- examples/one/yarn.lock
- examples/two/yarn.lock
- expo-package/yarn.lock
- native-package/yarn.lock
- src/components/ChannelList.js
- src/components/ChannelListMessenger.js
- yarn.lock
> Fixing duplicate channels issue

- examples/one/yarn.lock
- examples/two/yarn.lock
- expo-package/yarn.lock
- native-package/yarn.lock
- src/components/ChannelInner.js
- src/components/MessageList.js
- src/components/MessageNotification.js
- src/styles/styles.js
- yarn.lock
> Mark read functionality on seeing the message

- package.json
- rollup.config.js
- src/utils.js
- styleguide.config.js
- yarn.lock
move from react-native-simple-markdown to @stream-io/react-native-simple-markdown to resolve https://www.npmjs.com/advisories/815
> CHAT-603 use patched markdown lib

- README.md
> Updating readme with instructions for running example two

- CHANGELOG.md
- src/components/Card.js
- src/components/MessageSimple/MessageContent.js
> Fixing attachments

- src/components/ChannelPreviewMessenger.js
> Making channel preview compatible for 1-1 messaging

- examples/one/yarn.lock
- examples/two/yarn.lock
- expo-package/package.json
- expo-package/rollup.config.js
- expo-package/src/index.js
- expo-package/yarn.lock
- native-package/yarn.lock
- yarn.lock
> Changes to support Expo 34

- src/components/MessageInput.js
- src/components/MessageSimple/MessageContent.js
- src/styles/theme.js
> CHAT-777 : Adding custom styling support for action sheet

- src/components/AutoCompleteInput.js
- src/components/MessageInput.js
- src/components/MessageList.js
- src/components/SendButton.js
- src/components/docs/SendButton.md
- src/components/index.js
- styleguide.config.js
> CHAT-796: Adding custom SendButton prop support to MessageInput 

- src/components/ChannelInner.js
- src/components/MessageList.js
> CHAT-704: Making empty typing object immutable

- src/components/ChannelInner.js
> Limiting query channel calls

- src/components/ChannelInner.js
- src/components/MessageList.js
> CHAT-541: Marking channel read only if unreadCount is > 0

- src/components/Gallery.js
> CHAT-828: Closing image gallery on back press on android

- src/components/MessageSimple/MessageContent.js
> Fixing styles for message actionsheet

- src/components/MessageInput.js
- src/components/MessageList.js
- src/components/MessageSimple/MessageContent.js
- src/components/MessageSimple/index.js
> CHAT-857: Adding style support for ActionSheet

- CHANGELOG.md
- src/components/Attachment.js
- src/components/FileAttachmentGroup.js
- src/components/MessageList.js
- src/components/MessageSimple/MessageContent.js
- src/components/MessageSimple/index.js
> CHAT-858: Adding support for custom prop for file icon

- src/components/Attachment.js
- src/components/FileIcon.js
- src/components/FileUploadPreview.js
- src/components/MessageInput.js
- src/components/index.js
- types/index.d.ts
> CHAT-858: Updating typescript file

- src/components/ChannelInner.js
- src/components/ChannelList.js
- src/components/ChannelListMessenger.js
- src/components/Chat.js
> CHAT-627: Adding logs for homes issue

- src/components/ChannelList.js
- src/components/MessageList.js
> CHAT-814: Optimizing ChannelList and MessageList components

- CHANGELOG.md
- src/components/AutoCompleteInput.js
- src/components/MessageList.js
> CHAT-885: TypingIndicatorContainer fix

- examples/ExpoMessaging/yarn.lock
- examples/NativeMessaging/yarn.lock
- expo-package/yarn.lock
- native-package/yarn.lock
- src/components/ChannelList.js
- types/index.d.ts
- yarn.lock
> Handler for channel.deleted event in ChannelList component

- src/components/ChannelList.js
- types/index.d.ts
> CRNS-32: Handling channel.truncated event

- README.md
- examples/NativeMessaging/android/app/src/main/AndroidManifest.xml
- examples/NativeMessaging/ios/NativeMessaging/Info.plist
> CRNS-34: Fixing examples and readme for image picker functionality

- src/components/ChannelInner.js
- src/components/MessageList.js
https://github.com/GetStream/stream-chat-react-native/issues/85
> CRNS-33: Fixing issue with event history when message list is empty

- src/components/Thread.js
- types/index.d.ts
> CRNS-48: Adding props for thread customization

- src/components/ChannelList.js
> allow changing of filters and sort params to update channellist

- src/components/ChannelPreview.js
- src/components/ChannelPreviewMessenger.js
- src/components/MessageSimple/MessageContent.js
- src/components/MessageSimple/index.js
- types/index.d.ts
Fixes https://github.com/GetStream/stream-chat-react-native/issues/122 and https://github.com/GetStream/stream-chat-react-native/issues/121
> CRNS-58, 59: Adding support for custom message length in Channel preview

- types/index.d.ts
Fixes https://github.com/GetStream/stream-chat-react-native/issues/120
> CRNS-60: Adding types for SendButton component

- src/components/MessageSystem.js
Fixes https://github.com/GetStream/stream-chat-react-native/issues/117
> CRNS-62: Fixing date in MessageSystem

- src/components/LoadingIndicator.js
- src/styles/theme.js
- types/index.d.ts
> CRNS-63: Adding style and text customizability to LoadingIndicator

- src/components/AttachButton.js
- src/components/MessageInput.js
- src/components/docs/AttachButton.md
- styleguide.config.js
- types/index.d.ts
Resolves https://github.com/GetStream/stream-chat-react-native/issues/119
> CRNS-61: Adding prop for AttachButton to MessageInput

- src/components/ChannelPreviewMessenger.js
Fixes https://github.com/GetStream/stream-chat-react-native/issues/123
> CRNS-65:  Fixing channel preview avatars

- src/components/Gallery.js
Regarding https://getstream.zendesk.com/agent/tickets/1821
> CRNS-67: Fixing image index for image viewer

- src/components/Channel.js
- src/components/ChannelInner.js
- src/components/ChannelPreviewMessenger.js
- src/components/KeyboardCompatibleView.js
- src/components/MessageInput.js
- types/index.d.ts
> CRNS-74 and CRNS-75: Fixing issues with KeyboardCompatibleView and preview messanger

- types/index.d.ts
> fix context provider hoc typings

- src/components/Message.js
> Allow moderator to edit/delete message

- src/utils/Streami18n.js
> Disable escaping in translator functions

- src/components/KeyboardCompatibleView.js
- src/components/MessageSimple/MessageContent.js
> CRNS-79: Disable keyboard listeners when app goes to background

- src/components/Channel.js
- src/components/ChannelInner.js
- types/index.d.ts
> CRNS-78: Prop to override markRead function

- src/components/TypingIndicator.js
- src/styles/theme.js
- types/index.d.ts
> CRNS-76: Style-support updates to TypingIndicator

- src/components/Thread.js
> MessageList & MessageInput customization in Thread

- src/components/ChannelList.js
> Subscribing channellist to user.updated events

- src/components/MessageSimple/MessageAvatar.js
- removing superfluous ternary in MessageAvatar
> removing superfluous ternary in MessageAvatar

- src/components/Card.js
- src/components/MessageSimple/MessageContent.js
- if a Card Cover image uri is null, stop showing it
- some spelling fixes
> if a Card Cover image uri is null, stop showing it. some spelling fixes

- src/components/ReactionPicker.js
- remove ReactionCount entirely from ReactionPicker if hideReactionCount is true
> remove ReactionCount entirely from ReactionPicker if hideReactionCount is true

- src/components/EmptyStateIndicator.js
> Update placeholder text

- src/components/AttachButton.js
- src/components/AutoCompleteInput.js
- src/components/Channel.js
- src/components/ChannelInner.js
- src/components/Message.js
- src/components/MessageInput.js
- src/components/MessageList.js
- src/components/MessageSimple/MessageContent.js
- src/components/MessageSimple/index.js
- src/components/SendButton.js
- src/components/Thread.js
- types/index.d.ts
> Frozzen channel

- expo-package/yarn.lock
- native-package/yarn.lock
- package.json
- src/components/Message.js
- yarn.lock
> Adding fix for checking if current user is moderator

- CHANGELOG.md
- README.md
- docs/cookbook.md
> fixing doc typos

- src/components/Message.js
- src/components/docs/KeyboardContext.md
- src/components/docs/ListProps.md
- src/components/docs/PreviewProps.md
- src/components/docs/Streami18n.md
- src/components/docs/withKeyboardContext.md
> more typo fixes

- src/components/CommandsItem.js
- src/styles/theme.js
> Update CommandsItem.js to allow styling for args and description

- src/components/AutoCompleteInput.js
- src/components/MessageInput.js
- src/components/SuggestionsProvider.js
- src/utils/index.js
Make mentions feature on MessageInput to use queryMembers endpoint, so that it works for channels with more than 100 members
> queryMembers endpoint implementation for mentions feature

- src/components/KeyboardCompatibleView.js
> Fixing enabled prop on KeyboardCompatibleView

- docs/cookbook.md
- src/components/Attachment.js
- src/components/ChannelInner.js
- src/components/Chat.js
- src/components/MessageSimple/MessageContent.js
- src/components/MessageSimple/index.js
- types/index.d.ts
> misc spelling fixes and removal of unused/superfluous code

- native-package/yarn.lock
- package.json
- src/components/MessageSimple/MessageContent.js
- src/components/MessageSimple/MessageTextContainer.js
- src/components/MessageSimple/index.js
- src/components/docs/renderText.md
- src/utils/renderText.js
- types/index.d.ts
- yarn.lock
add a markdownRules object option to be passed into MessageContent and MessageTextContainer to pass through to renderText and allow overriding or adding any custom rules to the markdown lib
> markdown rule customization

- src/components/MessageInput.js
> remove await from sendMessage

- types/index.d.ts
> add sendImageAsync type

- src/components/ChannelList.js
> Set active channel only on reload

- src/mock-builders/api/error.js
- src/mock-builders/api/getOrCreateChannel.js
- src/mock-builders/api/index.js
- src/mock-builders/api/queryChannels.js
- src/mock-builders/api/queryMembers.js
- src/mock-builders/api/sendMessage.js
- src/mock-builders/api/threadReplies.js
- src/mock-builders/api/utils.js
- src/mock-builders/event/channelDeleted.js
- src/mock-builders/event/channelTruncated.js
- src/mock-builders/event/channelUpdated.js
- src/mock-builders/event/connectionRecovered.js
- src/mock-builders/event/index.js
- src/mock-builders/event/messageDeleted.js
- src/mock-builders/event/messageNew.js
- src/mock-builders/event/messageRead.js
- src/mock-builders/event/messageUpdated.js
- src/mock-builders/event/notificationAddedToChannel.js
- src/mock-builders/event/notificationMessageNew.js
- src/mock-builders/event/notificationMutesUpdated.js
- src/mock-builders/event/notificationRemovedFromChannel.js
- src/mock-builders/generator/attachment.js
- src/mock-builders/generator/channel.js
- src/mock-builders/generator/index.js
- src/mock-builders/generator/member.js
- src/mock-builders/generator/message.js
- src/mock-builders/generator/reaction.js
- src/mock-builders/generator/user.js
- src/mock-builders/index.js
> Adding mock-builders

- src/components/index.js
> Exporting autocomplete component

- .eslintrc.json
- .prettierrc
- src/components/Attachment/Card.js
- src/components/Attachment/FileAttachment.js
- src/components/Attachment/Gallery.js
- src/components/Avatar/Avatar.js
- src/components/Avatar/__tests__/Avatar.test.js
- src/components/Channel/ChannelInner.js
- src/components/ChannelList/ChannelListMessenger.js
- src/components/ChannelPreview/ChannelPreviewMessenger.js
- src/components/ChannelPreview/__tests__/ChannelPreview.test.js
- src/components/MessageInput/ImageUploadPreview.js
- src/components/MessageInput/UploadProgressIndicator.js
- src/components/MessageList/MessageList.js
- src/components/Reaction/ReactionList.js
- src/components/Reaction/ReactionPicker.js
- src/components/SuggestionsProvider/SuggestionsProvider.js
- src/styleguideComponents/PathlineRenderer.js
- src/styleguideComponents/Slot.js
> CRNS-131: converting Avatar component from class to functional component and adding hooks and adding jsx lint configs

- src/components/CloseButton/CloseButton.js
- src/components/CloseButton/__tests__/CloseButton.test.js
> CRNS-147: converting CloseButton component from class to functional component and adding hooks

- src/components/Indicators/EmptyStateIndicator.js
- src/components/Indicators/LoadingErrorIndicator.js
- src/components/Indicators/LoadingIndicator.js
Indicator components, Vish said these don't need tests
> CRNS-118/Indicators

- src/components/KeyboardCompatibleView/KeyboardCompatibleView.js
- src/components/KeyboardCompatibleView/hooks/useAppState.js
- src/components/KeyboardCompatibleView/hooks/useKeyboardCompatibleHeight.js
> CRNS-119: attempting hooks changes to fix KeyboardCompatibleView conversion

- src/components/Message/MessageSimple/index.js
https://github.com/GetStream/stream-chat-react-native/issues/265
> Fixing the imports for MessageSimple subcomponents

- src/components/ChannelPreview/hooks/useChannelPreviewDisplayAvatar.js
- src/components/ChannelPreview/hooks/useChannelPreviewDisplayName.js
- src/components/ChannelPreview/hooks/useLatestMessagePreview.js
> Optimizing ChannelPreview hooks

- src/components/MessageInput/ActionSheetAttachment.js
- src/components/MessageInput/MessageInput.js
Fixes https://github.com/GetStream/stream-chat-react-native/issues/270
> Fixing attachment actionsheet ref

- native-package/yarn.lock
- src/components/Spinner/Spinner.js
> CRNS-125/Spinner

- src/components/docs/ChatContext.md
- src/components/docs/withChatContext.md
> chat-docs-update

- src/components/SuggestionsProvider/SuggestionsProvider.js
- src/components/docs/SuggestionsContext.md
- src/components/docs/withSuggestionsContext.md
> suggestions docs update

- native-package/yarn.lock
- src/components/AutoCompleteInput/AutoCompleteInput.js
- src/components/SuggestionsProvider/SuggestionsList.js
> SuggestionsProvider hotfix

- src/components/Chat/Chat.js
- src/components/Chat/hooks/useIsOnline.js
> Fixing useIsOnline hook

- CHANGELOG.md
- src/components/Chat/Chat.js
- src/components/Chat/hooks/useIsOnline.js
> channel list change log update

- src/components/MessageInput/FileUploadPreview.js
- src/components/MessageInput/__tests__/__snapshots__/FileUploadPreview.test.js.snap
- src/styles/theme.js
- CRNS-106: add theme support for FileUploadPreview component just like ImageUploadComponent. Closes #238
> CRNS-106: add theme support for FileUploadPreview component just like ImageUploadComponent

- CHANGELOG.md
- src/components/MessageList/MessageList.js
- adding Message component to props
- dropping support for dateSeparator and headerComponent
> MessageList fixes/changes

- src/components/Chat/Chat.js
- CRNS:128: adding stream-chat-react-native-{platform}-{package_version} to user agent header for chat client
> CRNS:128: adding stream-chat-react-native-{platform}-{package_version} to user agent header for chat client

- src/components/CloseButton/CloseButton.tsx
> CRNS-137/CloseButton

- CHANGELOG.md
> Add renderText to change log

- src/components/Indicators/LoadingIndicator.md
- src/components/Indicators/LoadingIndicator.tsx
- src/components/KeyboardCompatibleView/KeyboardCompatibleView.tsx
- src/components/KeyboardCompatibleView/hooks/useAppState.ts
- src/components/KeyboardCompatibleView/hooks/useKeyboardCompatibleHeight.ts
- src/context.js
- src/css.macro.js
> CRNS-139: typescript convert KeyboardCompatibleView

- docs/cookbook.md
- src/components/MessageInput/MessageInput.js
> update some docs off of image crop picker usage

- CHANGELOG.md
> Adding to CHANGELOG for recently merged FileUploadPreview PR

- src/components/Channel/Channel.js
- src/components/Channel/__tests__/Channel.test.js
> CRNS-155/Handle undefined channel

- CHANGELOG.md
- src/components/ChannelList/ChannelListMessenger.tsx
- src/components/ChannelPreview/ChannelPreview.tsx
- src/components/ChannelPreview/ChannelPreviewMessenger.tsx
- src/components/docs/ListProps.md
- src/components/docs/PreviewProps.md
- styleguide.config.js
> tsx-docs-update

- src/components/AutoCompleteInput/AutoCompleteInput.js
- src/components/Channel/Channel.js
- src/components/Message/MessageSimple/MessageContent.js
- src/components/Message/MessageSimple/MessageSimple.js
> Fixing issues found during testing of slack-clone

- src/components/ChannelList/ChannelList.js
- src/components/ChannelList/ChannelListMessenger.js
- src/components/ChannelList/hooks/usePaginatedChannels.js
> Fixing ChannelList UX

- src/components/AutoCompleteInput/AutoCompleteInput.tsx
- src/components/AutoCompleteInput/CommandsItem.tsx
- src/components/AutoCompleteInput/MentionsItem.tsx
- src/components/MessageInput/MessageInput.js
- src/contexts/suggestionsContext/SuggestionsContext.tsx
- src/contexts/suggestionsContext/SuggestionsList.tsx
- src/types/types.ts
- src/utils/utils.ts
> fix suggestion context and auto complete input with carrot farming

- src/components/Thread/Thread.js
> Use Message prop for Thread

- native-package/src/index.js
- src/components/Attachment/FileAttachment.js
> Adding file size to file attachment

- src/components/Attachment/Attachment.tsx
- src/components/Attachment/Card.tsx
- src/components/Attachment/FileAttachment.tsx
- src/components/Attachment/FileAttachmentGroup.tsx
- src/components/Channel/Channel.tsx
- src/components/ChannelList/ChannelList.tsx
- src/components/Message/Message.tsx
- src/components/Message/MessageSimple/MessageContent.tsx
- src/components/Message/MessageSimple/MessageSimple.tsx
- src/components/Message/MessageSimple/MessageTextContainer.tsx
- src/components/MessageInput/FileUploadPreview.tsx
- src/components/MessageInput/MessageInput.tsx
- src/components/MessageList/MessageList.tsx
- src/components/MessageList/TypingIndicator.tsx
- src/components/Reaction/ReactionPickerWrapper.tsx
> remove partials

- src/styleguideComponents/Wrapper.js
- styleguide.config.js
> wrap all doc components in theme

- src/components/MessageInput/MessageInput.js
> Fixing retry upload functionality

- src/components/KeyboardCompatibleView/KeyboardCompatibleView.js
> Fixing keyboard for android

- docs/cookbook.md
- src/components/Chat/Chat.tsx
- src/components/Message/MessageSimple/MessageSimple.tsx
- src/components/Message/MessageSimple/MessageTextContainer.tsx
- src/components/MessageInput/MessageInput.tsx
- src/contexts/index.ts
- src/contexts/themeContext/ThemeContext.tsx
- src/contexts/themeContext/utils/formatDotNotation.ts
- src/contexts/themeContext/utils/replaceCssShorthand.ts
- src/index.ts
- src/styles/styledComponents.ts
- src/utils/Streami18n.ts
Feedback based updates on ts converison
> Ts conversion updates

- docs/cookbook.md
- expo-package/package.json
- native-package/package.json
- package.json
- src/components/Chat/Chat.tsx
- src/components/Message/MessageSimple/MessageContent.tsx
- src/components/Message/MessageSimple/MessageSimple.tsx
- src/components/Message/MessageSimple/MessageTextContainer.tsx
- src/components/MessageInput/MessageInput.tsx
- src/contexts/index.ts
- src/contexts/themeContext/ThemeContext.tsx
- src/contexts/themeContext/utils/formatDotNotation.ts
- src/contexts/themeContext/utils/replaceCssShorthand.ts
- src/index.ts
- src/styles/styledComponents.ts
- src/utils/Streami18n.ts
- src/v2/components/Chat/Chat.tsx
- src/v2/components/Message/MessageSimple/MessageContent.tsx
- src/v2/components/Message/MessageSimple/MessageSimple.tsx
- src/v2/components/Message/MessageSimple/MessageTextContainer.tsx
- src/v2/components/MessageInput/MessageInput.tsx
- src/v2/contexts/index.ts
- src/v2/utils/Streami18n.ts
> merge master and update v2

- examples/ExpoMessaging/yarn.lock
- examples/NativeMessaging/yarn.lock
- examples/TypeScriptMessaging/yarn.lock
- expo-package/yarn.lock
- native-package/yarn.lock
- package.json
- src/components/Channel/Channel.tsx
- src/components/MessageList/__tests__/MessageList.test.js
- src/mock-builders/generator/message.js
- yarn.lock
> Chore: bump stream-chat

- src/components/KeyboardCompatibleView/KeyboardCompatibleView.tsx
> Fixing keyboard issue

- expo-package/package.json
- native-package/package.json
- package.json
- src/components/Message/MessageSimple/MessageActionSheet.tsx
- src/components/Message/MessageSimple/MessageContent.tsx
- src/components/Message/MessageSimple/MessageSimple.tsx
- src/components/Message/MessageSimple/utils/renderText.tsx
- src/components/MessageList/TypingIndicator.tsx
- src/components/MessageList/__tests__/__snapshots__/TypingIndicator.test.js.snap
- src/components/Reaction/ReactionPicker.tsx
- src/components/Thread/Thread.tsx
> Minor fixes/additions

- .github/workflows/test.yml
- examples/SampleApp/android/app/build.gradle
- examples/SampleApp/android/app/google-services.json
- examples/SampleApp/android/build.gradle
- examples/SampleApp/android/gradle.properties
- examples/SampleApp/ios/SampleApp.xcodeproj/project.pbxproj
- examples/SampleApp/ios/fastlane/Fastfile
> App distribution

- examples/SampleApp/package.json
- examples/SampleApp/yarn.lock
- examples/TypeScriptMessaging/package.json
- examples/TypeScriptMessaging/yarn.lock
- package.json
- src/v2/components/Attachment/FileAttachment.tsx
- src/v2/components/Message/Message.tsx
- src/v2/components/Message/MessageSimple/MessageAvatar.tsx
- src/v2/components/Message/MessageSimple/MessageContent.tsx
- src/v2/components/Message/MessageSimple/MessageReplies.tsx
- src/v2/components/Message/MessageSimple/MessageSimple.tsx
- src/v2/components/Message/MessageSimple/MessageStatus.tsx
- src/v2/components/Message/MessageSimple/ReactionList.tsx
- src/v2/components/MessageList/DateSeparator.tsx
- src/v2/components/MessageOverlay/MessageOverlay.tsx
- src/v2/components/MessageOverlay/OverlayReactionList.tsx
- src/v2/contexts/channelContext/ChannelContext.tsx
- src/v2/contexts/chatContext/ChatContext.tsx
- src/v2/contexts/messageContext/MessageContext.tsx
- src/v2/contexts/messagesContext/MessagesContext.tsx
- src/v2/contexts/threadContext/ThreadContext.tsx
- yarn.lock
> adding efficiencies to memo and memoizing contexts

- examples/SampleApp/src/icons/Close.tsx
- examples/SampleApp/src/screens/NewDirectMessagingScreen.tsx
- examples/SampleApp/src/screens/NewGroupChannelAddMemberScreen.tsx
> Adding close icon on selected users

- examples/SampleApp/src/screens/NewGroupChannelAssignNameScreen.tsx
> Fixing styles for group-name input box

- examples/SampleApp/src/components/UserSearch/UserSearchResults.tsx
- examples/SampleApp/src/hooks/useUserSelector.ts
- examples/SampleApp/src/icons/AddUser.tsx
- examples/SampleApp/src/icons/ChatsTab.tsx
- examples/SampleApp/src/icons/Check.tsx
- examples/SampleApp/src/icons/CheckSend.tsx
- examples/SampleApp/src/icons/Close.tsx
- examples/SampleApp/src/icons/Contacts.tsx
- examples/SampleApp/src/icons/EmptySearchState.tsx
- examples/SampleApp/src/icons/LeftArrow.tsx
- examples/SampleApp/src/icons/MentionsTab.tsx
- examples/SampleApp/src/icons/NewGroupIcon.tsx
- examples/SampleApp/src/icons/RightArrow.tsx
- examples/SampleApp/src/icons/SignOut.tsx
- examples/SampleApp/src/icons/StreamLogo.tsx
- examples/SampleApp/src/screens/NewGroupChannelAddMemberScreen.tsx
> Fixing loading state

- examples/ExpoMessaging/package.json
- examples/ExpoMessaging/yarn.lock
- examples/TypeScriptMessaging/ios/Podfile.lock
- examples/TypeScriptMessaging/package.json
- examples/TypeScriptMessaging/yarn.lock
- expo-package/package.json
- expo-package/v2.js
- expo-package/yarn.lock
- native-package/package.json
- native-package/v2.js
- native-package/yarn.lock
- src/v2/components/ImageGallery/ImageGallery.tsx
- src/v2/components/Message/Message.tsx
- src/v2/components/Message/MessageSimple/ReactionList.tsx
- src/v2/components/MessageOverlay/MessageActions.tsx
- src/v2/components/MessageOverlay/MessageOverlay.tsx
- src/v2/components/MessageOverlay/OverlayReactionList.tsx
- src/v2/contexts/messageContext/MessageContext.tsx
- src/v2/native.ts
- Adds animations to ios and android for reactions
- Adds longPress animation and haptics for ios (Android needs gesture handler adjustments for the same)
> add ios message press animation and haptics

- examples/SampleApp/src/hooks/usePaginatedUsers.ts
> Fixing pagination  and cleanup

- src/components/ChannelList/hooks/usePaginatedChannels.ts
- src/components/Message/Message.tsx
> Fix channel and retry bugs

- src/v2/components/MessageList/MessageList.tsx
- src/v2/components/MessageList/hooks/useMessageList.ts
- src/v2/components/Thread/Thread.tsx
> PR suggestions made on v1 components but making them for v2

- native-package/package.json
- src/components/MessageList/MessageList.tsx
- src/components/MessageList/hooks/useMessageList.ts
- src/components/Thread/Thread.tsx
Implements new `invertedList` prop for `MessagesList` component. Changes the direction of the list and locates `HeaderComponent` based on it.
> Inverted list prop

- src/components/MessageInput/MessageInput.tsx
- src/utils/utils.ts
Support ticket - https://getstream.zendesk.com/agent/tickets/8076
> Fixing mentions issue and adding `autocompleteSuggestionsLimit` prop

- examples/SampleApp/App.tsx
- examples/SampleApp/src/components/AddMemberBottomSheet.tsx
- examples/SampleApp/src/components/BottomSheet.tsx
- examples/SampleApp/src/components/ConfirmationBottomSheet.tsx
- examples/SampleApp/src/components/UserSearch/UserGridItem.tsx
- examples/SampleApp/src/components/UserSearch/UserSearchResults.tsx
- examples/SampleApp/src/components/UserSearch/UserSearchResultsGrid.tsx
- examples/SampleApp/src/context/AppOverlayContext.tsx
- examples/SampleApp/src/hooks/usePaginatedUsers.ts
- examples/SampleApp/src/icons/AddUser.tsx
- examples/SampleApp/src/screens/GroupChannelDetailsScreen.tsx
- examples/SampleApp/src/screens/NewGroupChannelAddMemberScreen.tsx
- examples/SampleApp/yarn.lock
> AddMember functionality

- src/v2/components/Channel/Channel.tsx
- src/v2/components/Indicators/LoadingIndicator.tsx
- src/v2/components/MessageList/MessageList.tsx
> Fixing loading indicator on Channel

- src/components/AutoCompleteInput/AutoCompleteInput.tsx
remove handleChange from dependency array
> remove handleChange from dependency array

- src/v2/components/ImageGallery/ImageGallery.tsx
- src/v2/components/ImageGallery/components/AnimatedGalleryImage.tsx
make images higher res for zoom view
> High res zoom

- Makefile
- examples/SampleApp/src/components/ChatScreenHeader.tsx
- examples/SampleApp/src/components/NetworkDownIndicator.tsx
- examples/SampleApp/src/screens/ChannelScreen.tsx
- examples/SampleApp/src/screens/GroupChannelDetailsScreen.tsx
- examples/SampleApp/src/screens/MenuDrawer.tsx
- examples/SampleApp/src/utils/getUserActivityStatus.ts
- src/components/Avatar/Avatar.tsx
- src/components/ChannelPreview/ChannelAvatar.md
- src/components/ChannelPreview/ChannelAvatar.tsx
- src/components/ChannelPreview/ChannelPreviewMessenger.tsx
- src/components/index.ts
**SDK level:**
- Added a new component - `ChannelAvatar`. Which is a wrapper around GroupAvatar and Avatar. Makes it easy to use elsewhere, without having to deal with - if it's a group channel or direct conversation and when to show presence indicator.
**Sample App level**
- Used `ChannelAvatar` on top-right on `ChannelScreen`.
- Abstracted out NetworkDownIndicator to separate component - and reused in `ChatScreen` and `ChannelScreen`.
And some tiny styling fixes here and there as per QA by Mark.
> Design review feedback and some cleanup

- src/components/Channel/Channel.tsx
- src/components/ChannelPreview/hooks/useLatestMessagePreview.ts
> fix messages[messages.length - 1] undefined issue

- CHANGELOG.md
- examples/ExpoMessaging/package.json
- examples/ExpoMessaging/yarn.lock
- examples/NativeMessaging/ios/Podfile.lock
- examples/NativeMessaging/package.json
- examples/NativeMessaging/yarn.lock
- examples/SampleApp/ios/Podfile.lock
- examples/SampleApp/package.json
- examples/SampleApp/src/components/MessageSearch/MessageSearchList.tsx
- examples/SampleApp/yarn.lock
- examples/TypeScriptMessaging/ios/Podfile.lock
- examples/TypeScriptMessaging/package.json
- examples/TypeScriptMessaging/yarn.lock
- expo-package/package.json
- expo-package/src/index.js
- native-package/package.json
- native-package/src/index.js
- src/components/AttachmentPicker/AttachmentPicker.tsx
- src/components/AttachmentPicker/components/AttachmentSelectionBar.tsx
- src/components/MessageInput/MessageInput.tsx
- src/contexts/attachmentPickerContext/AttachmentPickerContext.tsx
- src/contexts/messageInputContext/MessageInputContext.tsx
- src/native.ts
[CRNS-232](https://stream-io.atlassian.net/browse/CRNS-232)
- adding expo/native image compression for images picked through the camera roll or taken through the camera
> adding expo/native image compression for images picked through the camera roll or taken through the camera

- src/components/ChannelList/ChannelList.tsx
- src/components/ChannelList/hooks/listeners/useChannelTruncated.ts
- src/components/ChannelList/hooks/listeners/useConnectionRecovered.ts
- src/components/ChannelList/hooks/usePaginatedChannels.ts
- src/components/ChannelPreview/ChannelPreview.tsx
> fix watchers reconencting

- src/components/Message/Message.tsx
- src/components/Message/MessageSimple/MessageStatus.tsx
- src/components/Message/hooks/useCreateMessageContext.ts
- src/components/MessageList/MessageList.tsx
- src/components/MessageList/hooks/useMessageList.ts
- src/components/MessageList/utils/getGroupStyles.ts
- src/contexts/messageContext/MessageContext.tsx
- src/contexts/messageOverlayContext/MessageOverlayContext.tsx
- src/contexts/messagesContext/MessagesContext.tsx
- src/contexts/threadContext/ThreadContext.tsx
I made some type tweaks based on some unknowns I noted in MessageType
> add type tweaks and guards

- src/components/Message/MessageSimple/MessageContent.tsx
- src/contexts/themeContext/utils/theme.ts
> Make MessageContent to occupy parent width

- CHANGELOG.md
- README.md
- src/contexts/themeContext/ThemeContext.tsx
On iOS this doesn't seem to be much of an issue (iPhone is much better than android to start with). But on android, when you press on reaction or if you long press the message - it takes a long time to open message overlay. After some profiling, it seems like this deepClone on every re-render is quite expensive. If we memoize that, it improves the UX alot (not sure though if this will break something):
https://user-images.githubusercontent.com/11586388/108605113-6ae99d00-73b2-11eb-8410-954cb51e1fd5.mov
https://user-images.githubusercontent.com/11586388/108605119-72a94180-73b2-11eb-9dbf-a7541941089e.mov
Also `cloneDeep` is quite slower than `JSON.parse(JSON.stringify(...))` for large objects. For smaller objects, its the opposite way. For our default theme, `JSON.parse(JSON.stringify)` …
> Optimizing ThemeContext

- CHANGELOG.md
> Updating changelog for v3 release

- package.json
- src/components/Message/Message.tsx
- src/components/Message/MessageSimple/MessageContent.tsx
- src/components/Message/MessageSimple/MessageSimple.tsx
- src/components/Message/MessageSimple/MessageStatus.tsx
- src/components/Message/MessageSimple/MessageTextContainer.tsx
- src/components/Message/hooks/useCreateMessageContext.ts
- src/components/MessageList/MessageList.tsx
- src/contexts/messageContext/MessageContext.tsx
- yarn.lock
Fixes most of the issues related to remove immutable flat list renders. The next step is to break messages out to further improve the render cycle.
> Improve non immutable rendering

- src/contexts/messageInputContext/MessageInputContext.tsx
> Fixed: restrict empty message

- CHANGELOG.md
- src/components/ImageGallery/ImageGallery.tsx
- src/contexts/messageInputContext/MessageInputContext.tsx
- src/contexts/messagesContext/MessagesContext.tsx
> Added changelog for 3.1.0 and some prop docs

- package.json
> Fixed ts build pointer in package.json

- bin/release.sh
- package.json
- scripts/post_version.sh
- We need to make sure update to version.json happens before we call `npm version`, so its part of the tag and published package.
> moving post_version script logic to release script

- examples/SampleApp/package.json
- examples/SampleApp/patches/@react-native-community+blur+3.6.0.patch
- examples/SampleApp/yarn.lock
> Sample App - Adding patch for blur view

- expo-package/package.json
- expo-package/src/index.js
- expo-package/yarn.lock
- native-package/package.json
- native-package/src/index.js
- native-package/yarn.lock
- src/components/Chat/Chat.tsx
- src/native.ts
> enabling tracking SDK client usage type between expo and react-native

- package.json
- src/utils/Streami18n.ts
> adding customization to Streami18n i18nextConfig and fixing copy-translations typescript creation

- src/components/MessageList/MessageList.tsx
> fixed goToMessage functionality on quoted reply

- src/components/MessageList/MessageList.tsx
> invert empty list component

- src/components/Message/MessageSimple/MessageTextContainer.tsx
- src/components/Message/MessageSimple/utils/renderText.tsx
- src/components/MessageOverlay/MessageOverlay.tsx
Fixes theming issue on overlay for my messages
> CRNS-306 - fix theme on outer overlay for my message

- src/components/MessageInput/MessageInput.tsx
add additionalTextInputProps to memo
> make additionalTextInputProps part of memo check

- native-package/src/index.js
> fix android camera permission check

- src/components/ImageGallery/components/ImageGrid.tsx
> fix for bang bang condition

- src/components/ChannelList/hooks/usePaginatedChannels.ts
- Generate `sortString` memoized value for sort parameter on usePaginatedChannels
- Add `sortString` to `reloadList` useEffect dependencies
> CRNS-280: Reload channels when sort changes on usePaginatedChannels

- src/components/ImageGallery/components/ImageGalleryHeader.tsx
Fix calendar call on moment that creates error due to incorrect type from moment.
> fix moment js issue with calendar

- src/components/ImageGallery/ImageGallery.tsx
Fixes edge case that only has been seen in a test channel.
> fix image selector edge case

- package.json
Move copy translation location to correct folder.
> fix translations copy location for TS

- src/components/Channel/hooks/useTargetedMessage.ts
> cleanup around targeted message

- src/components/Channel/Channel.tsx
- src/components/Message/Message.tsx
- src/components/MessageInput/MessageInput.tsx
Fix issues that were found while building new docs
> fix nav issues found in docs

- .github/workflows/docusaurus.yml
- src/components/Channel/Channel.tsx
- src/components/Message/MessageSimple/MessageSimple.tsx
> docusaurus automation and 2 simple changes

- .github/workflows/legacy-sample-distribution.yml
- .github/workflows/sample-distribution.yml
> Update workflow names and run distribution on every push to master

- .github/workflows/legacy-sample-distribution.yml
- .github/workflows/sample-distribution.yml
> Ignore docusaurus path on distribution scripts

- src/components/Message/MessageSimple/MessageStatus.tsx
> CRNS-291: add render states missing message status check marks

- src/components/ImageGallery/components/ImageGalleryFooter.tsx
Change image index numbers to match ios style
> change image viewer index numbers to match ios ordering

- docusaurus/docs/reactnative/contexts/thread_context.mdx
- docusaurus/docs/reactnative/contexts/typing_context.mdx
> add thread and typing contexts docs

- docusaurus/docs/reactnative/customization/contexts.mdx
> add closing to contexts docs

- src/components/Attachment/Card.tsx
- src/components/Attachment/FileAttachment.tsx
- src/components/Attachment/Gallery.tsx
- src/components/Attachment/Giphy.tsx
- src/components/Channel/hooks/useCreateThreadContext.ts
- src/components/Message/Message.tsx
- src/components/Message/MessageSimple/MessageContent.tsx
- src/components/Message/MessageSimple/MessageReplies.tsx
- src/components/Message/MessageSimple/MessageTextContainer.tsx
- src/components/Message/MessageSimple/ReactionList.tsx
- src/components/Message/MessageSimple/utils/renderText.tsx
- src/components/MessageList/utils/getReadStates.ts
- src/components/MessageOverlay/MessageOverlay.tsx
- src/contexts/messageContext/MessageContext.tsx
- src/contexts/messageOverlayContext/MessageOverlayContext.tsx
Fixes crash on longpress on overlay and readby being incorrect for non 1:1
> Fix emitter and read by

- docusaurus/docs/reactnative/customization/custom_components.mdx
- docusaurus/docs/reactnative/customization/native_handlers.mdx
- docusaurus/docs/reactnative/customization/theming.mdx
- docusaurus/docs/reactnative/customization/typescript.mdx
> Customization docs

- .gitignore
- examples/ExpoMessaging/metro.config.js
- examples/NativeMessaging/metro.config.js
- examples/SampleApp/metro.config.js
- examples/TypeScriptMessaging/metro.config.js
- metro-dev-helpers.js
- metro-dev-helpers/extract-linked-packages.js
- metro-dev-helpers/lib/extract-extra-node-modules.js
- metro-dev-helpers/lib/find-linked-packages.js
- metro-dev-helpers/lib/index.js
> Use new metro-dev-helpers instead of copy-pasted metro config on examples

- docusaurus/docs/reactnative/common-content/core-components/overlay-provider/props/attachment_picker_bottom_sheet_handle.mdx
- docusaurus/docs/reactnative/common-content/core-components/overlay-provider/props/attachment_picker_bottom_sheet_handle_height.mdx
- docusaurus/docs/reactnative/common-content/core-components/overlay-provider/props/attachment_picker_bottom_sheet_height.mdx
- docusaurus/docs/reactnative/common-content/core-components/overlay-provider/props/attachment_picker_error.mdx
- docusaurus/docs/reactnative/common-content/core-components/overlay-provider/props/attachment_picker_error_button_text.mdx
- docusaurus/docs/reactnative/common-content/core-components/overlay-provider/props/attachment_picker_error_image.mdx
- docusaurus/docs/reactnative/common-content/core-components/overlay-provider/props/attachment_picker_error_text.mdx
- docusaurus/docs/reactnative/common-content/core-components/overlay-provider/props/attachment_selection_bar_height.mdx
- docusaurus/docs/reactnative/common-content/core-components/overlay-provider/props/camera_selector_icon.mdx
- docusaurus/docs/reactnative/common-content/core-components/overlay-provider/props/file_selector_icon.mdx
- docusaurus/docs/reactnative/common-content/core-components/overlay-provider/props/i18n_instance.mdx
- docusaurus/docs/reactnative/common-content/core-components/overlay-provider/props/image_gallery_custom_components.mdx
- docusaurus/docs/reactnative/common-content/core-components/overlay-provider/props/image_gallery_grid_handle_height.mdx
- docusaurus/docs/reactnative/common-content/core-components/overlay-provider/props/image_gallery_grid_snap_points.mdx
- docusaurus/docs/reactnative/common-content/core-components/overlay-provider/props/image_overlay_selected_component.mdx
- docusaurus/docs/reactnative/common-content/core-components/overlay-provider/props/image_selector_icon.mdx
- docusaurus/docs/reactnative/common-content/core-components/overlay-provider/props/number_of_attachment_images_to_load_per_call.mdx
- docusaurus/docs/reactnative/common-content/core-components/overlay-provider/props/number_of_attachment_picker_image_columns.mdx
- docusaurus/docs/reactnative/common-content/core-components/overlay-provider/props/number_of_image_gallery_grid_columns.mdx
- docusaurus/docs/reactnative/common-content/core-components/overlay-provider/props/overlay_reaction_list.mdx
- docusaurus/docs/reactnative/common-content/core-components/overlay-provider/props/overlay_reactions.mdx
- docusaurus/docs/reactnative/common-content/core-components/overlay-provider/props/value.mdx
- docusaurus/docs/reactnative/core-components/overlay_provider.mdx
> OverlayProver edit

- docusaurus/docs/reactnative/guides/dev_setup_and_sample_apps.mdx
> Dev setup docs

- docusaurus/docs/reactnative/common-content/core-components/chat/props/client.mdx
- docusaurus/docs/reactnative/core-components/chat.mdx
- docusaurus/docs/reactnative/core-components/overlay_provider.mdx
> chat tweaks

- docusaurus/docs/reactnative/contexts/theme_context.mdx
- docusaurus/docs/reactnative/contexts/translation_context.mdx
- docusaurus/docs/reactnative/core-components/chat.mdx
> Add missing context docs

- src/components/Channel/Channel.tsx
> Update thread messages if thread is open when removing a message

- .github/workflows/release-candidate.yml
> ci: Run rc workflow on project level instead of only on package

- examples/SampleApp/src/components/AddMemberBottomSheet.tsx
- examples/SampleApp/src/components/UserSearch/UserGridItem.tsx
> fix(android): Fix add member bottom sheet touchables

- .github/workflows/next-release.yml
> ci: Only run next release for changes on package dir

- examples/SampleApp/README.md
> chore(SampleApp): Update readme steps for running the project

- package/src/components/ChannelList/ChannelListMessenger.tsx
> fix(android): Fix pull to refresh on ChannelList

- package/src/components/MessageOverlay/OverlayReactions.tsx
> fix(reactions): Fix overflowing reactions list and double scroll on Android

- package/src/components/Message/MessageSimple/MessageDeleted.tsx
> fix: Fix missing translations for message deleted

- .github/workflows/check-pr.yml
- package.json
> ci: Add pr checks for lint and build scripts

- package/src/components/Chat/Chat.tsx
- package/src/contexts/overlayContext/OverlayProvider.tsx
- package/src/hooks/index.ts
- package/src/hooks/useStreami18n.ts
- package/src/index.ts
> refactor: Move useStreami18n hook to hooks folder

- examples/SampleApp/ios/Podfile.lock
- package/src/components/Channel/Channel.tsx
- package/src/components/Thread/Thread.tsx
Thanks @nhannah for the nice pair programming session!
> fix: Fix messages disappearing on reconnect

- docusaurus/docs/reactnative/guides/message_actions_customization.mdx
> docs: fixing a typo in code example

- docusaurus/docs/reactnative/common-content/contexts/message-context/is_my_message.mdx
- docusaurus/docs/reactnative/common-content/contexts/message-input-context/set_show_more_options.mdx
- docusaurus/docs/reactnative/common-content/contexts/message-input-context/set_text.mdx
- docusaurus/docs/reactnative/common-content/contexts/message-input-context/toggle_attachment_picker.mdx
- docusaurus/docs/reactnative/common-content/contexts/message-input-context/trigger_settings.mdx
> docs: more docs related cleanup

- package/src/components/AttachmentPicker/components/AttachmentSelectionBar.tsx
- package/src/components/AttachmentPicker/components/FileSelectorIcon.tsx
- package/src/components/MessageInput/MessageInput.tsx
> feat: Allow images and attachments on the same message

- package/src/components/Message/Message.tsx
- package/src/components/Message/MessageSimple/MessageContent.tsx
- package/src/components/Message/MessageSimple/MessageSimple.tsx
- package/src/components/Message/MessageSimple/MessageTextContainer.tsx
- package/src/components/Message/hooks/useCreateMessageContext.ts
- package/src/components/MessageOverlay/MessageOverlay.tsx
- package/src/components/Reply/Reply.tsx
blocked by https://github.com/GetStream/stream-chat-js/pull/726
> fix: Fix quoted images/attachments

- examples/SampleApp/src/hooks/usePaginatedUsers.ts
- examples/SampleApp/src/screens/GroupChannelDetailsScreen.tsx
[CRNS-313](https://stream-io.atlassian.net/browse/CRNS-313)
- Exclude current user from user search list, in channel creation screen.
- Fix for `owner` label in member's list on group details.
> fix: fixing channel creation flow in sample app

- examples/SampleApp/yarn.lock
- package/package.json
- package/yarn.lock
> chore: upgrade stream-chat dep to 3.13.1

- README.md
> docs: updating readme with new docs link

- examples/NativeMessaging/ios/Podfile.lock
- examples/NativeMessaging/yarn.lock
- package/src/components/MessageInput/InputButtons.tsx
- package/src/components/MessageInput/MessageInput.tsx
- package/src/contexts/messageInputContext/MessageInputContext.tsx
> fix: Fix giphy and attachment icon hiding issue

- examples/NativeMessaging/ios/Podfile.lock
- examples/NativeMessaging/yarn.lock
- package/src/components/MessageInput/InputButtons.tsx
- package/src/components/MessageInput/MessageInput.tsx
- package/src/contexts/messageInputContext/MessageInputContext.tsx
> Next release

- docusaurus/docs/reactnative/core-components/channel.mdx
- docusaurus/docs/reactnative/guides/message_input_customization.mdx
- package/src/components/MessageInput/MessageInput.tsx
> fix(attachment-picker): fixing sync logic between `imageUploads` and `selectedImages`

- docusaurus/docs/reactnative/guides/message_actions_customization.mdx
> docs: fixed example for message action customization

- docusaurus/docs/reactnative/guides/message_actions_customization.mdx
> docs: fixed example for message action customisation

- release/release.config.js
> chore: Allow major releases on breaking changes

- docusaurus/docs/reactnative/basics/getting_started.mdx
- [ x ] I have signed the [Stream CLA](https://docs.google.com/forms/d/e/1FAIpQLScFKsKkAJI7mhCr7K9rEIOpqIDThrWxuvxnwUq2XkHyG154vQ/viewform) (required).
- [ x ] The code changes follow best practices
- [ x ] Code changes are tested (add some information if not applicable)
Minor typo
> docs: Fixing a typo in docusaurus > basics > getting started

- docusaurus/docs/reactnative/core-components/channel.mdx
> docs: Fix threadList header on Channel

- examples/SampleApp/ios/Podfile.lock
- examples/SampleApp/package.json
- examples/SampleApp/src/utils/AsyncStore.ts
- examples/SampleApp/yarn.lock
- package/expo-package/yarn.lock
- package/native-package/yarn.lock
- package/package.json
- package/yarn.lock
> fix: Hotfix for peer deps collision

- docusaurus/docs/reactnative/basics/translations.mdx
> docs: small fix to i18n docs

- package/expo-package/src/index.js
- package/native-package/src/index.js
Close https://github.com/GetStream/stream-chat-react-native/issues/825
> fix: unable to share user photo

- package/src/components/ChannelList/hooks/listeners/useConnectionRecovered.ts
Close https://github.com/GetStream/stream-chat-react-native/issues/832
> fix: update refreshList reference

- package/src/components/MessageList/MessageList.tsx
- package/src/components/MessageList/__tests__/__snapshots__/MessageList.test.js.snap
- package/src/components/Thread/__tests__/__snapshots__/Thread.test.js.snap
- package/src/contexts/messageInputContext/MessageInputContext.tsx
> fix: allow images attached through file picker to display in gallery view

- examples/NativeMessaging/ios/Podfile.lock
- examples/NativeMessaging/yarn.lock
- examples/SampleApp/ios/Podfile.lock
- examples/SampleApp/yarn.lock
- examples/TypeScriptMessaging/ios/Podfile.lock
- examples/TypeScriptMessaging/yarn.lock
- package/Makefile
- package/expo-package/yarn.lock
- package/native-package/yarn.lock
- package/package.json
- package/src/contexts/messageInputContext/MessageInputContext.tsx
- package/yarn.lock
> fix: delegate content type detection to backend for image/file uploads

- package/src/components/Message/MessageSimple/utils/renderText.tsx
[CRNS-408](https://stream-io.atlassian.net/browse/CRNS-408)
| Before | After |
| - | - |
| <img width="628" alt="Screenshot 2021-09-14 at 18 20 46" src="https://user-images.githubusercontent.com/11586388/133295856-63b9b4c0-d96d-4952-9a38-f3a0150a2c08.png"> | <img width="628" alt="Screenshot 2021-09-14 at 18 20 24" src="https://user-images.githubusercontent.com/11586388/133295872-3c1f1b86-b9ae-4a4c-b7e8-bb69a4cd0128.png"> |
> fix: fixed markdown issues with lists

- docusaurus/docs/reactnative/guides/message_input_customization.mdx
> docs: added example for custom CDN for image-file attachments

- examples/SampleApp/src/components/BottomTabs.tsx
- examples/SampleApp/src/components/MessageSearch/MessageSearchList.tsx
- examples/SampleApp/src/screens/ChannelListScreen.tsx
- examples/SampleApp/src/screens/MentionsScreen.tsx
Reference Ticket - https://stream-io.atlassian.net/browse/CRNS-286
> Feat: Bottom Tabs Scroll to top on press

- docusaurus/docs/reactnative/basics/troubleshooting.mdx
I've added a reference to the guide aiba has to get an app with RN running on a MacBook with the M1 SoC, as it's the most concise/straight-forward guide about the issue I've seen or been pointed to as of yet.
> docs: Add a link to aiba's guide for RN on M1 macs

- package/tsconfig.json
> fix: type definition directory structure

- package/src/components/MessageInput/FileUploadPreview.tsx
- package/src/components/MessageInput/__tests__/__snapshots__/FileUploadPreview.test.js.snap
This PR fixes the issue in removing failed attachment uploads from MessageInput.
Reference Ticket - https://stream-io.atlassian.net/browse/CRNS-393
> fix: remove failed attachment uploads

- package/src/components/MessageList/MessageList.tsx
> fix: fixed markRead() logic when Channel is mounted

- docusaurus/docs/reactnative/guides/message_actions_customization.mdx
> docs: how to add custom styles for message action title

- package/src/components/Channel/Channel.tsx
> feat: added a support for prop 'newMessageStateUpdateThrottleInterval'

- package/src/components/Attachment/Gallery.tsx
- package/src/components/Channel/Channel.tsx
> refactor: fixing some typescript issues and prop mess

- docusaurus/docs/reactnative/customization/native_handlers.mdx
> docs: added more examples for override native handler

- package/src/components/Attachment/Gallery.tsx
> refactor: additional fixes for gallery memoizations

- .github/workflows/release.yml
`bootstrap-ci` runs `yarn install --frozen-lockfile`
See above
<details>
| Before | After |
| --- | --- |
| img | img |
</details>
<details>
| Before | After |
| --- | --- |
| img | img |
</details>
> chore: Remove duplicate install when building release

- PULL_REQUEST_TEMPLATE.md
Re: #953 - changing the tables for screenshots from markdown to HTML as that makes it work better/easier.
> chore: Change PR template img table to HTML

- package/src/components/Message/Message.tsx
"Block User" action does nothing at the moment, due to wrong syntax of action provided.
Fix the action.
NA
> fix: 'Block User' message action

- docusaurus/docs/reactnative/ui-components/auto_complete_input.mdx
Documentation for the prop `cooldownActive` is missing on `AutoCompleteTextInput`, this aims to fix that.
> docs: Document cooldownActive on AutoCompleteTextInput

- package/src/components/MessageInput/MessageInput.tsx
-------
This removes a call to `console.log` left from debugging in another branch.
> chore: Remove unwanted console.log

- docusaurus/docs/reactnative/common-content/core-components/channel/props/input.mdx
- docusaurus/docs/reactnative/common-content/core-components/channel/props/thread.mdx
- docusaurus/docs/reactnative/common-content/core-components/overlay-provider/props/attachment_picker_error_button_text.mdx
- docusaurus/docs/reactnative/common-content/core-components/overlay-provider/props/attachment_picker_error_image.mdx
- docusaurus/docs/reactnative/common-content/core-components/overlay-provider/props/attachment_picker_error_text.mdx
Fixes a few broken links in our docs, reported by docusaurus
> docs: Fix broken links

- .github/workflows/check-pr.yml
Opening a PR to test whether this works/checks run on this PR
> build: Make matcher more permissive

- docusaurus/docs/reactnative/common-content/core-components/overlay-provider/props/overlay_reactions_avatar.mdx
- docusaurus/docs/reactnative/contexts/message_overlay_context.mdx
- docusaurus/docs/reactnative/core-components/overlay_provider.mdx
- docusaurus/docs/reactnative/ui-components/overlay_reactions_avatar.mdx
- package/src/components/MessageOverlay/MessageOverlay.tsx
- package/src/components/MessageOverlay/OverlayReactions.tsx
- package/src/components/MessageOverlay/OverlayReactionsAvatar.tsx
- package/src/components/index.ts
- package/src/contexts/messageOverlayContext/MessageOverlayContext.tsx
- package/src/contexts/overlayContext/OverlayContext.tsx
- package/src/contexts/overlayContext/OverlayProvider.tsx
This comes from [this ticket](https://getstream.zendesk.com/agent/tickets/16320) where the customer wanted to customize all avatars in their app, but the one in OverlayReactions does not allow for this.
Having a prop `OverlayReactionsAvatar` can help us achieve customizability. The component is exposed to the following props:
- `reaction`
- `size` from the AvatarProps
Usage Guide:
```jsx
import {
OverlayProvider,
OverlayReactionsAvatar,
} from 'stream-chat-react-native';
const App = () => {
return <OverlayProvider
OverlayReactionsAvatar={({ reaction, size }) => (
<OverlayReactionsAvatar reaction={reaction} size={60} />
)}
>
{/* Underlying components */}
</OverlayProvider>
}
```
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr> …
> Feat: Message overlay-reactions avatar customization [CRNS - 478]

- .github/workflows/check-pr.yml
https://github.com/tpbowden/chonkbot
See [Slack](https://getstream.slack.com/archives/C74PFN5HT/p1641984943006000)
> build: Report chonkiness in PRs

- package/yarn.lock
This PR resolves the conflict in the v4.0.0-beta.2 branch.
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
> Chore: Resolve conflict in target branch

- examples/ExpoMessaging/yarn.lock
- examples/NativeMessaging/yarn.lock
- examples/SampleApp/yarn.lock
- examples/TypeScriptMessaging/yarn.lock
Updates lockfiles for our sample apps.
> chore: update sample app lockfiles

- docusaurus/docs/reactnative/basics/upgrade_helper.mdx
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
> docs: upgrade helper docs for beta.4

- package/src/components/Avatar/Avatar.tsx
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
> fix: simple doc fix to fix next release

- README.md
Fix typescript example link on the README file
Change the URL
-
Click the Typescript example on the README.md
> docs: fix typo on Typescript example link

- package/src/components/MessageOverlay/MessageOverlay.tsx
- package/src/components/MessageOverlay/OverlayReactionList.tsx
Removes a setter that doesn't have a value being used in the component.
> refactor: remove unused setReactionListHeight

- package/src/components/MessageList/MessageList.tsx
Fixes: https://github.com/GetStream/stream-chat-react-native/issues/1170
Have added the details in code comment
> fix: mark channel as read when messages length is less than visible screen

- package/src/components/ImageGallery/ImageGallery.tsx
- package/src/components/ImageGallery/components/ImageGrid.tsx
- package/src/components/MessageOverlay/MessageOverlay.tsx
- package/src/contexts/overlayContext/OverlayProvider.tsx
Fixes: https://github.com/GetStream/stream-chat-react-native/issues/1148
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
> fix: image gallery cleanup and fixing race condition

- docusaurus/docs/reactnative/basics/upgrade_helper.mdx
Fixes - https://getstream.slack.com/archives/C02155MJNQG/p1646329175635679
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
> Docs: Typos in upgrade helper guide

- package/src/components/ChannelList/hooks/usePaginatedChannels.ts
Fixes: https://github.com/GetStream/stream-chat-react-native/issues/1192
> fix: pull to refresh functionality [CRNS-536]

- examples/SampleApp/src/components/UserInfoOverlay.tsx
This PR adds the TS single generic `StreamChatGeneric` to the `UserInfoOverlay` which was missing previously.
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
> fix: add TS single generic in UserInfoOverlay.tsx of SampleApp

- package/src/components/ImageGallery/ImageGallery.tsx
This PR focuses on fixing the rendering issues of giphy on Image Gallery because of old data format since they weren't considered previously.
Added the condition:
`(attachment.type === 'giphy' &&
(attachment.giphy?.[giphyVersion]?.url ||
attachment.thumb_url ||
attachment.image_url))`
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
> fix: issues with opening old Giphy on ImageGallery

- package/src/components/ChannelList/hooks/listeners/__tests__/useChannelUpdated.test.tsx
- package/src/components/Chat/Chat.tsx
- package/src/components/Chat/hooks/__tests__/useAppSettings.test.tsx
- package/src/components/Chat/hooks/useAppSettings.ts
- package/src/components/Chat/hooks/useCreateChatContext.ts
- package/src/contexts/chatContext/ChatContext.tsx
Adds appSettings to the ChatContext
- [sorta] New code is covered by tests
> feat: add appSettings to ChatContext

- package/CHANGELOG.md
- package/src/components/AttachmentPicker/AttachmentPicker.tsx
- package/src/components/Channel/Channel.tsx
- package/src/components/Chat/Chat.tsx
- package/src/components/Message/Message.tsx
- package/src/components/Message/MessageSimple/utils/renderText.md
- package/src/contexts/attachmentPickerContext/AttachmentPickerContext.tsx
- package/src/contexts/channelContext/ChannelContext.md
- package/src/contexts/channelContext/ChannelContext.tsx
- package/src/contexts/channelsContext/ChannelsContext.md
- package/src/contexts/channelsContext/ChannelsContext.tsx
- package/src/contexts/chatContext/ChatContext.md
- package/src/contexts/imageGalleryContext/ImageGalleryContext.md
- package/src/contexts/keyboardContext/KeyboardContext.md
- package/src/contexts/messageContext/MessageContext.md
- package/src/contexts/messageContext/MessageContext.tsx
- package/src/contexts/messageInputContext/MessageInputContext.md
- package/src/contexts/messageInputContext/MessageInputContext.tsx
- package/src/contexts/messageOverlayContext/MessageOverlayContext.tsx
- package/src/contexts/messagesContext/MessagesContext.md
- package/src/contexts/messagesContext/MessagesContext.tsx
- package/src/contexts/overlayContext/OverlayContext.md
- package/src/contexts/paginatedMessageListContext/PaginatedMessageListContext.md
- package/src/contexts/suggestionsContext/SuggestionsContext.md
- package/src/contexts/typingContext/TypingContext.md
Correcting broken urls to the repo
click on link in this file ```src/contexts/messagesContext/MessagesContext.tsx:88``` should not result in a 404 error
- [NR] I have signed the [Stream CLA](https://docs.google.com/forms/d/e/1FAIpQLScFKsKkAJI7mhCr7K9rEIOpqIDThrWxuvxnwUq2XkHyG154vQ/viewform) (required)
- [NR] New code is covered by tests
- [ NR] Screenshots added for visual changes
> docs: fixes broken links by adding */package/* in the url path

- docusaurus/docs/reactnative/customization/custom_components.mdx
Fixing a typo in Equality secion in docs
Check this [page[(https://getstream.io/chat/docs/sdk/reactnative/customization/custom_components/#equality) import should be important
- [NR] I have signed the [Stream CLA](https://docs.google.com/forms/d/e/1FAIpQLScFKsKkAJI7mhCr7K9rEIOpqIDThrWxuvxnwUq2XkHyG154vQ/viewform) (required)
- [NR] New code is covered by tests
- [NR] Screenshots added for visual changes
> docs: fixes typo in equality section

- package/src/components/MessageList/ScrollToBottomButton.tsx
- package/src/components/MessageList/__tests__/__snapshots__/ScrollToBottomButton.test.js.snap
- package/src/contexts/themeContext/utils/theme.ts
Fixes #1310 
Added the theme property `chevronColor` to the component using our global theme.
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
> feat: add theming support for the chevron icon in scroll to bottom button

- docusaurus/docs/reactnative/basics/troubleshooting.mdx
* Reanimated 2 installation links were broken and must be fixed.
* babel config file needed clarification about alternatives, informed by a customer.
* proguard must be added as an another reanimated troubleshooting part.
* point to babel docs for babel config clarity.
* change to new URL links for reanimated 2 docs.
NA
NA
> fix: reanimated 2 installation links were broken

- README.md
docs: removes the broken link to the native app, that is not existing
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
> docs: removes broken link to native app

- README.md
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
> docs: adds link to WhatsApp clone

- docusaurus/docs/reactnative/basics/getting_started.mdx
Keeping the table up-to-date with newer versions - reanimated 2.3.1 breaks with 4.2.0 of the SDK, whereas 2.4.0 works fine.
:)
:)
:)
> chore: update version compability table

- package/src/components/Channel/hooks/useCreatePaginatedMessageListContext.ts
- package/src/components/Channel/hooks/useCreateThreadContext.ts
- package/src/utils/utils.ts
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
> fix: handle undefined updated_at on messages with util function

- docusaurus/docs/reactnative/basics/getting_started.mdx
This PR focuses on adding the packages essential to get the video running for native and expo CLIs. Additionally, the additional installation steps guide is added.
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
> docs: add installation guide and packages to existing guide for vide support

- .github/workflows/check-pr.yml
- README.md
- package/package.json
Adds sonar analysis on check-pr workflow
Adding a sonar analysis step to check pr job/workflow
N/A
running workflow locally with [act](https://github.com/nektos/act#overview----) `act --secret-file ../act.secrets -j check_pr`
> chore: adds sonar analysis on check-pr workflow

- examples/SampleApp/ios/SampleApp.xcodeproj/project.pbxproj
- examples/SampleApp/ios/SampleApp/Info.plist
- examples/SampleApp/ios/SampleAppTests/Info.plist
Incrementing build number to fix ios publish
> chore: incrementing build number to fix ios publish

- README.md
- package/src/components/ChannelList/ChannelList.tsx
- package/src/components/MessageInput/MessageInput.tsx
- package/src/components/MessageList/MessageList.tsx
- package/src/components/Thread/Thread.tsx
- package/src/contexts/channelsContext/ChannelsContext.tsx
- package/src/contexts/messageInputContext/MessageInputContext.tsx
- package/src/contexts/messagesContext/MessagesContext.tsx
Replace all links to the old docs from the code base.
Linking to the new docs
N/A
Click through new links and check for dead links.
> docs: links all docs links to new documentation

- PULL_REQUEST_TEMPLATE.md
Updating PR template
I've removed non-relevant topics that are being automatically checked or are redundant and already exists in the template (test cov., conventional commits, and screenshots)
I've added and emphasized the need for testing and reviewing the features from the customer and end user's POV throughout relevant example apps.
N/A
N/A
> chore: updating PR template

- docusaurus/docs/reactnative/basics/troubleshooting.mdx
- examples/SampleApp/android/app/src/main/AndroidManifest.xml
- examples/TypeScriptMessaging/android/app/src/main/AndroidManifest.xml
Fixes #1509
Followed https://developer.android.com/training/package-visibility/use-cases#check-browser-available
NA
Open any external link on Android in the TS example or Sample App
> fix: query all packages should not be needed

- .github/workflows/next-release.yml
Our Sonarcloud quality gate, does not compute, due to the lack of test coverage on the `develop` branch
Adding sonar cloud analysis step before beta publish
N/A
N/A
> chore: adds sonar cloud analysis to next-release.yml

- examples/ExpoMessaging/yarn.lock
- examples/SampleApp/yarn.lock
- examples/TypeScriptMessaging/yarn.lock
- package/expo-package/yarn.lock
- package/native-package/yarn.lock
- package/package.json
- package/yarn.lock
Update bottom sheet lib to avoid a race condition that caused #1179 
NA
NA
NA
> fix: update bottom sheet lib to avoid race condition

- docusaurus/docs/reactnative/basics/upgrade_helper.mdx
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
> docs: removed cdn v2 note since its default now

- .github/workflows/docusaurus.yml
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
> build: move docs publishing to v5-release branch

- .github/workflows/docusaurus.yml
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
> build: set target branch to production

- examples/ExpoMessaging/yarn.lock
- examples/SampleApp/yarn.lock
- examples/TypeScriptMessaging/yarn.lock
- package/expo-package/yarn.lock
- package/native-package/yarn.lock
- package/package.json
- package/yarn.lock
- fixes #1395 
- fixes #1598 
NA
NA
NA
> fix: update markdown package to fix prop types import error 

- examples/ExpoMessaging/yarn.lock
- examples/SampleApp/yarn.lock
- examples/TypeScriptMessaging/yarn.lock
- package/expo-package/yarn.lock
- package/native-package/yarn.lock
- package/package.json
- package/yarn.lock
Reverts GetStream/stream-chat-react-native#1619
> Revert "fix: update markdown package to fix prop types import error "

- examples/ExpoMessaging/yarn.lock
- examples/SampleApp/yarn.lock
- examples/TypeScriptMessaging/yarn.lock
- package/expo-package/yarn.lock
- package/native-package/yarn.lock
- package/package.json
- package/yarn.lock
Reverts GetStream/stream-chat-react-native#1622
> Revert "Revert "fix: update markdown package to fix prop types import error ""

- package/src/components/ChannelList/__tests__/ChannelList.test.js
- package/src/components/ChannelList/hooks/listeners/useNewMessage.ts
- package/src/mock-builders/event/messageNew.js
Fixes #1463 
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
> fix: handle hidden channels in message.new listener

- package/src/components/Attachment/utils/getGiphyMimeType.ts
- package/src/components/ImageGallery/ImageGallery.tsx
> feat: add support for sharing mp4 and webp giphy attachments

- .github/workflows/next-release.yml
Increasing node version for Job
> fix: SampleApp app icons in right format (renaming files)

- docusaurus/docs/reactnative/basics/getting_started.mdx
> docs: add android install steps for react-native-video

- docusaurus/docs/reactnative/basics/getting_started.mdx
Adds compatible RN 0.69, SDK, and reanimated versions
Docs update by adding a new line to the table
> docs: adds compatible RN 0.69, SDK and reanimated versions

- docusaurus/docs/reactnative/basics/getting_started.mdx
- docusaurus/docs/reactnative/basics/upgrade_helper.mdx
- examples/SampleApp/ios/Podfile.lock
- examples/SampleApp/package.json
- examples/SampleApp/yarn.lock
- examples/TypeScriptMessaging/ios/Podfile.lock
- examples/TypeScriptMessaging/package.json
- examples/TypeScriptMessaging/yarn.lock
- package/native-package/package.json
- package/native-package/src/index.js
Removing the usage of our cameraroll fork to the new v5 release. 
NA
NA
NA
> feat: use cameraroll v5 dependency

- docs/index.html
- docs/v3/index.html
- docusaurus/docs/reactnative/basics/upgrade_helper.mdx
> Next release (docs only)

- examples/TypeScriptMessaging/App.tsx
- package/src/components/Message/MessageSimple/ReactionList.tsx
- package/src/components/Message/hooks/useCreateMessageContext.ts
Fixes #1721 
Memoization logic is added to the `ReactionList` component. 
Note: This PR also changes the multiple usage of Chat component in every Screen component in TSMessagingApp.
Now the message overlay with reactions update in real time.
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
> fix: add memoization in ReactionList to update MessageOverlay in Realtime

- README.md
Fixes #1748 
Removing irrelevant section link
N/A
N/A
> docs: removing RN Compatibility from contents

- README.md
Fixes broken GH badges
N/A
N/A
Check md file visually
> docs: broken badges in readme.md updated

- docusaurus/docs/reactnative/guides/push_notifications_v2.mdx
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
> feat: add documentation to clear iOS notification badge count 

- docusaurus/docs/reactnative/basics/getting_started.mdx
Fixes #1727 
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
> docs: add documentation stating that we do not support Web in React Native SDK

- docusaurus/docs/reactnative/guides/push_notifications_v2.mdx
This limitation was removed with push v2, this PR removes the mention of the limit form the push v2 docs
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
> docs: remove member limit info for push v2

- docusaurus/docs/reactnative/customization/native_handlers.mdx
Fixes docs issue pointed out in https://github.com/GetStream/stream-chat-react-native/issues/1784
> docs: remove BlurView handler from native handler docs

- package/src/components/Chat/hooks/useConnectionRecovered.ts
> fix: don't allow empty cids for sync api call

- docusaurus/docs/reactnative/guides/livestream_messagelist.mdx
Change transperent to transparent.
Fix typo in code example.
Change transperent to transparent.
N/A
Verified updated markdown.
- [N/A] New code is tested in main example apps, including all possible scenarios
- [N/A ] SampleApp iOS and Android
- [ N/A] Expo iOS and Android
> fix(docs): typo in code example

- docusaurus/docs/reactnative/basics/upgrade_helper.mdx
- docusaurus/docs/reactnative/common-content/core-components/chat/props/image_component.mdx
- docusaurus/reactnative_versioned_docs/version-3.x.x/common-content/core-components/channel/props/thread.mdx
- docusaurus/reactnative_versioned_docs/version-3.x.x/common-content/core-components/overlay-provider/props/attachment_picker_error_button_text.mdx
- docusaurus/reactnative_versioned_docs/version-3.x.x/common-content/core-components/overlay-provider/props/attachment_picker_error_image.mdx
- docusaurus/reactnative_versioned_docs/version-3.x.x/common-content/core-components/overlay-provider/props/attachment_picker_error_text.mdx
- docusaurus/reactnative_versioned_docs/version-3.x.x/contexts/translation_context.mdx
- docusaurus/reactnative_versioned_docs/version-3.x.x/guides/message_actions_customization.mdx
- docusaurus/reactnative_versioned_docs/version-3.x.x/guides/upgrade_helper.mdx
- docusaurus/reactnative_versioned_docs/version-4.x.x/contexts/translation_context.mdx
- docusaurus/reactnative_versioned_docs/version-4.x.x/guides/message_actions_customization.mdx
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
> docs: fix broken links.

- package/src/components/ImageGallery/components/ImageGrid.tsx
- package/src/contexts/themeContext/utils/theme.ts
When scrolling the expanded BottomSheetFlatList in ImageGrid upwards, a white background color is exposed at the bottom of the screen, and currently, there is no way to customize it to a different color using theme configs.
Add a new theme config called `container` that applies a ViewStyle style prop to the BottomSheetFlatList component in ImageGrid.
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
> fix: Add theme config for BottomSheetFlatList in ImageGrid

- package/src/utils/DBSyncManager.ts
Fixes: https://github.com/GetStream/stream-chat-react-native/issues/1841
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
> fix: syncStatus of DBSyncManager is not updated correctly

- package/src/store/QuickSqliteClient.ts
Fixes: https://github.com/GetStream/stream-chat-react-native/issues/1843
> fix: expo app crashes due to sqlite being null

- examples/SampleApp/App.tsx
Sample app crashes on testflight. Upon investigation, I found out that this was the issue. 
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
> fix(sampleApp): crash on load due to import of devsettings module 

- .github/workflows/changelog-preview.yml
- .github/workflows/next-release.yml
- .github/workflows/release.yml
- .github/workflows/sample-distribution.yml
- examples/SampleApp/package.json
- package.json
- package/native-package/package.json
- package/package.json
> chore: yarn installs through all packages over bootstrap-ci

- examples/SampleApp/android/gradle.properties
- examples/SampleApp/ios/Podfile.lock
- examples/SampleApp/yarn.lock
Fixes the error `Execution failed for task ':react-native-gesture-handler:assertNoMultipleInstances'.` in SA
> fix: react-native-gesture-handler:assertNoMultipleInstances

- package/src/components/Message/utils/messageActions.ts
Fixes #1917 
We don't need a null type within the action type.
None
None
> fix: messageAction action type

- package/src/components/ChannelList/ChannelList.tsx
- package/src/components/ChannelList/hooks/listeners/useNewMessage.ts
- package/src/components/ChannelList/hooks/listeners/useNewMessageNotification.ts
Reverts GetStream/stream-chat-react-native#1920
> revert: "fix: show appropriate channel according to filter type defined when new message received"

- examples/TypeScriptMessaging/android/gradle.properties
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
> fix: android issue of multiple instances of react native gesture handler in TypeScriptMessaging app

- docusaurus/docs/reactnative/guides/multiple_channel_lists.mdx
- examples/ExpoMessaging/yarn.lock
- examples/SampleApp/yarn.lock
- examples/TypeScriptMessaging/yarn.lock
- package/expo-package/yarn.lock
- package/native-package/yarn.lock
- package/src/components/ChannelList/ChannelList.tsx
* fixes #1945 
* Also wanted by Feeld
did the exact same thing as done in react SDK. https://getstream.io/chat/docs/sdk/react/guides/multiple_channel_lists/#channelrenderfilterfn-prop
> feat: add prop for helping multiple channel list implementation

- .github/workflows/release.yml
> chore: change release process GitHub token to stream bot

- .github/workflows/release.yml
- .github/workflows/sample-distribution.yml
> chore: replace all vishal gh token with stream bot token

- examples/ExpoMessaging/yarn.lock
- examples/SampleApp/ios/Podfile.lock
- examples/SampleApp/yarn.lock
- examples/TypeScriptMessaging/ios/Podfile.lock
- examples/TypeScriptMessaging/yarn.lock
- package/expo-package/yarn.lock
- package/native-package/yarn.lock
- package/yarn.lock
- yarn.lock
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
> fix: update yarn.lock file of the root, packages and the example apps

- .github/workflows/docusaurus.yml
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
> fix: docusaurus workflow so that changes in develop are pushed to staging

- examples/TypeScriptMessaging/package.json
- examples/TypeScriptMessaging/yarn.lock
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
> chore: devtools package version upgrade to 1.1.0

- package/expo-package/src/handlers/NetInfo.ts
- package/expo-package/src/handlers/Sound.ts
- package/expo-package/src/handlers/compressImage.ts
- package/expo-package/src/handlers/takePhoto.ts
- package/native-package/src/handlers/NetInfo.ts
- package/native-package/src/handlers/compressImage.ts
- package/native-package/src/handlers/getPhotos.ts
- package/native-package/src/handlers/pickDocument.ts
- package/native-package/src/handlers/shareImage.ts
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
> fix: eslint sort errors and mode cover in compressImage.ts of native-package

- .github/workflows/sample-distribution.yml
- examples/SampleApp/fastlane/Matchfile
> chore: MATCH_GIT_BASIC_AUTHORIZATION update

- .github/workflows/sample-distribution.yml
Solve auth issues in sample dis pipeline
> chore: sample-distribution.yml update

- .github/workflows/sample-distribution.yml
> chore: Update sample-distribution.yml

- examples/ExpoMessaging/yarn.lock
- examples/SampleApp/ios/Podfile.lock
- examples/SampleApp/yarn.lock
- examples/TypeScriptMessaging/ios/Podfile.lock
- examples/TypeScriptMessaging/yarn.lock
- package/package.json
- package/yarn.lock
- yarn.lock
This reverts commit e49fc7c569c54735f15996dd5990b64c3f11dea9.
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
> fix: revert upgrade stream-chat version to 8.6.0 (#2077)

- .github/ISSUE_TEMPLATE/bug_report.md
Whether offline support is enabled or not plays a big role in triaging a potential bug. Therefore it was added to the bug template.
Addition to bug template
N/A
N/A
> chore: bug_report.md

- README.md
> docs: adding sonar badge

- examples/ExpoMessaging/yarn.lock
- examples/SampleApp/package.json
- examples/SampleApp/yarn.lock
- examples/TypeScriptMessaging/package.json
- examples/TypeScriptMessaging/yarn.lock
- package/expo-package/yarn.lock
- package/native-package/package.json
- package/native-package/yarn.lock
> feat: upgrading flatlist mvcp dep.

- examples/SampleApp/ios/Podfile.lock
- examples/SampleApp/package.json
- examples/SampleApp/yarn.lock
- examples/TypeScriptMessaging/ios/Podfile.lock
- examples/TypeScriptMessaging/package.json
- examples/TypeScriptMessaging/yarn.lock
- package/native-package/package.json
- package/native-package/src/optionalDependencies/pickDocument.ts
Fixes: #2115 
The JS error of variable being used before assign is also solved in this PR. 
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
> chore: upgrade react-native-document-picker to 9.0.1 and added related API changes

- package/expo-package/yarn.lock
- package/native-package/yarn.lock
- package/yarn.lock
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
> chore: upgrade yarn.lock file in package directory

- package/expo-package/package.json
- package/expo-package/src/handlers/getLocalAssetUri.ts
- package/expo-package/yarn.lock
- package/src/components/MessageInput/UploadProgressIndicator.tsx
- package/src/contexts/messageInputContext/MessageInputContext.tsx
- package/src/native.ts
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
> chore: upgrade expo-media-library dev dependency version to ~15.2.3

- package/src/components/Channel/Channel.tsx
- package/src/contexts/messageInputContext/MessageInputContext.tsx
Fixes #2068 
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
> fix: image upload issue for expo apps

- examples/ExpoMessaging/yarn.lock
- examples/SampleApp/yarn.lock
- examples/TypeScriptMessaging/Gemfile
- examples/TypeScriptMessaging/ios/Podfile.lock
- examples/TypeScriptMessaging/yarn.lock
- package/expo-package/yarn.lock
- package/native-package/yarn.lock
- package/src/components/ChannelPreview/ChannelPreviewMessenger.tsx
> chore: add client as dependency and update yarn locks

- examples/ExpoMessaging/Readme.md
- examples/SampleApp/yarn.lock
- examples/TypeScriptMessaging/yarn.lock
- package/expo-package/yarn.lock
- package/native-package/yarn.lock
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
> docs: add guide to fix the broken android build on Expo Messaging App and update yarn.lock files

- docusaurus/reactnative_versioned_docs/version-4.x.x/guides/push_notifications_v2.mdx
customer should be informed about the order for clarity
> fix: clarify the order of setLocalDevice

- examples/ExpoMessaging/yarn.lock
- examples/SampleApp/yarn.lock
- examples/TypeScriptMessaging/yarn.lock
- package/expo-package/yarn.lock
- package/native-package/yarn.lock
- package/package.json
- package/yarn.lock
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
> chore: update yarn.lock files and solve peer deps issue of eslint-plugin-typescript-sort-keys

- examples/ExpoMessaging/yarn.lock
- examples/SampleApp/yarn.lock
- examples/TypeScriptMessaging/yarn.lock
- package/expo-package/yarn.lock
- package/native-package/yarn.lock
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
> chore: update yarn lock files for packages and sample apps

- package/src/components/ChannelPreview/hooks/useLatestMessagePreview.ts
- package/src/components/Message/MessageSimple/utils/renderText.tsx
Fixes: https://github.com/GetStream/stream-chat-react-native/issues/2208
> fix: special character in mentioned user name causes crash

- package/src/components/MessageList/MessageList.tsx
fixes: https://github.com/GetStream/stream-chat-react-native/issues/2108
> fix: inline unread count indicator flickering on muted channels

- package/package.json
- package/src/components/Message/MessageSimple/utils/parseLinks.test.ts
- package/src/components/Message/MessageSimple/utils/parseLinks.ts
- package/yarn.lock
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
> fix: parsing the links with unconventional tlds

- package/src/i18n/ja.json
- To remove the following warning
```
WARN  Streami18n: Missing translation for key: 3 Replies 
at ThreadFooterComponentWithContext (http://localhost:8081/index.bundle//&platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.cookwithmoment.ios:253771:24)
at ThreadFooterComponent (http://localhost:8081/index.bundle//&platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.cookwithmoment.ios:253856:71)
at RCTView
at View (http://localhost:8081/index.bundle//&platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.cookwithmoment.ios:48920:43)
at RCTView
at View (http://localhost:8081/index.bundle//&platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.cookwithmoment.ios:48920:43)
at …
```
> Fix: missing Japanese translation

- package/package.json
- package/yarn.lock
Update stream-chat dependency to import the fix: https://github.com/GetStream/stream-chat-js/commit/a325737d8318e58d891d7106b543b1a36ed401a0
Fixes: https://github.com/GetStream/stream-chat-react-native/issues/2257
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
> fix: update stream-chat to fix failing get requests with undefined param

- package/package.json
- package/yarn.lock
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
> feat: upgrade axios to v1

- package/src/i18n/en.json
- package/src/i18n/fr.json
- package/src/i18n/he.json
- package/src/i18n/hi.json
- package/src/i18n/it.json
- package/src/i18n/ja.json
- package/src/i18n/ko.json
- package/src/i18n/nl.json
- package/src/i18n/ru.json
- package/src/i18n/tr.json
Fixes #2227 
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
> feat: add maximum file size limit release translations

- package/src/components/MessageInput/MessageInput.tsx
- package/src/contexts/messageInputContext/MessageInputContext.tsx
Apply translations to message input component.
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
> fix: apply max file size limit translations

- package/expo-package/src/handlers/iOS14RefreshGallerySelection.ts
- package/expo-package/src/handlers/index.ts
- package/expo-package/src/handlers/oniOS14GalleryLibrarySelectionChange.ts
Move functions to independent files.
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
> refactor: iOS Gallery refresh files change

- examples/ExpoMessaging/package.json
- examples/ExpoMessaging/yarn.lock
- examples/SampleApp/ios/SampleApp.xcodeproj/project.pbxproj
- examples/SampleApp/yarn.lock
- examples/TypeScriptMessaging/yarn.lock
- package/expo-package/yarn.lock
- package/native-package/yarn.lock
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
> chore: update yarn lock deps for packages and example apps

- package/src/components/ImageGallery/ImageGallery.tsx
> fix: unnecessary reanimated warning

- README.md
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
> docs: update build status badge in README.md

- examples/SampleApp/src/components/BottomSheetOverlay.tsx
- examples/SampleApp/src/components/ChannelInfoOverlay.tsx
- examples/SampleApp/src/components/UserInfoOverlay.tsx
- package/src/hooks/index.ts
Fixes sample app crash due to #2310 
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
> fix: sample-app crash because of viewport changes

- package/src/components/MessageInput/UploadProgressIndicator.tsx
Fixes #2324 
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
> fix: upload progress indicator component type

- package/package.json
- package/yarn.lock
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
> fix: upgrade stream-chat to fix uploadFile issue

- package/src/components/Message/MessageSimple/utils/generateMarkdownText.ts
- package/src/components/Message/MessageSimple/utils/parseLinks.test.ts
- package/src/components/Message/MessageSimple/utils/parseLinks.ts
Fixes #2337 
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
> fix: remove url encoding

- package/src/components/MessageOverlay/MessageActionListItem.tsx
Fixes #2351 
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
> fix: message action list item title theme

- package/src/contexts/__tests__/index.test.tsx
- package/src/contexts/channelsStateContext/ChannelsStateContext.tsx
- package/src/contexts/messageInputContext/MessageInputContext.tsx
Fixes #2344 
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
> feat: compress images selected through file picker while upload

- docusaurus/docs/reactnative/state-and-offline-support/contexts.mdx
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
> docs: add context docs to state and offline section

- docusaurus/docs/reactnative/advanced-guides/internationalization.mdx
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
> docs: add internationalization guide

- .styles/Vocab/Base/accept.txt
- docusaurus/docs/reactnative/basics/installation.mdx
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
> docs: add installation guide to Basics section

- package/src/utils/utils.ts
Fixes #2373 
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
> fix: emoji skin_variations undefined warning when emoji is not found

- package/src/components/AutoCompleteInput/AutoCompleteSuggestionList.tsx
- package/src/components/MessageInput/MessageInput.tsx
- package/src/components/Thread/__tests__/__snapshots__/Thread.test.js.snap
Fixes #1490 
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
> fix: autocomplete suggestion list scroll issue

- examples/TypeScriptMessaging/ios/Podfile.lock
- examples/TypeScriptMessaging/ios/TypeScriptMessaging.xcodeproj/project.pbxproj
- examples/TypeScriptMessaging/package.json
- examples/TypeScriptMessaging/yarn.lock
- package/src/components/Channel/Channel.tsx
- package/src/components/MessageInput/MessageInput.tsx
- package/src/components/MessageList/MessageList.tsx
- package/src/components/MessageList/hooks/useMessageList.ts
fixes #2396
fixes #2395
* TS app, update to latest 0.71
* some chore refactors having no influence
> fix: unnecessary thread reload

- examples/TypeScriptMessaging/android/app/src/release/java/com/typescriptmessaging/ReactNativeFlipper.java
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
> fix: ReactNativeFlipper TS app package import

- package/src/components/Message/Message.tsx
- package/src/components/MessageList/MessageList.tsx
Fixes #2409 
After
https://github.com/GetStream/stream-chat-react-native/assets/39884168/b524c40e-907a-454a-a215-e71e4e79ef60
> fix: scroll to bottom when message is removed from message list

- package/src/components/MessageInput/SendButton.tsx
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
> fix: send button icon theme

- docusaurus/docs/reactnative/common-content/core-components/channel/props/message_bounce.mdx
- docusaurus/docs/reactnative/contexts/messages_context.mdx
- docusaurus/docs/reactnative/core-components/channel.mdx
- docusaurus/docs/reactnative/guides/message_customizations.mdx
- docusaurus/docs/reactnative/ui-components/message_bounce.mdx
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
> docs: add message bounce docs

- package/src/components/MessageInput/MessageInput.tsx
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
> fix: auto complete suggestion list container theme

- package/src/components/MessageInput/UploadProgressIndicator.tsx
- package/src/contexts/themeContext/utils/theme.ts
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
> feat: introduce upload progress indicator spinner theme color

- package/src/components/Chat/Chat.tsx
- package/src/components/Chat/hooks/useSyncDatabase.ts
> fix: do not render channels on offline support before db init

- examples/SampleApp/metro.config.js
- examples/TypeScriptMessaging/metro.config.js
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
> fix: metro config for example apps

- package/src/components/Attachment/Card.tsx
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
> fix: authorNameFooterContainer theme in Card component

- examples/ExpoMessaging/app.json
- examples/ExpoMessaging/babel.config.js
- examples/ExpoMessaging/metro.config.js
- examples/ExpoMessaging/package.json
- examples/ExpoMessaging/yarn.lock
- package/expo-package/yarn.lock
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
> feat: expo 50 version upgrade in sample app

- docusaurus/docs/reactnative/basics/installation.mdx
- docusaurus/docs/reactnative/basics/overview.mdx
- docusaurus/shared
Fixes
1. Sync the selection of Expo tabs between the install pages and within the page
2. Babel config reanimated addition clarification
3. Gesture handler wrapper clarification
> docs: improve expo installation explanations

- package/src/components/Attachment/Giphy.tsx
Prev:
Now:
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
> fix: giphy border radius and color issue

- package/src/components/Chat/hooks/handleEventToSyncDB.ts
- package/src/contexts/messagesContext/MessagesContext.tsx
- package/src/store/apis/getChannelsForFilterSort.ts
- package/src/store/apis/queries/selectMembersForChannels.ts
- package/src/store/apis/upsertChannelDataFromChannel.ts
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
> fix: broken imports in SDK as per TS

- package/src/components/Message/MessageSimple/MessageContent.tsx
- package/src/components/Message/MessageSimple/MessageFooter.tsx
- package/src/components/Message/MessageSimple/MessagePinnedHeader.tsx
- package/src/components/Message/MessageSimple/MessageSimple.tsx
- package/src/components/Message/MessageSimple/__tests__/__snapshots__/MessagePinnedHeader.test.js.snap
- package/src/components/Thread/__tests__/__snapshots__/Thread.test.js.snap
- package/src/contexts/themeContext/utils/theme.ts
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
> feat: introduce grouped message theming for message and fix message pinned header styles

- docusaurus/docs/reactnative/basics/troubleshooting.mdx
- docusaurus/docs/reactnative/common-content/ui-components/overlay-provider/props/attachment_picker_bottom_sheet_height.mdx
- docusaurus/docs/reactnative/common-content/ui-components/overlay-provider/props/attachment_selection_bar_height.mdx
- docusaurus/docs/reactnative/contexts/overlay-context.mdx
- docusaurus/docs/reactnative/core-components/overlay-provider.mdx
- package/src/components/AttachmentPicker/AttachmentPicker.tsx
- package/src/components/AttachmentPicker/components/AttachmentPickerSelectionBar.tsx
- package/src/components/ImageGallery/ImageGallery.tsx
- package/src/components/ImageGallery/components/ImageGalleryHeader.tsx
- package/src/components/MessageInput/MessageInput.tsx
- package/src/components/MessageInput/__tests__/MessageInput.test.js
- package/src/components/index.ts
- package/src/contexts/attachmentPickerContext/AttachmentPickerContext.tsx
- package/src/contexts/overlayContext/OverlayContext.tsx
- package/src/contexts/overlayContext/OverlayProvider.tsx
- package/src/hooks/index.ts
- package/src/hooks/useScreenDimensions.ts
The goal of the PR is to improve the image gallery and the attachment picker bottom sheet implementation. Specially the snapshot is fixed and the code is much more simpler now.
Changes to be noted:
- The attachment picker height and the selection bar height can now be customized by the integrators which was not working as expected before.
- The `translucentStatusBar` property is now removed. Integrators can handle it by adding padding on their side if needed.
- The `AttachmentPickerSelectionBar` prop is added so as to customize the selection bar which contains the camera, image and file picker icons.
- Screen height is considered now rather than window height for the Attachment Picker.
- More meaningful variable names for the image gallery.
<details>
<table>
<thead> …
> fix: improve attachment picker and image gallery bottom sheet implementation

- package/native-package/src/handlers/getPhotos.ts
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
> fix: ts issue in getPhotos around Platform.Version

- package/src/components/ImageGallery/ImageGallery.tsx
- package/src/contexts/overlayContext/OverlayContext.tsx
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
> fix: image gallery handle height ts issue

- examples/SampleApp/android/app/src/main/AndroidManifest.xml
- examples/SampleApp/android/build.gradle
- examples/SampleApp/ios/Podfile.lock
- examples/SampleApp/ios/SampleApp.xcodeproj/project.pbxproj
- examples/SampleApp/package.json
- examples/SampleApp/src/screens/ChannelScreen.tsx
- examples/SampleApp/src/screens/NewDirectMessagingScreen.tsx
- examples/SampleApp/src/screens/ThreadScreen.tsx
- examples/SampleApp/yarn.lock
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
> feat: add async audio feature to sample app

- package/native-package/src/optionalDependencies/Audio.ts
- package/src/components/MessageInput/hooks/useAudioController.tsx
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
> fix: handle react native audio recorder player optionally

- package/src/components/MessageList/MessageList.tsx
Fixes #2499 
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
> fix: add undefined check for message when checking for isMessageUnread

- package/src/components/MessageList/MessageList.tsx
- package/src/components/Thread/__tests__/__snapshots__/Thread.test.js.snap
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
> fix: empty message list UI and scrolling issue

- examples/ExpoMessaging/yarn.lock
- examples/SampleApp/yarn.lock
- examples/TypeScriptMessaging/yarn.lock
- package/expo-package/package.json
- package/expo-package/yarn.lock
- package/native-package/yarn.lock
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
> fix: add expo-clipboard to peer deps of expo-package

- package/src/i18n/ja.json
Improved Japanese translation
Corrected Japanese translation of message used in `<MessagePinnedHeader>` .
N/A
N/A
> fix: Correct Japanese translation

- examples/ExpoMessaging/types.ts
- examples/SampleApp/src/components/ChannelInfoOverlay.tsx
- examples/SampleApp/src/components/ChannelPreview.tsx
- examples/SampleApp/src/components/ConfirmationBottomSheet.tsx
- examples/SampleApp/src/types.ts
- examples/TypeScriptMessaging/App.tsx
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
> fix: example app TS issue and icons props issue

- package/src/components/Message/MessageSimple/MessageFooter.tsx
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
> fix: message edited label edited time stamp

- package/src/components/MessageList/MessageList.tsx
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
> fix: empty message list text string crash bug

- package/src/components/Message/MessageSimple/ReactionList.tsx
- package/src/contexts/themeContext/utils/theme.ts
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
> feat: configure ReactionList reaction theme

- package/expo-package/src/handlers/Video.tsx
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
> fix: audio for the video muted when the silent mode is on for iOS

- package/src/components/Channel/Channel.tsx
- package/src/contexts/messageInputContext/MessageInputContext.tsx
- package/src/utils/utils.ts
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
> fix: upload image issue when clicking a photo using expo-image-picker on Expo 51

- examples/ExpoMessaging/app/channel/[cid]/index.tsx
- examples/ExpoMessaging/app/channel/[cid]/thread/[cid]/index.tsx
- package/package.json
- package/src/components/ImageGallery/ImageGallery.tsx
- package/src/components/ImageGallery/components/ImageGalleryFooter.tsx
- package/src/components/ImageGallery/components/ImageGalleryHeader.tsx
- package/src/components/ImageGallery/hooks/useImageGalleryGestures.tsx
- package/src/components/Message/MessageSimple/ReactionList.tsx
- package/src/components/MessageInput/MessageInput.tsx
- package/src/components/MessageOverlay/MessageActionListItem.tsx
- package/src/components/MessageOverlay/MessageOverlay.tsx
- package/src/components/MessageOverlay/OverlayReactionList.tsx
- package/src/components/MessageOverlay/hooks/useMessageActionAnimation.tsx
- package/src/components/ProgressControl/ProgressControl.tsx
- package/src/components/ProgressControl/WaveProgressBar.tsx
- package/src/contexts/themeContext/utils/theme.ts
- package/yarn.lock
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
> fix: change old gesture handler useAnimatedGestureHandler to the new API

- package/src/components/Message/MessageSimple/ReactionList.tsx
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
> fix: memoization issue for ReactionList count

- package/src/components/Message/hooks/useMessageActions.tsx
- package/src/icons/Pin.tsx
- package/src/icons/Resend.tsx
- package/src/icons/index.ts
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
> fix: delete message action UI and resend icon

- examples/SampleApp/ios/Podfile.lock
- examples/SampleApp/ios/SampleApp.xcodeproj/project.pbxproj
- examples/SampleApp/package.json
- examples/SampleApp/yarn.lock
- examples/TypeScriptMessaging/ios/Podfile.lock
- examples/TypeScriptMessaging/package.json
- examples/TypeScriptMessaging/yarn.lock
- package/native-package/package.json
- package/native-package/yarn.lock
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
> fix: upgrade react-native-video to a stable version 6.4.2 from the previously beta version

- .styles/Vocab/Base/accept.txt
- docusaurus/docs/reactnative/contexts/message-input-context.mdx
- docusaurus/docs/reactnative/guides/date-time-formatting.mdx
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
> chore: vale lint issues

- package/src/components/Message/MessageSimple/MessageTextContainer.tsx
Fixes [this Zendesk issue](https://getstream.zendesk.com/agent/tickets/55303).
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
> fix: issue with message.status in MessageTextContainer

- docusaurus/docs/reactnative/common-content/contexts/threads-context/thread-list-item.mdx
- docusaurus/docs/reactnative/contexts/threads-context.mdx
- docusaurus/docs/reactnative/guides/custom-thread-list.mdx
- docusaurus/docs/reactnative/state-and-offline-support/state-overview.mdx
- docusaurus/docs/reactnative/ui-components/thread-list.mdx
- docusaurus/sidebars-react-native.json
- package/src/components/ThreadList/ThreadList.tsx
- package/src/contexts/index.ts
Some last minute changes I thought to do before we go live with the feature. Nothing breaking, just some clarifications.
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
> fix: threads v2 minor improvements and docs fixes

- examples/ExpoMessaging/yarn.lock
- package/expo-package/src/handlers/Audio.ts
- package/src/components/ChannelList/ChannelListMessenger.tsx
Fixes this [Zendesk issue](https://getstream.zendesk.com/agent/tickets/55808).
- Whenever unmounting, the `recording` is already cleaned up and we don't need to do anything - hence the `null` check
- RN's `RefreshControl` used in a `FlatList` does not seem to be working well and this is a [well known issue](https://github.com/facebook/react-native/issues/24855) that sometimes happens; fortunately the `FlatList` exposes its own API to spin up an internal `RefreshControl` through the [`refreshing`](https://reactnative.dev/docs/flatlist#refreshing) and [`onRefresh`](https://reactnative.dev/docs/flatlist#onrefresh) properties which work fine
- Really curious why this only behaves poorly on `Expo` though, might dive deeper into it at some other point to peek a bit under the hood 
<details> …
> fix: expo refresh control and audio bugs

- package/native-package/src/optionalDependencies/FlatList.ts
- package/src/contexts/messagesContext/MessagesContext.tsx
- package/src/native.ts
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
> fix: add a log that complains for removal for mvcp package on RN version <0.72

- .github/workflows/check-pr.yml
- .github/workflows/docusaurus.yml
- .github/workflows/next-release.yml
- .github/workflows/sdk-size-metrics.yml
- docusaurus/docs/reactnative/basics/migrating-from-5.x-to-6.x.mdx
- package.json
- release/next.js
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
> chore: setup workflow and improve migration guide for v6 rc release

- examples/SampleApp/package.json
- examples/SampleApp/yarn.lock
- examples/TypeScriptMessaging/package.json
- examples/TypeScriptMessaging/yarn.lock
> fix: upgrade react native version in sample apps to 0.73.10

- package/src/components/Message/hooks/useProcessReactions.ts
> feat!: rc release v6

- package/src/components/Message/hooks/useProcessReactions.ts
- package/src/components/MessageMenu/MessageActionList.tsx
Add styling changes.
BREAKING CHANGE: Add styling changes for the MessageActionList component
> feat: styles changes for MessageActionList

- package/src/components/MessageMenu/MessageUserReactions.tsx
- release/next.js
- release/release.config.js
Style changes for the `MessageUserReactions` component.
BREAKING CHANGE: Introduce Style changes for the `MessageUserReactions` component.
> feat: styles changes for MessageUserReactions

- examples/SampleApp/ios/SampleApp.xcodeproj/project.pbxproj
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
> fix: remove macos deployment destination

- docusaurus/docs/reactnative/hooks/poll/use-poll-state-store.mdx
- docusaurus/docs/reactnative/hooks/poll/use-poll-state.mdx
- package/src/components/ChannelPreview/hooks/useLatestMessagePreview.ts
- package/src/components/Poll/Poll.tsx
- package/src/components/Poll/components/Button.tsx
- package/src/components/Poll/components/PollAnswersList.tsx
- package/src/components/Poll/components/PollOption.tsx
- package/src/components/Poll/components/PollResults/PollOptionFullResults.tsx
- package/src/components/Poll/components/PollResults/PollResultItem.tsx
- package/src/components/Poll/components/PollResults/PollResults.tsx
- package/src/components/Poll/hooks/usePollOptionVotesPagination.ts
- package/src/components/Poll/hooks/usePollState.ts
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
> feat: rename poll state selector props

- package/src/components/MessageInput/components/NativeAttachmentPicker.tsx
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
> fix: native image picker poll control

- package/src/components/ChannelPreview/hooks/useLatestMessagePreview.ts
Resolves [this Zendesk ticket](https://getstream.zendesk.com/agent/tickets/56665).
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
> fix: check for channel validity before consuming config

- examples/ExpoMessaging/types.ts
- examples/SampleApp/src/components/NewDirectMessagingSendButton.tsx
- examples/SampleApp/src/types.ts
- examples/TypeScriptMessaging/App.tsx
- package/src/types/types.ts
This PR adds support for custom member types to our SDK. It will be backported to V5 as well.
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
> feat: add support for membership customization

- examples/ExpoMessaging/yarn.lock
- examples/SampleApp/yarn.lock
- examples/TypeScriptMessaging/yarn.lock
- package/expo-package/yarn.lock
- package/native-package/yarn.lock
- package/package.json
- package/src/utils/utils.ts
- package/yarn.lock
Backport of [this PR](https://github.com/GetStream/stream-chat-react-native/pull/2794) for V6.
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
> feat: moderation v2 support

- examples/SampleApp/ios/Podfile.lock
- examples/SampleApp/package.json
- examples/SampleApp/yarn.lock
- examples/TypeScriptMessaging/ios/Podfile.lock
- examples/TypeScriptMessaging/yarn.lock
- package/package.json
- package/src/components/AttachmentPicker/AttachmentPicker.tsx
- package/src/components/ChannelList/Skeleton.tsx
- package/src/components/ImageGallery/ImageGallery.tsx
- package/yarn.lock
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
> fix: upgrade bottom sheet and fix reanimated errors in new arch

- package/src/components/Chat/hooks/useIsOnline.ts
Backport of [this PR](https://github.com/GetStream/stream-chat-react-native/pull/2807). All details are mentioned there.
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
> fix: channel.state break on going to background

- package/src/components/ImageGallery/components/ImageGalleryFooter.tsx
- package/src/components/ImageGallery/components/ImageGalleryHeader.tsx
> fix: image gallery header and footer safe area view

- package/CHANGELOG.md
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
> fix: dummy commit to trigger v6 release

- .github/workflows/check-pr.yml
- .github/workflows/next-release.yml
- .github/workflows/sample-distribution.yml
- .github/workflows/sdk-size-metrics.yml
- release/next.js
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
> fix: add V5 branch configuration

- package/src/components/MessageList/hooks/useLastReadData.ts
- package/src/components/MessageList/hooks/useMessageList.ts
- package/src/components/MessageList/utils/getReadStates.ts
> fix: read state for messages

- package/src/components/MessageList/MessageList.tsx
- package/src/components/Thread/__tests__/__snapshots__/Thread.test.js.snap
This solution works on older and newer devices, android 33 and older, and also on >0.73 and <0.73.
Images attached
RN >0.73 on all types of android device
RN <0.73 on all types of android devices
Fixes #2885
> fix: inverted unread indicator due to applied inverted styles

- examples/ExpoMessaging/package.json
- examples/ExpoMessaging/yarn.lock
- examples/SampleApp/ios/Podfile.lock
- examples/SampleApp/package.json
- examples/SampleApp/yarn.lock
- examples/TypeScriptMessaging/ios/Podfile.lock
- examples/TypeScriptMessaging/package.json
- examples/TypeScriptMessaging/yarn.lock
- package/src/store/SqliteClient.ts
- package/src/store/apis/getAppSettings.ts
- package/src/store/apis/getChannelMessages.ts
- package/src/store/apis/getLastSyncedAt.ts
- package/src/store/apis/getPendingTasks.ts
- package/src/store/apis/queries/selectChannels.ts
- package/src/store/apis/queries/selectMembersForChannels.ts
- package/src/store/apis/queries/selectMessagesForChannels.ts
- package/src/store/apis/queries/selectReactionsForMessages.ts
- package/src/store/apis/queries/selectReadsForChannels.ts
- package/src/store/apis/updatePollMessage.ts
- package/src/store/types.ts
The goal of the PR is to add compatibility for the latest version of op-sqlite. This fixes #2891 as a part of the change. This also includes TS issue fixes.
> fix: add latest version >11.2.6 compatibility for op-sqlite

- package/src/components/ChannelList/hooks/useCreateChannelsContext.ts
- package/src/components/ChannelPreview/hooks/useChannelPreviewData.ts
- package/src/components/Chat/hooks/handleEventToSyncDB.ts
This is a backport of [this PR](https://github.com/GetStream/stream-chat-react-native/pull/2901) to V5.
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
> fix: backport read status fix

- package/expo-package/yarn.lock
- package/native-package/src/optionalDependencies/Audio.ts
- package/native-package/src/optionalDependencies/Sound.tsx
- package/native-package/yarn.lock
Fixes [this Zendesk issue](https://getstream.zendesk.com/agent/tickets/60466).
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
> fix: ignore silent switch on sound as well

- package/src/components/Message/MessageSimple/utils/generateMarkdownText.test.ts
- package/src/components/Message/MessageSimple/utils/generateMarkdownText.ts
- package/src/components/Message/MessageSimple/utils/renderText.tsx
> feat: blockquote support on v5 branch

- package/src/components/MessageInput/components/AudioRecorder/AudioRecorder.tsx
- package/src/i18n/en.json
- package/src/i18n/es.json
- package/src/i18n/fr.json
- package/src/i18n/he.json
- package/src/i18n/hi.json
- package/src/i18n/it.json
- package/src/i18n/ja.json
- package/src/i18n/ko.json
- package/src/i18n/nl.json
- package/src/i18n/pt-br.json
- package/src/i18n/ru.json
- package/src/i18n/tr.json
> fix: add translations for slide to cancel text in async audio

- package/src/components/MessageMenu/MessageMenu.tsx
- package/src/contexts/themeContext/utils/theme.ts
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
> fix: change height of bottom sheet in message menu using theme

- examples/SampleApp/src/hooks/useChatClient.ts
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
> fix: duplicate android pns

- examples/SampleApp/src/ChatUsers.ts
- examples/SampleApp/src/hooks/useChatClient.ts
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
> fix: pn integration changes for new pn update

- examples/ExpoMessaging/yarn.lock
- examples/SampleApp/yarn.lock
- examples/TypeScriptMessaging/yarn.lock
- package/package.json
- package/yarn.lock
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
> fix: bump stream-chat for user agent hotfix

- .github/workflows/sample-distribution.yml
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
> fix: bump macos version to 15

- package/src/store/apis/queries/selectMessagesForChannels.ts
Sadly, I introduced an unfortunate bug with [this fix](https://github.com/GetStream/stream-chat-react-native/pull/2996) to how the messages are sorted. Since the order changed (to reflect what we expect from the server) the limit to 200 messages from the offline DB was causing any value past that to "move" the window of available messages.
In other words, if we had 250 messages stored for a single `channel` we would get the oldest 200 while the latest 50 would simply not be loaded (until the first query is run, after which everything would reconcile).
To fix this, we run the `SELECT` query still with `DESC` ordering and only order properly towards the end.
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td> …
> fix: db sorting past 200 messages

- examples/ExpoMessaging/yarn.lock
- examples/SampleApp/android/app/src/main/AndroidManifest.xml
- examples/SampleApp/ios/Podfile.lock
- examples/SampleApp/package.json
- examples/SampleApp/yarn.lock
- examples/TypeScriptMessaging/ios/Podfile.lock
- examples/TypeScriptMessaging/yarn.lock
- package/expo-package/yarn.lock
- package/native-package/yarn.lock
- package/package.json
- package/yarn.lock
> chore: use rimraf to clear the dist and add cameraroll android permissions on sample app

- package/expo-package/yarn.lock
- package/native-package/yarn.lock
- package/src/components/Channel/Channel.tsx
- package/src/components/Thread/components/ThreadFooterComponent.tsx
This PR fixes 2 bugs:
- The optimistic update of the `Thread` implementation would cause a race condition sometimes where messages would be sent twice, but with the same key (once for the optimistic update and once for the `thread.state` upsertion); it should be resolved with this fix
- The `FlatList` footer component was not updating the `replyCount` in real time within the `ThreadList`, which should also be fixed
Linear issues: 
- https://linear.app/stream/issue/RN-169/sending-messages-in-a-threadlist-thread-causes-key-errors
- https://linear.app/stream/issue/RN-170/threads-from-threadlist-do-not-update-their-reply-count-in-realtime
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody> …
> fix: thread list variety bugs

- examples/SampleApp/yarn.lock
- package/expo-package/yarn.lock
- package/native-package/yarn.lock
- package/src/contexts/channelsStateContext/useChannelState.ts
A backport of [this PR](https://github.com/GetStream/stream-chat-react-native/pull/3068) to V6.
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
> fix: thread messages updates

- package/src/components/MessageInput/components/AudioRecorder/AudioRecordingButton.tsx
Context - https://getstream.slack.com/archives/C07AV3YEMK7/p1746460020501879
> fix: async audio button ui spacing with other buttons

- package/src/components/Attachment/FileAttachmentGroup.tsx
- package/src/components/Message/MessageSimple/MessageSimple.tsx
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
> fix: swipe to reply remounting

- package/src/components/Chat/hooks/useAppSettings.ts
Should close [this Zendesk ticket](https://getstream.zendesk.com/agent/tickets/64536).
We recently discovered that we fetch the Stream app settings way too aggressively in certain scenarios within the SDK (especially with offline support disabled). An attempt to fetch them would happen if:
- The connectivity status of the user changed (**even when** going offline, resulting in timeouts)
- When putting the app in background mode (because of connectivity changes, specifically if `closeConnectionOnBackground` is `true`)
- When coming back from background mode
- Every time the `isOnline` value changes basically regardless
Additionally, it was entirely possible to trigger multiple requests towards the `/app` endpoint at the same time and they would all fire (i.e if we rerendered the `Chat` …
> fix: guard against fetching appsettings many times

- package/expo-package/yarn.lock
- package/native-package/yarn.lock
- package/src/index.ts
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
> fix: expose abstract offline db implementation

- package/src/components/Chat/Chat.tsx
- package/src/components/ImageGallery/ImageGallery.tsx
- package/src/components/MessageList/MessageList.tsx
- package/src/components/Thread/__tests__/__snapshots__/Thread.test.js.snap
- package/src/contexts/overlayContext/OverlayProvider.tsx
This PR focuses on improving our `ImageGallery` performance which was pretty bad on lower end devices. It can be optimized further, but it's better if those changes happen gradually.
TL;DR:
- Since we want to eventually remove `OverlayProvider` and all of the noise it's causing, we will start by removing all references towards it in the SDK
- The `scrollEnabled` behaviour of our `MessageList` has been removed as it is no longer needed (due to how the overlays work exactly with the newer SDK versions); this was causing heavy layout recalculations of the entire DOM subtree for no good reason due to the usage of `OverlayContext`
- We no longer use `OverlayContext` within the `Chat` component just to grab the theme, rather we consume the `Theme` from the top level provider and use it that way …
> perf: image gallery rendering improvements

- package/src/components/MessageInput/SendButton.tsx
- package/src/components/MessageInput/__tests__/AudioAttachmentUploadPreview.test.js
- package/src/components/Poll/CreatePollContent.tsx
- package/src/contexts/messageInputContext/MessageInputContext.tsx
- package/src/utils/setupCommandUIMiddleware.ts
LLC PR: https://github.com/GetStream/stream-chat-js/pull/1560
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
> fix: poll creation and optimistic updates

- .github/workflows/sample-distribution.yml
- examples/SampleApp/fastlane/Fastfile
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
> fix: sample app crash on start

- package/src/components/MessageList/MessageList.tsx
Port https://github.com/GetStream/stream-chat-react-native/pull/3145 to V7
> fix: unread underlay display for own messages

- package/src/contexts/index.ts
- package/src/contexts/messageInputContext/MessageInputContext.tsx
> fix: add export for message composer api context

- package/src/utils/setupCommandUIMiddlewares.ts
> fix: duplicate command injection issue when commands added in message

- examples/ExpoMessaging/yarn.lock
- examples/SampleApp/yarn.lock
- examples/TypeScriptMessaging/yarn.lock
- package/package.json
- package/yarn.lock
Fixes https://github.com/GetStream/stream-chat-react-native/issues/3180
> fix: update the stream-chat version to 9.13.0

- package/src/components/Message/Message.tsx
- package/src/components/Message/MessageSimple/ReactionList/ReactionListBottom.tsx
- package/src/components/MessageMenu/MessageUserReactionsItem.tsx
- package/src/components/MessageMenu/ReactionButton.tsx
- package/src/components/MessageMenu/__tests__/ReactionButton.test.tsx
- package/src/contexts/themeContext/utils/theme.ts
Fixes the regression with default theme colors not taking dark mode into account for different properties.
> fix: regression in theme default value colors
