GetStream/stream-chat-react-native

CHANGELOG.md
README.md
expo-package/yarn.lock
native-package/package.json
native-package/src/index.js
native-package/yarn.lock
yarn.lock

React native introduced autolinking behaviour, so packages don't need to be linked manually. And RN does this using cocoapod. All the dependencies are auto-linked according to their pod configuration. But for this to work, we need to have cocoapods configured for our project. So that, when consumer installs our SDK, then pods of dependencies of our sdk will also be installed on his end when he does `pod install`. But our project is kind of pure js project ... we don't really have any ios/android directories. 
1. So either we can make it native project (with ios/android directories). But I don't think it makes sense, since we don't really have any native code.
2. Other option is to take following dependencies out of our project and ask consumer to install it on their end (on application …

Making sdk compatible with RN 0.60

---

src/components/MessageSimple/MessageContent.js
src/components/MessageSimple/MessageTextContainer.js
src/components/docs/MessageSimple.md
src/styles/theme.js
src/utils.js

CRNS-36: Adding custom style support for markdown

---

README.md
src/components/Chat.js
src/components/DateSeparator.js
src/components/MessageInput.js
src/components/MessageSimple/MessageAvatar.js
src/components/MessageSimple/MessageContent.js
src/components/MessageSimple/MessageReplies.js
src/components/MessageSimple/MessageStatus.js
src/components/MessageSimple/MessageTextContainer.js
src/components/MessageSimple/index.js
src/index.js
types/index.d.ts

https://github.com/GetStream/stream-chat-react-native/issues/108

CRNS-54: Typescript and prop types for message related inner components

---

src/components/ReactionPicker.js

- [] Code changes are tested (add some information if not applicable)
First character of a user ID is displayed above emojis in reactions. The code reads as though this should be the initials of the users name.
I have not tested this as it is a small change, and the user object should contain the key "name", as it appears in other areas of the application

NOTICKET: Update ReactionPicker to send username instead of ID

---

src/components/MessageSimple/index.js
types/index.d.ts

I don't see any tests in the current codebase. Happy to add something if desired!
It would be convenient if when we configure the `<MessageSimple` component that we could swap out the internal components it uses without having to completely re-implement or fork MessageSimple!

[Feature] MessageSimple: Add Formal Override Points to provide Alternate Components

---

src/components/MessageSimple/MessageContent.js
src/components/MessageSimple/index.js
src/components/ReactionPicker.js
types/index.d.ts

- adding in a boolean values to MessageSimple to enable hiding reaction count/owner in the ReactionPicker

adding in a boolean values to MessageSimple to enable hiding reaction count/owner in the ReactionPicker

---

src/components/ChannelInner.js
src/components/Message.js
src/components/MessageList.js
types/index.d.ts

Fixes - https://github.com/GetStream/stream-chat-react-native/issues/149
- Update the reactions (add/remove) in UI without waiting for api calls.
- In case of failure, reset the added/removed reactions.
- Lifting `handleReaction` function up from `Message` (HOC) to `Channel` component.
- Lifting network status (state variable `online`) from `MessageList` to `Channel` component
- Updating channel state before calling sendReaction/removeReaction api.
- If promise gets rejected or api fails, then we reset the state update.
**NOTE** This PR is dependent on changes of following PR in js client - https://github.com/GetStream/stream-chat-js/pull/280

Optimistic reaction updates to UI

---

src/components/KeyboardCompatibleView.js
src/components/MessageNotification.js

We recently started seeing warnings in the debug console that Animated values need to specify true/false for useNativeDriver. Added false calls for the non-native supported height properties and added true for the native supported opacity properties.
https://reactnative.dev/blog/2017/02/14/using-native-driver-for-animated#caveats

Add useNativeDriver to animations to prevent console warnings

---

src/components/ChannelList.js
types/index.d.ts

This PR fixes #187 by handling the channel.hidden event. Unfortunately I can't test this right now but all I did is take the same method from the channel.deleted event so it should works.
I also fixed the documentation link in PropTypes.

In teach/handle channel hidden

---

src/components/MessageInput.js

Vish, we're running into a race conditions issue where the `img` pulled off state in `_uploadImage` is undefined on the first pass through the code for gif uploads. Since the state is not yet set, an infinite loading state is triggered. The upload works properly after we click the preview icon to retry the upload, as the state has had time to update.
https://github.com/GetStream/stream-chat-react-native/blob/32953a3efce28f4927739d7835ed2b467500e4bb/src/components/MessageInput.js#L561

Add async/await to uploadNewImage function in MessageInput

---

src/utils/index.js

I noticed that occasionally the internal og scraper was adding some whitespace to the image urls, causing them not to show. so figured they should trim them so that they render correctly

Trim whitespace from image url in cards

---

src/components/ChannelInner.js

When a socket connection is lost and recovered the channel.state.threads do not return in the initial reconnection. This resets thread messages to and empty array when you, for instance, background an app on Android for 30sec then pull it back up while still in the thread screen. If instead the fallback is the previous state of threadMessages, which defaults to an empty array and thus covers the current fallback, the messages are maintained through this recovery cycle.

handleEvent fallback to state.threadMessages

---

src/components/ChannelList.js
src/components/ChannelListMessenger.js
src/components/MessageList.js
types/index.d.ts

We already have additionalFlatList prop on ChannelList and MessageList which allows user to add any custom prop to inner flatlist. But this can not be used to set ref on flatlist, since it will override ref set by MessageList component, disrupting the original behavior. So instead `setFlatListRef` can be used instead to get access to ref.
Issue - https://github.com/GetStream/stream-chat-react-native/issues/201

Adding setFlatListRef prop to ChannelList and MessageList

---

docs/cookbook.md
src/components/Attachment.js
src/components/Card.js
src/components/FileAttachment.js
src/components/Gallery.js
src/components/MessageSimple/MessageContent.js
src/components/MessageSimple/index.js
types/index.d.ts

- Adding support for prop `additionalTouchableProps` in `MessageSimple` to allow adding additional prop to inner TouchableOpacity components
- Same (additionalTouchableProps) prop gets forwarded to all inner components which has some touchable feedback attached such as Gallery, FileAttachment, etc
fixes https://github.com/GetStream/stream-chat-react-native/issues/186

Bug fixes with message component

---

src/components/Gallery.js

Due to Stream Chat not having "save image" functionality, that [functionality was disabled](https://github.com/GetStream/stream-chat-react-native/blob/master/src/components/Gallery.js#L132), but only for image galleries with one image. So, i'm also disabling for multi image gallery.

Disable "Save Image" functionality for multi-image Gallery

---

package.json
src/components/ChannelList.js
src/components/ChannelListFooterLoadingIndicator.js
src/components/ChannelListHeaderErrorIndicator.js
src/components/ChannelListHeaderNetworkDownIndicator.js
src/components/ChannelListMessenger.js
src/components/LoadingErrorIndicator.js
src/components/Spinner.js
src/components/index.js
src/i18n/en.json
src/i18n/fr.json
src/i18n/hi.json
src/i18n/it.json
src/i18n/nl.json
src/i18n/ru.json
src/i18n/tr.json
src/styles/theme.js
types/index.d.ts

```js
setStateAsync = (newState) => {
return new Promise((resolve) => {
this.setState(newState, resolve);
});
};
```

Better error handling in ChannelList

---

docs/cookbook.md
src/components/ChannelInner.js
src/components/Chat.js
src/components/KeyboardCompatibleView.js
src/components/MessageInput.js
types/index.d.ts

setting KeyboardCompatibleView initialHeight again when the layoutHeight is not equal to the new height when the keyboard is closed and setting the initial channelHeight state to a number as the types for Animated suggest removing some unused or unnecessary things

KeyboardCompatibleView initialHeight setting with keyboard closed and new onLayout height

---

src/components/MessageInput.js

change action sheet onPress timeout from 10 ms to 201 because the animated timing of the actionsheet is 200ms leading to an animation firing after the image picker appears and causes the image picker render to be overridden

message input picker bug

---

types/index.d.ts

`MessageInput` component handles optional `additionalTextInputProps`, but it's not present on `MessgeInputProps`. So, I've added the type.

Add additionalTextInputProps? to MessageInputProps

---

src/components/KeyboardCompatibleView.js

With react-native 0.63, came a runtime check on animated values - which disallowed anything other than pure numbers.

Fixing Animated values on KeyboardCompatibleView

---

src/components/Attachment/Gallery.js
src/components/MessageInput/MessageInput.js
src/components/MessageInput/__tests__/__snapshots__/MessageInput.test.js.snap
src/components/Thread/__tests__/__snapshots__/Thread.test.js.snap

- CRNS-151: removing flex from view container to allow button to be clickable on android and ios and making android not crash from MessageInput

CRNS-151: removing flex from view container to allow button to be clickable on android and ios and making android not crash from MessageInput

---

package.json
src/components/Attachment/__tests__/Attachment.test.js
src/components/Channel/Channel.js
src/components/ChannelPreview/__tests__/ChannelPreviewMessenger.test.js
src/components/MessageList/MessageList.js
src/components/Thread/__tests__/Thread.test.js
src/mock-builders/generator/attachment.js
src/mock-builders/generator/channel.js
src/mock-builders/generator/message.js
src/mock-builders/generator/user.js
src/utils/__tests__/Streami18n.test.js
yarn.lock

Older Expo version have issues with uuid v8+ so we reverted this and used the old integrations instead.

revert uuid from v8 to v3

---

src/components/Channel/Channel.tsx

Related to - https://github.com/GetStream/stream-chat-react-native/issues/494
v2.2.1 fixed the issue on reloading the ChannelList in case of connection.changed event. Although it skipped following two cases
- If user is on Channel screen, the updated messages will reflect on ChannelList, but not on Channel component. This is because there no way for Channel component to know when ChannelList has refreshed.
- If app has standalone Channel component.
These two scenarios have been covered here.

Reload channel upon connection.changed

---

src/components/MessageList/MessageList.tsx
src/components/MessageOverlay/MessageOverlay.tsx
src/contexts/themeContext/ThemeContext.tsx

This PR build's on @vishalnarkhede previous theme improvement to further reduce the number of merge's / lodash calls made. I introduced a new prop to ThemeProvider that instead of performing a merge uses the Theme directly, for messages and overlay this allows for reuse of the current theme. Essentially all theme merges should now only happen once or when a change occurs instead.

Reuse expensive merge in theme

---

src/components/MessageOverlay/MessageOverlay.tsx
src/components/Thread/Thread.tsx
src/contexts/overlayContext/OverlayProvider.tsx

Customizing reactions got thrown off by some changes, it would end up always the default. This fixes that issue.
Also Footer correction in thread after prop change.

change ordering of spread to account for undefined in props

---

src/components/Channel/Channel.tsx
src/components/ChannelPreview/ChannelPreview.tsx
src/components/MessageList/MessageList.tsx

- We used to allow un-initialized `channel` as prop on Channel component in v2. Just making sure in this PR, that we still do.
- `ChannelPreview` breaks if you send message on channel with no messages. Fixed that issue.

CRNS-283: Allow uninitialized channel on Channel component

---

src/components/Channel/Channel.tsx
src/components/Channel/hooks/useCreateInputMessageInputContext.ts
src/components/Channel/hooks/useCreateMessagesContext.ts
src/components/Channel/hooks/useCreatePaginatedMessageListContext.ts

- All the internal methods such as `sendMessage`, `updateMessage`, `loadMore` carry reference to old channel, after channel switch. To avoid this, add channelId as extra check on memoization of messagesContext and

Ensure context update, when channel is changed

---

src/components/AttachmentPicker/AttachmentPicker.tsx

Fixes images not loading in picker when switching from keyboard on first load.

fix image picker not loading when swapping from keyboard

---

src/components/MessageOverlay/OverlayReactionList.tsx
src/contexts/themeContext/utils/theme.ts

Adds a default size to Icon's on the overlay reaction list

CRNS-287 - add reaction size to overlay reaction list

---

src/components/MessageInput/MessageInput.tsx
src/contexts/messageInputContext/MessageInputContext.tsx
src/contexts/messageInputContext/hooks/useCreateMessageInputContext.ts

Image picker close function was changed resulting in a change being needed elsewhere to maintain functionality

FIX - Close image picker on unmount

---

src/components/ChannelList/ChannelList.tsx
src/components/ChannelList/hooks/listeners/useChannelVisible.ts

- Add `onChannelVisible` prop to `ChannelList` component
- add `useChannelVisible` hook which uses `onChannelVisible` but defaults to adding the channel to the channel list state.

CRNS-279: Handle channel.visible event

---

src/utils/Streami18n.ts

Streami18n accepts incomplete translations based on the usage, i.e. missing keys are dealt with. Therefore the types should be partial. It also appears in the current docs that translations should be merged when `translationsForLanguage` is used in the options; but currently that key replaces translations for a given language it appears, this remedies that.

adjust Streami18n

---

src/components/Message/Message.tsx
src/contexts/messagesContext/MessagesContext.tsx

Without access to `dismissOverlay`, user won't be able to dismiss the overlay if he wants to add some custom action. This should be probably provided in other props as well such as editMessage, deleteMessage. Have added a story to backlog for that - https://stream-io.atlassian.net/browse/CRNS-356

Provide dismissOverlay function as param to messageActions prop

---

src/components/KeyboardCompatibleView/KeyboardCompatibleView.tsx

The keyboard calculations are incorrect when the header on android is translucent, this accounts for that issue.

Fix Android translucent header keyboard height issue

---

src/contexts/messageInputContext/MessageInputContext.tsx

Images from the file picker need to be treated as files for the time being until we alter the single use scenario currently in place

CRNS-325: Treat images from file picker as files

---

package/src/components/ImageGallery/ImageGallery.tsx

There is an edge case that is not 100% repeatable where notched iOS phones cause an infinite loop between the reanimated and main JS thread. This tries to fix this issue by preventing recalculation of snap points.

fix: Fix infinite loop in bottom sheet or image gallery on notched iOS phones

---

docusaurus/docs/reactnative/basics/hello_stream_chat.mdx
docusaurus/docs/reactnative/basics/stream_chat_with_navigation.mdx
docusaurus/docs/reactnative/basics/troubleshooting.mdx
docusaurus/docs/reactnative/common-content/core-components/channel/props/thread_list.mdx
docusaurus/docs/reactnative/core-components/channel.mdx
docusaurus/docs/reactnative/ui-components/thread.mdx
examples/ExpoMessaging/App.js
examples/NativeMessaging/App.js
examples/SampleApp/src/screens/ThreadScreen.tsx
examples/TypeScriptMessaging/App.tsx
package/package.json
package/src/components/Channel/Channel.tsx
package/src/components/ChannelList/hooks/usePaginatedChannels.ts
package/src/components/Message/MessageSimple/MessageReplies.tsx
package/src/components/Thread/components/ThreadFooterComponent.tsx
package/src/contexts/channelsStateContext/ChannelsStateContext.tsx
package/src/contexts/channelsStateContext/useActiveChannels.ts
package/src/contexts/channelsStateContext/useChannelState.ts
package/src/contexts/overlayContext/OverlayProvider.tsx
package/yarn.lock

This PR is meant to fix the concurrency problems we've been having with our Channel & ChannelList components.
It moves the basics of our Channel state to a parent level in order to have it shared between multiple instances of the same Channel (i.e. when you have a channel and a thread in the navigation stack).
Also, uses the new parameter from our js client to prevent initializing active channels when refreshing the channel list (happens on reconnect).
Blocked by https://github.com/GetStream/stream-chat-js/pull/740
We need to update the stream-chat-js version on our sample apps before merging this PR.
PS: This PR adds a breaking change (now channel components rendering threads should add the threadList prop when the thread is active). Also, the new parameter from stream-chat-js will make …

fix: Channel concurrency fixes

---

docusaurus/docs/reactnative/basics/hello_stream_chat.mdx

docs: Fixing the typos in the hello_steam_chat.mdx file.
Typos:
- https://getstream.io/chat/docs/sdk/reactnative/basics/hello_stream_chat/ Line number 2. Two times "need".
- https://getstream.io/chat/docs/sdk/reactnative/basics/hello_stream_chat/
"To connect `a user a` the connectUser function should be called and provided with the user object and user_token. Connecting a user could be done in the login flow or elsewhere in the application after the client is instantiated". The issue is marked inside ``.

docs: fix in hello_stream_chat.mdx

---

package/package.json
package/src/components/Chat/hooks/useIsOnline.ts
package/src/hooks/useAppStateListener.ts
package/yarn.lock

React Native 0.65 deprecated a support for `AppState.removeEventListener()`. This involves the internal subscription model changes which is affecting our `useAppStateListener` in which we tried to keep away from `useCallback()` hook. Exact reason why removeEventListener fails to remove the listener is still a bit of a mystery, causing exponential increase in these listeners. But replacing `removeEventLister` with `subscription.remove()` seems to do the job.

fix: fixed AppState subscription logic to support RN 0.65

---

package/src/components/KeyboardCompatibleView/KeyboardCompatibleView.tsx

fix: fixing deprecated warning around AppState for RN 0.65 compatibility

---

.github/workflows/check-pr.yml
.github/workflows/e2e-native-android.yml
.github/workflows/e2e-native-ios.yml
.github/workflows/e2e-sample-android.yml
.github/workflows/e2e-sample-ios.yml
.github/workflows/lint-pr-title.yml

This intends to make it so our checks run for PRs targeting branches named by semver versions. For example `v4.0.0` should be valid.
I've verified the syntax should work with the [GitHub docs](https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#filter-pattern-cheat-sheet)

build: Run checks on semver-named branches

---

package/src/components/ChannelList/hooks/usePaginatedChannels.ts

With current logic, we used to set `offset` for next pagination request after the completion of previous request. But in case a length of `channels` changes between two pagination calls (new channel gets added/remove to list from event handlers), then the offset for next pagination api call will be wrong. This results in following error on channellist:
```
ERROR  Warning: Encountered two children with the same key, `messaging:channel-ex-example-apps-8`. Keys should be unique so that components maintain their identity across updates.
```
We should decide the value of offset right before making the pagination api call, using length of channel list.

fix: fixed offset-limit logic for channel list pagination

---

package/src/components/Channel/Channel.tsx

This PR is meant to fix the problem where, after throttling the state updates inside of channel, it ended up kind of debouncing it instead because the leading parameter was set to false. Setting it to true should immediately copy the channel state and then start throttling

fix(Channel): Copy channel state on leading edge of throttling

---

docusaurus/docs/reactnative/basics/troubleshooting.mdx
examples/NativeMessaging/android/app/src/main/AndroidManifest.xml
examples/SampleApp/android/app/src/main/AndroidManifest.xml
examples/TypeScriptMessaging/android/app/src/main/AndroidManifest.xml

This PR introduces support and adds documentation for the issue: No support for opening the external links on applications having targetSdkVersion >=30 on android. This is also done for our example applications.
Reference JIRA issue - https://stream-io.atlassian.net/browse/CRNS-441

fix: support external link for targetSdkVersion >=30

---

package/src/components/Attachment/Gallery.tsx
package/src/utils/__tests__/utils.test.js
package/src/utils/utils.ts

https://stream-io.atlassian.net/browse/CRNS-288
For memoization of Gallery component, we compare the entire image_url or thumb_url. But everytime you update the message, signature url param on these urls change. This is to make sure the url will remain valid for the maximum amount of time after it gets queried. So basically our memoization doesn't work on message updates. And so we should compare the base urls instead of comparing entire url
```
https://us-east.stream-io-cdn.com/62344/images/69c62680-45ba-4c6c-af49-66f3acee39cf.C8B8DF8D-A326-44A6-8030-C2B1C61116A5.jpg?Key-Pair-Id=APKAIHG36VEWPDULE23Q&Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly91cy1lYXN0LnN0cmVhbS1pby1jZG4uY29tLzYyMzQ0L2ltYWdlcy82OWM2MjY4MC00NWJhLTRjNmMtYWY0OS02NmYzYWNlZTM5Y2YuQzhCOERGOEQtQTMyNi00NEE2LTgwMzAtQzJCM …
```

fix: avoid unnecessary gallery image re-rendering upon message update

---

package/src/components/ChannelList/ChannelListLoadingIndicator.tsx
package/src/components/ChannelPreview/ChannelPreviewMessage.tsx
package/src/contexts/themeContext/utils/theme.ts

Currently, there is a bug where we cannot customize the preview message color. The parent text node consumes the message from context so we can apply it to style. But the child text node doesn't consume anything beyond the base styles which enforces the grey color. As seen in develop branch here
https://github.com/GetStream/stream-chat-react-native/blob/develop/package/src/components/ChannelPreview/ChannelPreviewMessage.tsx#L49-#L60
As a consumer, if I want to update the preview message color to a color other than the theme color `grey` I cannot. This solves that issue
ChannelListLoadingIndicator background can be updated based on` white_snow`, however if we want the background to be different from the color that is `white_snow` this is not currently possible. In this PR this is resolved …

fix: preview message & channellist customization

---

docusaurus/docs/reactnative/basics/getting_started.mdx

To replace a broken link in our documentation
N/A
N/A
N/A
-  ~New code is covered by tests~
- ~Screenshots added for visual changes~

docs: Fix broken link to reanimated docs

---

package/src/components/ChannelList/hooks/usePaginatedChannels.ts
package/src/components/Chat/hooks/useIsOnline.ts
package/src/hooks/useIsMountedRef.ts
package/src/hooks/useStreami18n.ts

Fixes https://github.com/GetStream/stream-chat-react-native/issues/693
- Introduced a hook - `useIsMountedRef`, which can be used to keep track of mount status of hook/component.
- Updated `useIsOnline`, `useStreami18n` and `usePaginatedChannels` to use mounted status and prevent setState calls in unmounted state.
- Updated useIsOnline component to use `unsubscribe` methods returned by `client.on(...)` method, instead of using `client.off()` to unsubscribe event listener
NA

fix: fixed react warnings - Can not perform a React state update on an unmounted component [CRNS-444]

---

package/src/components/Message/MessageSimple/utils/renderText.tsx

Fix the issue: https://github.com/GetStream/stream-chat-react-native/issues/924
Force the markdown component to update when theme changes.
NA
- Open the example app on simulator
- Open any channel
- Press `cmd + shift + A` to toggle the dark/light mode.
Notice that text color doesn't update before this change.

fix: update message text when theme changes [CRNS-467]

---

examples/SampleApp/.eslintrc.json
examples/SampleApp/src/components/ChatScreenHeader.tsx
examples/SampleApp/src/hooks/useChatClient.ts
examples/SampleApp/src/icons/Close.tsx
examples/SampleApp/src/icons/RightArrow.tsx
examples/SampleApp/src/screens/NewDirectMessagingScreen.tsx

Running the `yarn lint` command produces around 28-30 warnings across the SDK and the sample app. Most of them are related to unused vars. This PR intends to fix them all. 
The solution for no-used-vars are as follows:
- Using a `_` character and prepend it to the parameter. This would simply let the linter avoid checks on such parameters.
- Adding an `args` argument to the `no-unused-vars` and setting it to `none`. This avoids no-unused-vars checks from the parameters of the functions.
I personally preferred the 2nd solution because a function parameter could be used or unused and checking them or not doesn't make much difference. Moreover, usage 0f `_` might confuse others.
I will be happy to get suggestions on this and also feedback if the solution looks fine. 
None
<details> …

Fix: lint warnings in the SDK and example apps

---

docusaurus/docs/reactnative/common-content/core-components/overlay-provider/props/message_text_number_of_lines.mdx
docusaurus/docs/reactnative/core-components/overlay_provider.mdx
package/src/components/Message/MessageSimple/MessageTextContainer.tsx
package/src/components/Message/MessageSimple/utils/renderText.tsx
package/src/components/MessageOverlay/MessageOverlay.tsx
package/src/contexts/overlayContext/OverlayContext.tsx
package/src/contexts/overlayContext/OverlayProvider.tsx

This PR introduces the fix for the long message scroll problem due to message overlay text and the related ScrollView problem.
Previously, opening the message overlay on long-press loaded a Scrollview which generated a warning/error of Virtualized list due to the presence of Reaction list within the view. To solve this the long text size is truncated and the underlying Scrollview is removed.
I have introduced a prop `messageTextNumberOfLines` to solve the issue which gives users flexibility to change the prop value later and render the number of lines according to their own purpose/use-case. By default, the value is 5.
Reference - https://stream-io.atlassian.net/browse/CRNS-278
<details>
<table>
<thead>
<tr><td>Before</td><td>After</td></tr>
</thead> …

Fix: remove long message text and scrollview from message overlay [CRNS - 278]

---

package/src/components/Channel/Channel.tsx
package/src/components/Channel/__tests__/Channel.test.js

Fixing the issue - https://github.com/GetStream/stream-chat-react-native/issues/930
- Add try-catch block around access to channel config, to avoid error.
- Add event listener for `channel.deleted` event on channel.
- Render `null` if channel is deleted in realtime.
- Replace event listener cleanups (`client.off` or `channel.off`) with `unsubscribe` methods provided by js client.
N.A
- Open some example app
- Open any channel
- Delete the channel on backend side
- Notice the error on screen as described in the gh issue

fix: handling the errors when channel which is open gets deleted [CRNS-468]

---

package/src/components/ChannelList/Skeleton.tsx
package/src/contexts/themeContext/utils/theme.ts

- Add customisability to background color for channel list loading indicator (skeleton).
- Will close the ticket - https://getstream.zendesk.com/agent/filters/360143141753
Technically you can still use `white_snow` theme color to change this color, but white_snow is used across the SDK and will affect plenty of components. So better to give explicit customization to change this color.
- Added a new theme key to override mask color for skeleton - `channelListSkeleton.maskFillColor`
Following table displays a customizable theme in channel list loading indicator:
```tsx
const theme = {
channelListMessenger: {
flatList: {
backgroundColor: 'yellow',
},
},
channelListLoadingIndicator: {
container: {
backgroundColor: 'blue',
},
},
channelListSkeleton: {
background: {
backgroundColor: 'red',
}, …
```

feat: added support for `channelListSkeleton.maskFillColor` theme property [CRNS-471]

---

examples/SampleApp/android/app/build.gradle
examples/TypeScriptMessaging/android/app/build.gradle

This pulls inn the changes from @khushal87 to fix fresco in the sample apps that the e2e tests use.
This is merged to v4.0.0, but not to develop. This branch has cherry-picked the commits so we can have them in develop as well.
(See for example that checks on #965 breaks cause of this)

build: Android fresco version bump

---

package/src/components/ChannelList/Skeleton.tsx
package/src/contexts/themeContext/utils/theme.ts

- Add customisability to background color for channel list loading indicator (skeleton).
- Will close the ticket - https://getstream.zendesk.com/agent/filters/360143141753
Technically you can still use `white_snow` theme color to change this color, but white_snow is used across the SDK and will affect plenty of components. So better to give explicit customization to change this color.
- Added a new theme key to override mask color for skeleton - `channelListSkeleton.maskFillColor`
Following table displays a customizable theme in channel list loading indicator:
```tsx
const theme = {
channelListMessenger: {
flatList: {
backgroundColor: 'yellow',
},
},
channelListLoadingIndicator: {
container: {
backgroundColor: 'blue',
},
},
channelListSkeleton: {
background: {
backgroundColor: 'red',
}, …
```

feat: added support for channelListSkeleton.maskFillColor theme property [CRNS-471]

---

package/src/components/Channel/Channel.tsx
package/src/components/Message/hooks/useMessageActions.tsx
package/src/hooks/useNetworkState.tsx

This checks network state before doing message actions without involving StreamCache, as not all customers will use StreamCache at all - our current implementation will give an error if there hasn't been set up a StreamCache instance
I've set up a simple hook using NetInfo to check network state, and expose a boolean value based on that.
N/A
Remove cache from the SampleApp, see that it won't give an error for missing StreamCache instance
- [-] PR targets the `develop` branch
- [-] New code is covered by tests
- [-] Screenshots added for visual changes
- [-] Documentation is updated

fix: Check network state separately from cache [CRNS-457]

---

examples/SampleApp/App.tsx
examples/SampleApp/src/hooks/usePaginatedPinnedMessages.ts
examples/SampleApp/src/hooks/usePaginatedSearchedMessages.ts
examples/SampleApp/yarn.lock
package/src/StreamCache.test.js
package/src/StreamCache/index.ts
package/src/StreamMediaCache.ts
package/src/components/ChannelList/hooks/usePaginatedChannels.ts

If the content of the offline cache is corrupt/incomplete/wrong, currently the rehydration of the cache will break, and an unhandled exception will be logged over and over in the console.
This catches these errors, and clears the cache if that were to happen.
Wrapping the rehydration in a try/catch, to give some information to the developer through the console, and clear cache when an error is caught.
None
Arbitrarily add a postfix or prefix to cache keys after the cache has been synced (so not on first build of the app), which should throw an error. Then apply these changes and do the same, which should give a warning, and then clear the cache, followed by the error disappearing.
- [-] PR targets the `develop` branch
- [-] Screenshots added for visual changes
- [-] Documentation is …

fix: Recover by clearing cache if cache is corrupt [CRNS-457]

---

package/src/components/Message/MessageSimple/utils/renderText.tsx

Our markdown custom rules use `React.createElement`, but I don't think that's necessary for us, so this PR changes it to use JSX instead. :) Happy to be convinced otherwise, though.
- [-] New code is covered by tests
- [-] Screenshots added for visual changes
- [-] Documentation is updated

refactor: Use JSX rather than React.createElement

---

package/src/components/Message/MessageSimple/utils/renderText.tsx

Currently, any ordered list in a message will have numbers reset to start from 1, but for consistency, this PR introduces a new default to start lists with the first number of the list, assigning incremental numbers from there.
I've taken the list rule from [react-native-markdown-package](https://github.com/andangrd/react-native-markdown-package), but simplified it a bit on top of using JSX rather than `React.createElement`.
I've only included screenshots from the iOS emulator, but this renders the same on either OS
<details>
<summary>Screenshots</summary>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>       
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
Send a message like this:
```
4. Four
5. Five
6. Six
```
The message should render with 4, …

feat: Default to not renumbering lists

---

package/src/components/MessageInput/CooldownTimer.tsx
package/src/contexts/themeContext/utils/theme.ts

Currently the CooldownTimer cannot be styled through the theme at all, this adds that possibility
Straight-up just a key in the theme :) Also defaults color to theme.colors.black, which is the same as other text in messages etc.

feat: Add theming to the cooldown timer

---

package/jest.config.js

The current jest config makes it so it also looks for test files in lib/, making it so tests written in TypeScript will be ran twice - once in `src/` and once in `lib/`.
This PR makes it so jest ignores `/lib`

build: Ignore test files in lib/

---

package/src/components/Attachment/Attachment.tsx
package/src/components/Message/Message.tsx

RN SDK currently doesn't support video rendering. And thus when user uploads a video, it gets sent as `attachment.type === 'file'`. But when file gets uploaded from other SDKs, it gets sent as type `video`, and handling of this case was wrong within the SDK. It used to get rendered as `Card` component instead of FileAttachment.
https://getstream.slack.com/archives/C02888QAYG0/p1636955394060400
Render type `video` attachment as file attachment.
| BEFORE | AFTER |
| - | - |
| ![Screenshot 2021-11-15 at 09 02 55](https://user-images.githubusercontent.com/11586388/141744315-8dd514ee-aa54-4efc-ab74-66b1b0c9c249.png) | ![Screenshot 2021-11-15 at 09 03 15](https://user-images.githubusercontent.com/11586388/141744307-c4981188-44f6-4bf1-ac11-bde513a1a907.png) |
Upload video file from react …

fix: render attachment type video in FileAttachment view [CRNS-480]

---

docusaurus/docs/reactnative/common-content/core-components/channel/props/legacy_image_viewer_swipe_behaviour.mdx
package/src/components/Channel/Channel.tsx

Switch off the legacy image swiping behavior
Switch the default value of [`legacyImageViewerSwipeBehaviour`](https://getstream.io/chat/docs/sdk/reactnative/core-components/channel/#legacyimageviewerswipebehaviour) prop to false

fix(perf): turn off legacy image swiping behaviour

---

package/src/components/Avatar/GroupAvatar.tsx
package/src/components/Message/Message.tsx

`Image.prefetch()` calls were introduced to fetch the image attachments and avatars in advance for better UX purpose. But it's not working as expected, images are getting downloaded once during prefetch call and another during rendering Gallery component. And there is no appropriate documentation for `Image.prefetch()` from react-native to resolve this.
So the objective of this PR is to simply get rid of these prefetch calls to save up on those extra image download calls.
- Checkout on v4.0.0 branch
- Keep flipper open on the side
- Open some channel and notice that every image download call happens twice (before this change)

perf: remove Image.prefetch calls to avoid redundant image downloads

---

package/src/components/MessageInput/hooks/useCooldown.ts
package/src/components/MessageInput/hooks/useCountdown.ts
package/src/utils/date.ts

In v4.0.0, the countdown timer is stuck, and isn't actually counting down. This PR aims to fix that.
From feedback when talking about the original PR for the countdown timer, an empty dependency array was added to the useEffect wrapping the actual `setInterval`. This PR removes this, as an empty dependency array makes it so the effect is triggered at mount, and cleaned up at unmount.
Like this, the useEffect will be called on a rerender of MessageInput, and at each tick of the setInterval call that's being set up. It also cleans up the interval each time it's ran, making it so it will be cleaned up even if you dismount the component before the cooldown has completed.

fix: Make countdown timer actually count down

---

docusaurus/docs/reactnative/guides/message_input_customization.mdx
package/src/components/AutoCompleteInput/AutoCompleteInput.tsx
package/src/components/MessageInput/CooldownTimer.tsx
package/src/components/MessageInput/MessageInput.tsx
package/src/contexts/themeContext/utils/theme.ts
package/src/i18n/en.json
package/src/i18n/fr.json
package/src/i18n/hi.json
package/src/i18n/it.json
package/src/i18n/ja.json
package/src/i18n/ko.json
package/src/i18n/nl.json
package/src/i18n/ru.json
package/src/i18n/tr.json

Changing the styling of the CooldownTimer to match the [figma designs](https://www.figma.com/file/ekifwChR9tR7zRJg1QEzSM/Chat-Design-Kit---Current-version?node-id=12254%3A953)
One quirk I'm doing is to check for the amount of characters are displayed as the remaining seconds, as without it, going through 13, 12, 11, 10 the countdown jumped in width from character to character. As seen in the supplied video, this works around that.
I don't think this makes a difference of significance/that can be noticed since the component rerenders every second anyways, and it's a cheap calculation to make, so I haven't optimized it at all. If anybody thinks we should, I'm all ears.
https://user-images.githubusercontent.com/1548276/143273889-c7e3e290-33eb-4bd1-98f6-cfa0e7d3556e.mp4

fix: Add the correct styling for CooldownTimer

---

package/src/components/Message/MessageSimple/utils/renderText.tsx

URL parsing using `anachrome` library seems to break in case text contains some special character or so. Its not worth breaking the app when url parsing fails, and thus we should simply fallback to plain text when this happens.
Add `try ... catch` around url parsing using `anachrome.js` and ignore in case of failure.
- Open a channel
- Send following message: `aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa🤡`
- Long press on this message
- Select "Reply" message action.
- Notice the error on screen.

fix: crash on parsing urls [CRNS-498]

---

package/src/contexts/messageInputContext/hooks/useMessageDetailsForState.ts

This PR fixes the empty mentioned users array issue when a message with a mentioned user is edited. 
Fixes: #1023 
Reference ticket: https://stream-io.atlassian.net/browse/CRNS-493
The solution is fixed in `useEffect` hook.
https://user-images.githubusercontent.com/39884168/145537720-ea3738c2-e31b-4847-9ab3-0dfd0e8ff1fa.mov
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>

Fix: Mentioned users removed after editing message [CRNS - 493]

---

package/.watchmanconfig
package/package.json
package/src/components/Message/MessageSimple/utils/parseUrls.test.ts
package/src/components/Message/MessageSimple/utils/parseUrls.ts
package/src/components/Message/MessageSimple/utils/renderText.tsx
package/yarn.lock

[`anchorme`](https://github.com/alexcorvi/anchorme.js) is not receiving updates, and has started to cause issues with a missing security update, as well as throwing errors some unicode characters if it isn't considered a complete character. (For example when truncation breaks an emoji into a half character since the unicode code points count as 2 characters in JS).
We only use a subset of the functionality of anchorme, so this PR removes anchorme entirely in favor of maintaining our own parsing of links to take its place.
Anchorme markets itself as performant, so I have kept that in mind to check this implementation against the benchmark anchorme uses in its repository to not make this be at the cost of user experience for the end user.
The parser is pretty simple in how it's set up, as …

fix(MessageSimple): Replace `anchorme`, parse links ourselves [CRNS-505]

---

package/src/components/MessageOverlay/OverlayReactionList.tsx

When passing fill in useAnimatedProps, the value passed to
RenderableView in react-native-svg is the literal hex string
and isn't converted to the rgb value array expected.
This fixes #1054
@vishalnarkhede I think this is worth releasing as a hotfix for 3.x as well as including in v4.0.0-beta.2
This ligns up with how the [`hook is supposed to be used as per the reanimated docs`](https://docs.swmansion.com/react-native-reanimated/docs/2.2.0/api/useAnimatedProps/), and works with both reanimated v2.2.x and 2.3.x.
None
Haven't found a good way to automate this yet, but if you open an overlay on android with reanimated v2.3.1 with and without this diff, it should clearly break without and not break when the diff is applied.

fix: Animated prop with fill crashing [CRNS-507]

---

package/src/components/Message/MessageSimple/utils/parseLinks.ts

The version of javascript run for expo doesn't allow lookbehinds. This removes those, and strips out markdown formatted links ahead of parsing the rest of the links in the input string.

fix: Removing markdown formatted liks

---

examples/SampleApp/ios/Podfile.lock

This PR focuses on fixing the error while running `pod install` lately after the `v4` release on iOS. This was due to a dependency mismatch in RCT-Folly.
Error:
```
[!] CocoaPods could not find compatible versions for pod "RCT-Folly":
In snapshot (Podfile.lock):
RCT-Folly (from `../node_modules/react-native/third-party-podspecs/RCT-Folly.podspec`)
In Podfile:
RCT-Folly (from `../node_modules/react-native/third-party-podspecs/RCT-Folly.podspec`)
It seems like you've changed the version of the dependency `RCT-Folly` and it differs from the version stored in `Pods/Local Podspecs`.
You should run `pod update RCT-Folly --no-repo-update` to apply changes made locally.
```
Pushing the latest dependency lock file which is running smoothly with v4.
<details>
<table>
<thead> …

Fix: issues with dependency while running pod install

---

package/src/contexts/messageOverlayContext/MessageOverlayContext.tsx
package/src/contexts/messageOverlayContext/hooks/useResettableState.test.tsx
package/src/contexts/messageOverlayContext/hooks/useResettableState.ts

This fixes #1065, and adds a test to check that the reset of state works as expected. Moved to a custom hook for simplicity.

refactor: Move resettable state to a new custom hook

---

package/src/components/ImageGallery/components/ImageGalleryFooter.tsx

This PR solves the issue of not being able to share files on android devices from the ImageGallery.
Should fix: #1015 
There was an issue with the file name which doesn't have spaces while saving the file i.e. it was saved with (%20 characters) but when we try to read the file using the `readFile` API it worked well and the filename was read with spaced. This is solved by changing the `photo.user.name` to `photo.user.id` which makes more sense. The `photo.userId` is removed as it's undefined every time.
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr> …

fix: Issue on android while sharing file [CRNS - 510]

---

package/src/components/ChannelList/ChannelListHeaderErrorIndicator.tsx
package/src/components/ChannelList/ChannelListHeaderNetworkDownIndicator.tsx

The goal of this PR is to fix the error banner UI in the Channel list screen when there's a network error or the user isn't online.
The text color of the error text is changed to `white(#ffffff)`. The background color of the UI is also fixed. 
Note: These changes were specific to the SDK and not the SampleApp. Tested for Dark mode too.
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>

Fix: Error banner UI in channel list screen [CRNS - 436]

---

examples/SampleApp/src/screens/AdvancedUserSelectorScreen.tsx

This PR fixes the sign-in advanced option UI in the SampleApp.
The input focus border color didn't work previously so now on focusing an input the border color of the text input is changed to `accent_blue`.
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>

Fix: Sign-in advanced option focus UI fix [CRNS - 363]

---

examples/SampleApp/src/components/ChatScreenHeader.tsx
examples/SampleApp/src/components/UnreadCountBadge.tsx
examples/SampleApp/src/components/UserInfoOverlay.tsx
examples/SampleApp/src/context/AppContext.ts
examples/SampleApp/src/hooks/useChannelMembersStatus.ts
examples/SampleApp/src/hooks/usePaginatedAttachments.ts
examples/SampleApp/src/hooks/usePaginatedPinnedMessages.ts
examples/SampleApp/src/hooks/usePaginatedSearchedMessages.ts
examples/SampleApp/src/hooks/usePaginatedUsers.ts
examples/SampleApp/src/screens/AdvancedUserSelectorScreen.tsx
examples/SampleApp/src/screens/ChannelListScreen.tsx
examples/SampleApp/src/screens/ChannelScreen.tsx
examples/SampleApp/src/screens/GroupChannelDetailsScreen.tsx
examples/SampleApp/src/screens/MentionsScreen.tsx
examples/SampleApp/src/screens/MenuDrawer.tsx
examples/SampleApp/src/screens/NewDirectMessagingScreen.tsx
examples/SampleApp/src/screens/NewGroupChannelAddMemberScreen.tsx
examples/SampleApp/src/screens/NewGroupChannelAssignNameScreen.tsx
examples/SampleApp/src/screens/OneOnOneChannelDetailScreen.tsx
examples/SampleApp/src/screens/SharedGroupsScreen.tsx
examples/SampleApp/src/screens/UserSelectorScreen.tsx

This PR solves the issue which enabled the non-admin users to add/remove users from the group in the SampleApp.
The fix is by checking the chat client id and the channel creator id.
This PR also improved the AppContext usage all over the SampleApp using the hook `useAppContext`. This reduces imports and makes the code cleaner IMO.
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>

Fix: Non-admin user group add/remove permissions [CRNS - 359]

---

examples/SampleApp/App.tsx

This PR focuses on solving the user panel swipe issue on android which was not swipeable previously. 
The changes are self-descriptive. Previously it was only for iOS and now it's enabled for Android too. 
<details>
https://user-images.githubusercontent.com/39884168/149091986-1d82d600-57e9-402a-8ef6-03f8ff4120cb.mp4
</details>
<details>
https://user-images.githubusercontent.com/39884168/149092010-acc0039f-fe6b-40df-8cc4-31de41948fb1.mov
</details>

Fix: enable user panel submenu swipe gesture on Android in Sample App [CRNS - 295]

---

docusaurus/reactnative_versioned_docs/version-3.x.x/common-content/core-components/channel/props/input.mdx
package/yarn.lock

This PR fixes the broken link on docusarus website as reported here - https://getstream.slack.com/archives/CP32GBDAA/p1642605506013300
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>

Fix: Broken link in message input docs

---

docusaurus/docs/reactnative/common-content/core-components/channel-list/props/preview_muted_status.mdx
docusaurus/docs/reactnative/core-components/channel_list.mdx
docusaurus/docs/reactnative/ui-components/channel_preview_muted_status.mdx
docusaurus/docs/reactnative/ui-components/channel_preview_title.mdx
package/src/components/ChannelPreview/ChannelPreviewMessenger.tsx
package/src/components/ChannelPreview/ChannelPreviewMutedStatus.tsx
package/src/contexts/channelsContext/ChannelsContext.tsx
package/src/contexts/themeContext/utils/theme.ts

This PR adds the channel muted status component(icon) for a channel in the channel list.
This is done by introducing the `ChannelPreviewMutedStatus` component which is passed through the `ChannelsContext`. The customization is taken in mind and the component can be passed as a prop `PreviewMutedStatus` in the `ChannelList`.
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>

Feat: Add muted channel status in Channel list screen [CRNS - 374]

---

package/src/components/Message/MessageSimple/utils/renderText.test.tsx
package/src/components/Message/MessageSimple/utils/renderText.tsx

When a list item in a message is empty, it has caused an error while rendering the list. This PR fixes that.
This fixes #1067 
Simplified the function to compose the result a bit, added some tests for it as well
Should not be any UI changes
Create a list in a message, but leave one of the elements empty. For example:
```
3. Something
4.
5. Something
```
The app should not crash when you send the message

fix: avoid errors when an empty list item is rendered [CRNS-508]

---

package/src/components/Message/MessageSimple/ReactionList.tsx

When you touch the reactions, it opens overlay. Currently touchable area for reactions is full width of the screen. Since reaction list kinda overlaps with the message content part, it creates a bit of wierd user experiece for end user e.g., user presses on upper half of message content (which is the overlapping part with reactions) and it opens overlay. But bottom half doesn't behave the same.
Also it creates confusion when you try to customize MessageContent. So its better if touchable area is only the reaction icons part. We have a ZD ticket for this - https://getstream.zendesk.com/agent/tickets/18105
Following screenshots display touchable area (black bordered) before and after the change:
<table>
<thead>
<tr>
<td><strong>Before</strong></td>
<td><strong>After</strong></td>
</tr> …

fix: fixed touchable area for reaction list

---

examples/SampleApp/src/screens/GroupChannelDetailsScreen.tsx

An unused import in the SampleApp was reported in the next-release workflow (however, doesn't stop the build. I'll make a separate PR with some changes to the workflows)

refactor: remove unused import of useContext in SampleApp

---

package/src/components/ImageGallery/components/ImageGalleryHeader.tsx
package/src/components/ImageGallery/components/__tests__/ImageGalleryHeader.test.tsx
package/src/components/Message/MessageSimple/utils/renderText.tsx
package/yarn.lock

`fromNow` in `ImageGalleryHeader` as it is at the moment can be undefined on the first render. This ensures it exists before accessing it.
This fixes #1116

fix: ensure fromNow exists before accessing it

---

docusaurus/docs/reactnative/basics/troubleshooting.mdx

This PR involves adding the troubleshooting docs for the channel delete blank screen which appears if the channel is deleted.
Nothing as such. Only the troubleshooting docs are updated. 
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>

docs: Channel delete blank screen troubleshooting docs [CRNS - 472]

---

package/src/components/Attachment/__tests__/buildGallery.test.js
package/src/contexts/messageInputContext/MessageInputContext.tsx
package/src/utils/__tests__/getResizedImageUrl.test.js
package/src/utils/getResizedImageUrl.ts

Start requesting resized version of images only when new CDN is deployed.
- Detect whether new CDN is deployed or not using existence of `oh` and `ow` params in url. If these params exist in url, then it means new CDN has been deployed and SDK can start requesting resized images.
- Otherwise use the original images

fix: only allow image resizing when new CDN is deployed

---

docusaurus/docs/reactnative/basics/stream_chat_with_navigation.mdx
docusaurus/reactnative-docusaurus-dontent-docs.plugin.js
docusaurus/reactnative_versioned_docs/version-3.x.x/basics/getting_started.mdx

Show v4 docs by default, adds notice to v3 as not actively maintained

build: change docs to use v4 by default

---

package/src/contexts/index.ts

Fixes https://github.com/GetStream/stream-chat-react-native/issues/1186
Export `OwnCapabilitiesContext` from SDK

fix: export ownCapabilitiesContext from SDK

---

package/src/components/ChannelPreview/ChannelPreviewMessenger.tsx
package/src/components/ChannelPreview/ChannelPreviewStatus.tsx
package/src/components/ChannelPreview/hooks/useLatestMessagePreview.ts

To make it a bit more readable, I've made the message read status an enum and updated the docs with a description of the values.

refactor: make MessageReadStatus an enum and update docs

---

package/src/components/MessageOverlay/MessageOverlay.tsx
package/src/contexts/overlayContext/OverlayContext.tsx

Move `overlayOpacity` from OverlayProvider to MessageOverlay.
The `OverlayProvider` had `overlayOpacity` as a compulsory prop which might be a problem for the users to add a value. This prop is only used by `MessageOverlay` so we can simply confine the prop to the component itself rather than using it from `OverlayProvider`.
Thanks, @santhoshvai for pointing this out.
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>

fix: change overlayOpacity prop type definition from OverlayContext to MessageOverlay

---

package/src/components/ChannelList/hooks/listeners/__tests__/useChannelUpdated.test.tsx
package/src/components/ChannelList/hooks/listeners/useChannelUpdated.ts

Fixes https://github.com/GetStream/stream-chat-react-native/issues/1193

fix: add missing own_capabilities field after channel.updated event [CRNS-537]

---

package/src/components/AttachmentPicker/AttachmentPicker.tsx

Fix the deprecated warning about `removeListener`

fix: cleanup of keyboard listeners

---

examples/SampleApp/src/screens/NewDirectMessagingScreen.tsx
package/src/components/Channel/Channel.tsx

Fixes - #1191 
- Fixes the above issue by adding the `overrideOwnCapabilities` prop with `sendMessage` capability.
- Since all the capabilities were compulsory previously, so making the type of it as `Partial<OwnCapabilitiesContextValue>` in SDk.
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>

fix: overrideOwnCapabilities typescript issue

---

package/src/components/Attachment/Giphy.tsx
package/src/components/Message/MessageSimple/MessageContent.tsx

The Giphy customization change in https://github.com/GetStream/stream-chat-react-native/pull/1201 caused a bug in the message overlay for Giphy. On the overlay, Giphy did not have any background, it should show the same background as in MessageSimple.
Moved the background color to Giphy component. Then the overlay picks it up.
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
NA

fix: show background for Giphy on long press

---

examples/ExpoMessaging/yarn.lock
examples/SampleApp/yarn.lock
examples/TypeScriptMessaging/yarn.lock
package/expo-package/yarn.lock

This PR fixes the yarn lock version of packages in the package directory(`expo-package`, `native-package`) and example applications.
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>

fix: update yarn lock files in package and examples

---

docusaurus/docs/reactnative/common-content/contexts/image-gallery-context/set_image.mdx
docusaurus/docs/reactnative/common-content/contexts/image-gallery-context/set_images.mdx
docusaurus/docs/reactnative/common-content/core-components/overlay-provider/props/giphy_version.mdx
docusaurus/docs/reactnative/core-components/overlay_provider.mdx
docusaurus/docs/reactnative/ui-components/gallery.mdx
docusaurus/docs/reactnative/ui-components/giphy.mdx
package/src/components/Attachment/Giphy.tsx
package/src/components/ImageGallery/ImageGallery.tsx
package/src/contexts/overlayContext/OverlayContext.tsx
package/src/contexts/overlayContext/OverlayProvider.tsx

This PR involves adding a feature that allows opening a giphy in the image viewer when it's pressed.
This is done by setting the state of `setImage`, `setImages` and `setOverlay` to `gallery`.
<details>
<table>
<thead>
<tr>
<td>Image</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>Image</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
</tr>
</tbody>
</table>
</details>

feat: open giphy in image viewer when pressed [CRNS - 540]

---

package/src/components/Message/MessageSimple/utils/parseLinks.test.ts
package/src/components/Message/MessageSimple/utils/parseLinks.ts

Currently `123.456` would be parsed as a URL, this change makes sure to avoid that.
This assumes that any TLD comprises letters (`a-zA-Z`), and IPs are handled as a separate case with `123.123.123.123` or `1.2.3.4` or anything along those lines.
See above
none
Test case is added to the test suite. You can test it manually if you'd like by sending a message with something like "123.456" as part of the message, and see that it's not rendered as a URL

fix: avoid parsing a decimal number as a URL

---

examples/ExpoMessaging/Readme.md
examples/ExpoMessaging/yarn.lock
examples/SampleApp/ios/Podfile.lock
examples/SampleApp/yarn.lock
package/Makefile
package/expo-package/yarn.lock

The readme of expo messaging app did not have expo package and core installation steps. This caused  https://github.com/GetStream/stream-chat-react-native/issues/1226. To make it easier, we need a single makefile installation step like in the sample app.
Add the makefile installation step for expo package and core in the expo messaging app readme
NA
NA

fix: readme of expo messaging app did not have core/expo package installation steps

---

package/src/components/ImageGallery/ImageGallery.tsx
package/src/contexts/overlayContext/OverlayContext.tsx
package/src/contexts/overlayContext/OverlayProvider.tsx

This PR adds a default value to `giphyVersion` prop in ImageGallery used through OverlayProviderProps.
This also fixes the use of other props in ImageGallery through OverlayProviderProps.
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>

fix: overlay provider props usage in ImageGallery

---

package/src/components/Attachment/Giphy.tsx
package/src/components/Attachment/__tests__/Attachment.test.js
package/src/components/Attachment/__tests__/Giphy.test.js
package/src/components/Channel/__tests__/isAttachmentEqualHandler.test.js
package/src/components/Message/MessageSimple/MessageContent.tsx
package/src/components/Message/MessageSimple/MessageSimple.tsx

Fixes - https://github.com/GetStream/stream-chat-react-native/pull/1219/files#r844457438
- Fixed the condition of isAttachmentEqual logic in MessageSimple and MessageContent component. 
- Fixed the test suite name for isAttachmentEqual prop in Channel.
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>

fix: isAttachmentEqual logic in MessageContent and MessageSimple

---

examples/SampleApp/android/app/build.gradle
examples/SampleApp/android/app/proguard-rules.pro
examples/SampleApp/ios/Podfile.lock
examples/SampleApp/package.json
examples/SampleApp/yarn.lock

When you try to create the release build of SampleApp and test it out on the android device the app crashed with the following error:
```
FATAL EXCEPTION: main
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.swmansion.reanimated.layoutReanimation.f.j()' on a null object reference
FATAL EXCEPTION: main
Process: com.sampleapp, PID: 7079
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.swmansion.reanimated.layoutReanimation.f.j()' on a null object reference
at com.swmansion.reanimated.layoutReanimation.g.r(ReanimatedNativeHierarchyManager.java:1)
at com.facebook.react.uimanager.x0$m.execute(UIViewOperationQueue.java:1)
at com.facebook.react.uimanager.x0$a.run(UIViewOperationQueue.java:19)
at …
```

fix: issue with release build due to react native reanimated@2.3.3 in SampleApp

---

package/src/components/AttachmentPicker/AttachmentPicker.tsx
package/src/components/MessageInput/__tests__/__snapshots__/FileUploadPreview.test.js.snap
package/src/components/MessageInput/__tests__/__snapshots__/MessageInput.test.js.snap

This PR fixes the UI issues with the bottom sheet in the attachment picker.
Fixes - #1299 
The `fullscreenHeight` was using Dimension.get("screen") while the `screenHeight` has the vh around Dimension.get("window") which caused the UI inconsistency. Also, the `handleHeight` caused the full-screen drag with inconsistency. We only need `handleHeight` for Android. 
Check the screenshots attached to see the changes.
*Full screen issue*
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
*Attachment Picker icons*
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table> …

fix: hidden icons due to wrong screenHeight value and remove handleHeight to fix fullscreen top padding in AttachmentPicker

---

docusaurus/docs/reactnative/guides/push_notifications_v2.mdx

A local link was broken in the push documentation.
Cause:  The header of a section was changed after the review comments. But I had terribly forgotten to update the local element link to it as well.
NA
NA
NA

fix: broken local element link in the push doc

---

.github/workflows/sample-distribution.yml

Android compile SDK was updated to 31 for the latest firebase support. This broke the GitHub sample distribution workflow. As JDK 8 is not supported with compile SDK 31.
Updated to JDK 11.
NA
NA

fix: github workflow did not support android compileSdk 31

---

package/src/components/Attachment/Giphy.tsx

The border radiuses (radi? radii? corner go bendy) on the giphy selector doesn't match the design spec, and the corners of the border get cut off. This PR aims to fix that by ensuring a border radius of 16 on all corners except bottom right, as it's shown in the figma designs.
I also snuck in a margin before the `/giphy UserInput` text in the header, as that was missing - the margin being set to 8 is me just copying the margin in the designs. 
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
type `/giphy something` and hit send to render the giphy selector. Then you should see the component in question. Check that the corner borders aren't getting cut off. See my …

fix: set border radius to 16 for giphy selector

---

examples/SampleApp/yarn.lock
examples/TypeScriptMessaging/Gemfile.lock
package/native-package/yarn.lock
package/package.json
package/yarn.lock
yarn.lock

This applies the patches from the following PRs:
#1303 #1280 #1276 #1275 #1274 #1263 #1242 #1240
not much interesting, I just ran `curl https://patch-diff.githubusercontent.com/raw/GetStream/stream-chat-react-native/pull/1303.patch | git apply -v` once per PR.

chore: apply dependabot version changes

---

examples/SampleApp/ios/SampleApp.xcodeproj/project.pbxproj
examples/SampleApp/ios/SampleApp/Info.plist
examples/SampleApp/ios/SampleAppTests/Info.plist

As the GitHub sample app distribution broke before pushing the iOS version change, we have to manually update it
NA
NA
NA

fix: manually update iOS version to 93

---

docusaurus/docs/reactnative/guides/channel_background_customization.mdx

Adding more customization possibilities to our documentation. 
This PR touches Channel background related customization
2 custom. steps one with a static background and 2nd with a dedicated channel preference that are persisted to a key-value store.
N/A
pull PR and run `npx stream-chat-docusaurus -i -s`

docs: adds channel background customization guide

---

examples/SampleApp/ios/SampleApp.xcodeproj/project.pbxproj
examples/SampleApp/ios/SampleApp/Info.plist
examples/SampleApp/ios/SampleAppTests/Info.plist

As the last GitHub sample app distribution broke before pushing the iOS version change, we have to manually update it
Incrementing to 103 due to this error `You've already uploaded a build with build number '102'`
N/A
N/A

fix: manually update iOS version to 102

---

package/src/contexts/messageInputContext/MessageInputContext.tsx

We render image attachments smartly according to their aspect ratio. Although this logic currently doesn't work when we send a message. This is because when we optimistically add a message to list before actually making api call (sendMessage), the image attachment doesn't include `original_height` and `original_width` properties. We rely on backend to populate these values. 
In this PR, we are adding these properties in a message while optimistically adding it to the list.
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
<video src="https://user-images.githubusercontent.com/11586388/170325164-433f7d9b-6c7e-4e60-86ff-d9023ca6f2ea.mov" />
</td>
<td>
<video src="https://user-images.githubusercontent.com/11586388/170325097-9c9b5f19-e263-44de-9008-869892026f1 …

fix: smart gallery rendering while optimistically adding a message to list

---

examples/SampleApp/ios/SampleApp.xcodeproj/project.pbxproj
examples/SampleApp/ios/SampleApp/Info.plist
examples/SampleApp/ios/SampleAppTests/Info.plist

The sample app distribution failed because the build number at the app store hasn't been pushed.
Did it through fastlane. `bundle exec fastlane run increment_build_number xcodeproj:"./ios/SampleApp.xcodeproj"`
NA
NA

chore: manually update build number to 110

---

package/src/contexts/messageInputContext/MessageInputContext.tsx

To upload Audio attachments with the type `audio`.
Ref - #1351 
Added the type in `MessageInputContext.tsx`.
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>

refactor: attachment upload type for audio attachments

---

docusaurus/docs/reactnative/common-content/core-components/channel/props/on_press_message.mdx
package/native-package/yarn.lock
package/src/components/Attachment/Card.tsx
package/src/components/Message/Message.tsx
package/src/components/Message/MessageSimple/utils/renderText.tsx

This PR exposes the url to a customer when the emitter is a `card` or `textLink`
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>

feat: expose link url in onPress

---

package/src/components/Reply/Reply.tsx

This PR fixes the issue with the link text in the Reply view which is overflowing the Reply view area.
Added the condition `!lastAttachment.og_scrape_url` to check if the attachment is a video or a link with a video in it.
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>

fix: issue with the link text overflowing the reply view

---

examples/SampleApp/App.tsx

With the newest develop, I get an error when running the SampleApp reading 
```
Error: The useThemeContext hook was called outside the ThemeContext Provider. Make sure you have configured OverlayProvider component correctly - https://getstream.io/chat/docs/sdk/reactnative/basics/hello_stream_chat/#overlay-provider
```
This seems expected, but also makes it clear we miss wrapping a component in the ThemeProvider before it's used.
This PR simply wraps the entire SampleApp with the ThemeProvider.
1. Build and run the SampleApp on `develop`. This should cause the error to be thrown.
2. Build an run the SampleApp on this branch. This should *not* cause the error to be thrown.

fix: wrap the SampleApp with ThemeProvider

---

package/src/contexts/messageInputContext/MessageInputContext.tsx

This PR focuses on fixing the issue with image uploads on iOS devices.
The solution is to pass `file.filename` instead of `undefined` to the sendImage API. The backend is not able to interpret the file name for the case of native CLI and thereby its type. Passing the file name for ensures that the type is evaluated by the backend for both native and expo and across all platforms.
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>

fix: image uploads issue in iOS devices

---

package/src/contexts/__tests__/index.test.tsx
package/src/contexts/messageContext/MessageContext.tsx

Currently, trying to reply to a message will throw the error `The useMessageContext hook was called outside of the MessageContext provider. Make sure you have configured MessageList component correctly - https://getstream.io/chat/docs/sdk/reactnative/basics/hello_stream_chat/#message-list` out of the box with the SDK.
This PR is a suggestion to avoid this (see next headline)
This error is intended to give users a hint when using a context outside
of its provider.
However, the MessageContext specifically is something we use ourselves
in the Reply component, as well as multiple child components of it, both
as part of the MessageList (within Message context) and in the
MessageInput component (outside Message context).
I've considered two approaches:
1. Removing the error - the idea being …

fix: remove error thrown in useMessageContext

---

docusaurus/docs/reactnative/guides/push_notifications_v2.mdx

A missing comma in the notification template in our docs introduces issues for any user copying the template from there. 
Looks like this will solve #1454

docs: add missing comma in notification template (push v2)

---

docusaurus/docs/reactnative/common-content/contexts/message-input-context/remove_file.mdx
docusaurus/docs/reactnative/common-content/contexts/message-input-context/remove_image.mdx

Our documentation currently shows the wrong parameter type for `removeFile` and `removeImage` - this PR aims to correct this.
- [x Commits follow the [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/) spec

docs: correct the parameter type for removeImage and removeFile

---

package/src/components/AutoCompleteInput/AutoCompleteInput.tsx

In the watercooler production app, Giphy command is disabled via dashboard. In this case, only Giphy must be disabled in the SDK.. but if Giphy is disabled, the mentions are also disabled. This should not be the case.
Remove giphy-enabled verification from the if clause that handles mentions and emojis.
NA
NA

fix: mentions dont work if giphy is disabled

---

examples/ExpoMessaging/ios/Podfile.lock
examples/ExpoMessaging/yarn.lock
examples/TypeScriptMessaging/yarn.lock
package/expo-package/package.json
package/expo-package/yarn.lock
package/native-package/package.json
package/native-package/yarn.lock

This PR fixes an issue where video attachment breaks when video dependency is not installed
removing `optionalDependencies` from `package.json` of respective packages
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>

fix: video attachment when video dependency is not installed

---

package/src/components/AutoCompleteInput/AutoCompleteInput.tsx
package/src/components/AutoCompleteInput/AutoCompleteSuggestionItem.tsx
package/src/components/MessageInput/__tests__/__snapshots__/MessageInput.test.js.snap
package/src/components/Thread/__tests__/__snapshots__/Thread.test.js.snap

Cursor position and hint text position of TextInput remained in the LTR alignment even after enforcing RTL. 
- check if the app is in rtl and changed TextInput alignment accordingly
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
<thead>
<tr>
<td>Before LTR</td>
<td>After LTR</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</tbody>
<thead>
<tr>
<td>RTL with hebrew</td>
<td>RTL with hebrew</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td> …

fix: align placeholderText to right when when in RTL

---

package/src/components/AutoCompleteInput/AutoCompleteSuggestionItem.tsx

This change was made to fix the padding between the titles and icons in command pop-ups that break in RTL
- switched paddingRight for paddingHorizontal so padding is maintained in both rtl and ltr
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>

Fix: RTL command up

---

package/expo-package/src/index.js

The expo media library by default shows videos first and then pictures. However, we need it to sort by time. The native package sorts by time by default. So this change also aligns it with expo and native. This bug was informed by a customer through zendesk.
use `SortBy` prop from expo.
NA
Open attachment picker from expo example app.

fix: expo media library must sort by time

---

package/src/components/Attachment/Gallery.tsx

Currently, image loading indicators will show if _any_ image in a gallery is loading.
This PR aims to move that state to each thumbnail so it acts per image.
I've not refactored much, just moved thumbnails into a separate component to move state there.
No new UI components/style
Have an image in a gallery that can't load (can force it in code, that's what I did), and see that it gets an error indicator while other images load as usual.

fix: move image loading state to thumbnails separately

---

release/release.config.js

The changelog on the current develop branch is not generated due to the presence of a merge commit. However, the presence on mergePattern on the parserOpts should ignore it anyhow. Hence, let's enable to generate changelog even if a merge commit is present.
If I removed `filterRegex: mergeRegex,` the merge commit was ignored as expected and changelog was generated. I do not know however from where this field came from. I cant find it on [official docs.](https://github.com/semantic-release/semantic-release/blob/master/docs/usage/configuration.md#options)
NA
In the root directory, run `yarn extract-changelog` and then check `NEXT_RELEASE_CHANGELOG.md`.

fix: do not quit generating changelog on merge commit

---

docusaurus/docs/reactnative/basics/getting_started.mdx
examples/ExpoMessaging/ios/Podfile.lock
examples/ExpoMessaging/package.json
examples/ExpoMessaging/yarn.lock
examples/SampleApp/ios/Podfile.lock
examples/SampleApp/package.json
examples/SampleApp/yarn.lock
examples/TypeScriptMessaging/ios/Podfile.lock
examples/TypeScriptMessaging/package.json
examples/TypeScriptMessaging/yarn.lock
package/expo-package/yarn.lock
package/jest-setup.js
package/native-package/yarn.lock
package/package.json
package/src/components/MessageInput/__tests__/__snapshots__/MessageInput.test.js.snap
package/src/components/MessageList/__tests__/__snapshots__/TypingIndicator.test.js.snap
package/yarn.lock

The goal of this PR is to upgrade the dependency react-native-reanimated to 2.7.0. The decision was taken because there was an issue with the `__reanimatedWorkletInit` function and `__worklet` property while creating mocks of the package while testing.
Upgraded the package everywhere.
Nil

chore: upgrade react-native-reanimated to 2.7.0

---

examples/SampleApp/ios/SampleApp.xcodeproj/project.pbxproj
examples/SampleApp/ios/SampleApp/Info.plist
examples/SampleApp/ios/SampleAppTests/Info.plist

The sample app distribution failed because the build number at the app store hasn't been pushed by the GH action.
`bundle exec fastlane run increment_build_number xcodeproj:"./ios/SampleApp.xcodeproj"`
NA
NA

chore: manually update ios build number

---

package/src/components/ImageGallery/components/ImageGalleryFooter.tsx

Fixes - #1547 
The background colour is changed accordingly.
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>

fix: image gallery footer background color for dark mode

---

package/src/components/ImageGallery/components/ImageGalleryFooter.tsx
package/src/contexts/messageInputContext/MessageInputContext.tsx
package/src/contexts/messageInputContext/__tests__/__snapshots__/sendMessage.test.tsx.snap

This PR fixes the issues with sharing an image from android and ios devices.
The condition for mime_type availability is added to fix the issue. The colour of the share icon is also fixed for dark mode.
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>

fix: image sharing in android

---

package/src/components/Attachment/VideoThumbnail.tsx
package/src/components/Reply/Reply.tsx
package/src/contexts/themeContext/utils/theme.ts

The PR fixes the Video reply UI in the message list.
Initially, the thumbnail and the image were rendered separately. This is fixed by adding a condition and the design of the video thumbnail is fixed thereby.
PS: Refer screenshots for more details.
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>

fix: added condition to render only the video thumbnail in video reply and fix styles and theming

---

package/src/components/MessageInput/FileUploadPreview.tsx
package/src/components/MessageInput/ImageUploadPreview.tsx

Fixes - #1571 
The appropriate colours are added in accordance with the design for the File and Image upload preview.

fix: add pathFill to the image and file upload Close icon

---

docusaurus/docs/reactnative/guides/push_notifications_v2.mdx

* add a template for showcasing iOS badge number support
* use the new`setLocalDevice` method in the JS client, to avoid an initial api call to add push token
* mention optional multi-bundle support
fixes #1541 
NA
NA

docs(push): add example for iOS badge number addition and multi bundle support

---

.github/workflows/sample-distribution.yml
examples/SampleApp/ios/SampleApp.xcodeproj/project.pbxproj
examples/SampleApp/ios/SampleApp/Info.plist
examples/SampleApp/ios/SampleAppTests/Info.plist

The sample app distribution failed because the build number at the app store hasn't been pushed by the GH action.
* `bundle exec fastlane run increment_build_number xcodeproj:"./ios/SampleApp.xcodeproj"`
* [disable concurrent distributions](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#concurrency)
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>

chore: update ios sample app build number

---

package/src/components/Message/MessageSimple/utils/parseLinks.test.ts
package/src/components/Message/MessageSimple/utils/parseLinks.ts

In the watercooler app, we noticed that a URL including `#` in its path got cut off at `#` when parsed as a link.
This PR should fix this.
Regex is modified to allow the symbol
Send a message containing a link with a pound sign in the path, and see that it's made into a link in its entirety. The URL that caught the issue is `http://help.apple.com/xcode/mac/current/#/devba7f53ad4`

fix: allow pound sign in link paths

---

package/src/components/Attachment/Gallery.tsx

Center the image loading indicator
Simple styling change
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>

fix: center align the image loading indicator

---

package/src/components/MessageOverlay/MessageOverlay.tsx

The commit cc3d391e1841faa8b7c1e35000f21c03d87c1d8c was supposed to block the touch on audio play button on message overlay. But it blocks every touch listeners in the overlay. This PR aims to fix it.
Move pointerEvents="none" to the child container that is 1 level deeper
NA
Long press on audio attachment.
- tap on play button -> nothing should happen
- give a reaction -> reaction works
- press reply -> we get reply on message input

fix: broken touch listeners on message overlay

---

package/src/components/Attachment/Card.tsx
package/src/components/Attachment/Gallery.tsx
package/src/components/Attachment/Giphy.tsx
package/src/components/Message/Message.tsx

When using a long press to pin or give reactions in Attachments, the state does not update unless you close the chat screen and return. This PR aims to fix it.
- fixes #1543 
I used `${prevMessage?.updated_at} === ${nextMessage?.updated_at}` to see if the message was updated and then used it to remove the memoization on the attachment when its reactions or pinning state was updated. 
NA
1. Long press on any GIF or image.
2. Select "Pin to conversation".
3. Long press again, it should show "Unpin from conversation".

fix: reactions and pinning are not updating on attachments

---

docusaurus/docs/reactnative/guides/push_notifications_v2.mdx
examples/SampleApp/src/hooks/useChatClient.ts

iOS foreground notifications are not working anymore due to the new presence of stream object in the data payload from the default template. This PR aims to correct it through the docs and sample app implementation. 
extract the payload and add it to a new object.
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>

fix(docs): ios foreground push notifications

---

package/src/components/Attachment/Gallery.tsx

Resolves the following
- GH issue #1618
- ZD ticket https://getstream.zendesk.com/agent/tickets/25050
Architectural design of our component is such that they access required values from contexts but those values can be overriden from props if needed.  In this particular case, Gallery component uses `message` from MessageContext, but message is missing in its prop. So there is no way to override the underlying message in Gallery component.
I am marking this as bug since it goes against our intention of component designs and seems like something we missed.
Added message prop to Gallery component.
NO UI CHANGES

fix: allow overriding message from props on gallery component

---

package/src/components/Message/MessageSimple/MessageTextContainer.tsx

Fixes: https://getstream.zendesk.com/agent/tickets/25912
Allow re-rendering of MessageTextContainer when markdownStyleProp is updated. Otherwise dark/light themed styles for Reply component's markdown won't update upon toggling between dark-light mode 
How to reproduce the issue:
- Configure following theme in `useStreamChatTheme.ts` in TypescriptMessaging app
```
reply: {
markdownStyles: {
text: {
color: colorScheme === 'dark' ? 'blue' : 'pink',
},
},
}
```
- Open some channel where there is quoted reply
- Press `cmd + shift + A` to toggle between dark and light mode, and notice that text color of quoted reply doesn't update

fix: rerender message text container when markdown style prop updates

---

.github/workflows/sample-distribution.yml
examples/SampleApp/fastlane/Fastfile

- Getting ios build number from app store would be better than having it in codebase because of the non triggering changelog previews in the "next release" PRs.
- Setting up pods take a lot of time now. This can be saved by caching it. 
NA
NA
NA

build: use ios build number from app store and add pods caching

---

docusaurus/docs/reactnative/basics/troubleshooting.mdx

While adding giphy support for Android in watercooler app, realized that animated webp is essential. Also, our docs mention ice cream sandwich which are outdated now.
Align the troubleshooting docs to the latest fresco getting started page: https://frescolib.org/docs/
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
NA

docs: update gif library needs for android

---

package/src/components/ChannelPreview/ChannelPreview.tsx

- Fixes https://getstream.zendesk.com/agent/tickets/26263 (2nd part)
Deleting/Updating messages doesn't always update in the channel preview. 
NA
NA
Delete or update a message in the chat in one device and see the preview on the other. The preview must correspondingly update. Send a few new messages and test updating each one of them. The preview must update.

fix: channel preview message only updates on the first last message

---

package/src/components/ImageGallery/ImageGallery.tsx
package/src/components/ImageGallery/hooks/useImageGalleryGestures.tsx

Without this, the initial index is always assumed to be 0. This allows selecting another image for the gallery to start at, for the gestures.
n/a
n/a
Open the image gallery by selecting an image in an image grid. See that you can navigate right and left between images as normal/expected.

fix: set an initial image index for the ImageGallery

---

docusaurus/docs/reactnative/common-content/core-components/channel/props/on_press_message.mdx
package/src/components/Attachment/FileAttachment.tsx
package/src/components/Message/Message.tsx

- Fixes https://getstream.zendesk.com/agent/tickets/26224
Adds support for listening to assetUrls in the fileAttachment onPress listeners.
NA
NA
NA

feat: add asset url for file attachment's press event emitter

---

package/package.json
package/yarn.lock

Fixes #1644 
Updating the core's JS client version solves the issue. It was because a new function was added to the channel in the JS client in https://github.com/GetStream/stream-chat-js/pull/974
NA
Set the js client version to 6.7.1 in the TypeScriptMessaging App and then use the client with default generics in App.tsx as below,
`const chatClient = StreamChat.getInstance('q95x9hkbyd6p');`
and no generics errors should pop up

fix: generics typing issues if js client is above 6.7.1

---

package/src/components/Message/MessageSimple/utils/renderText.tsx

We are looking to override the default onPressMessage for both Card and TextLink but currently, TextLink is not being emitted.
Updated the custom rules as per the list and other examples. Tested this within the SampleApp.
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>

fix: make onPressMessage possible to override for TextLink

---

.github/workflows/next-release.yml
.github/workflows/release.yml

With RN 0.69, our release breaks with the following error message:
```
sampleapp: error react-native@0.69.4: The engine "node" is incompatible with this module. Expected version ">=14". Got "12.22.12"
```
This PR raises the version used to 16.x
16.x is the [Active LTS version of node](https://nodejs.org/en/about/releases/)
N/A
N/A

ci: bump node version in release workflows to 16.x

---

.gitignore
docusaurus/docs/reactnative/basics/translations.mdx
docusaurus/docs/reactnative/contexts/translation_context.mdx
docusaurus/docs/reactnative/customization/theming.mdx
docusaurus/docs/reactnative/guides/message_actions_customization.mdx
docusaurus/docs/reactnative/guides/push_notifications_v1.mdx
docusaurus/docs/reactnative/ui-components/overlay_reactions.mdx
docusaurus/reactnative_versioned_docs/version-3.x.x/basics/translations.mdx
docusaurus/reactnative_versioned_docs/version-3.x.x/basics/troubleshooting.mdx
docusaurus/reactnative_versioned_docs/version-3.x.x/customization/theming.mdx
docusaurus/reactnative_versioned_docs/version-3.x.x/guides/push_notifications.mdx
docusaurus/reactnative_versioned_docs/version-3.x.x/guides/upgrade_helper.mdx
docusaurus/reactnative_versioned_docs/version-3.x.x/ui-components/overlay_reactions.mdx

This PR address the broken links in docusaurus as outlined by [this](https://docs.google.com/spreadsheets/d/1ekfYOYl1HSs97uU13yYV-I-xjxTQ1cTOnFe0tOdX_BA/edit#gid=0) internal document. 
The changes included in this PR are scoped to v5 content. 
- Updates external links 
- Updates internal docusaurus links
- Adds `.idea` to `.gitignore` 
No tests added, only docs changes.
cc: @jeroenleenarts

Update broken Docusaurus links 

---

docs/index.html
docs/v3/index.html

This PR aims to deprecate the old docs.
Adding a sticky header with a deprecation message and a link to the new docs.
N/A

feat: deprecates old docs

---

docusaurus/docs/reactnative/guides/push_notifications_v2.mdx

The presence of a notification template causes the notifications to show up on foreground. This is confusing to users. I have witnessed two zendesk tickets regarding. Hence I am adding this caution note.
NA
NA
NA

docs: inform user about notification template caveat

---

package/src/components/MessageInput/ImageUploadPreview.tsx
package/src/contexts/themeContext/utils/theme.ts

Currently, you can customize the background behind the dismiss icon for uploaded photos in the message input. This PR allows users to also customize the color of the icon itself (the `x` icon to dismiss the image)
n/a
no UI changes
In an app, change the value of `messageInput.imageUploadPreview.dismissIconColor`. Any color should be fine.
Then upload an image in the message input, and see that the icon has the color you've selected.

feat: allow customization of the close icon for uploads

---

docusaurus/docs/reactnative/guides/push_notifications_v2.mdx

The wording on our expo docs is such that in expo go rn-firebase cannot work. This PR clarifies the confusion. 
NA
NA
NA

docs(push): improve expo installation docs by mentioning the custom dev client

---

docusaurus/docs/reactnative/ui-components/message_input.mdx

<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>

docs: fix irrelavant arrow due to comment in message input documentation

---

package/src/__tests__/offline-feature.test.js
package/src/components/ChannelList/ChannelList.tsx
package/src/components/ChannelList/ChannelListMessenger.tsx
package/src/components/ChannelList/__tests__/ChannelList.test.js
package/src/components/ChannelList/hooks/useCreateChannelsContext.ts
package/src/components/ChannelList/hooks/usePaginatedChannels.ts
package/src/contexts/channelsContext/ChannelsContext.tsx

Fixes: https://github.com/GetStream/stream-chat-react-native/issues/1695
We need explicit way to know whether `channels` have been queries either from local db or server. Currently we initialize `channels` as `[]`, but we can't differentiate between following two cases:
- there are no channels corresponding to certain `filters`
- channels have not been queried from local db or server yet.
Thus in this PR, `channels` have been initialized as `null`, and it will make it explicit what exactly the state of channel list is.
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead> …

fix: handling of empty channels corresponding to filters/sort in offline support

---

package/src/native.ts

Fix a few typescript definition inconsistencies:
1) Currently, if you want to implement a new `getLocalAssetUri` function, typescript will complain as it expects a `never` response, not a string as you can see here
https://github.com/GetStream/stream-chat-react-native/blob/53a9c41981e0b602c2d817696490c66a8045b9f2/package/expo-package/src/index.js#L34-L41
2) The `initializeSound` function is async in code, but in the typedef it is currently sync
https://github.com/GetStream/stream-chat-react-native/blob/75561fdc2d59732a6b8a35dd12d3a0f2b6a56126/package/src/components/Attachment/AudioAttachment.tsx#L163

fix: typescript definition was wrong for getLocalAssetUri and initializeSound

---

examples/SampleApp/src/components/UnreadCountBadge.tsx

The goal of this PR is to fix the unread count update issue in the Sample App.
The condition `if (e.total_unread_count)` is changed to `if (e.total_unread_count !== undefined)` to consider 0 as count too.
Loading the initial count when the app load is still an issue and is to be fixed once the TS issue is handled in the JS client. See the discussion here - https://getstream.slack.com/archives/CE5N802GP/p1663313393442849

fix: wrong unread count issue in the SampleApp

---

package/src/components/Attachment/__tests__/Gallery.test.js
package/src/components/Attachment/utils/buildGallery/buildGallery.ts

This applies to grids of 2x2 images.
Currently, we render images by column. This means that the first two pictures are in column one, the last two in column two.
To conform to what the other SDKs does, this PR flips in by changing `invertedDirection` to `true` for our use of `buildThumbnailGallery`. This will render the photos by row instead.
This fixes #1736
See above
N/A
Pick 4 photos to upload, then send the message.
The grid should be rendered with the first two photos you selected in the first row, as opposed to the first column.

refactor: change the direction gallery thumbnails are rendered

---

package/src/components/Chat/hooks/useIsOnline.ts

Android app state handling makes us disconnect the client every time an Activity is launched (even if it’s the same bundle ID). 
By calling `openConnection` regardless of `closeConnectionOnBackground` we're making sure that the chat functionality will behave normally when returning to the app. 
Changing the logics of the `onForeground` callback.
Calling `openConnection` regardless of `closeConnectionOnBackground` we're making sure that the chat functionality will behave normally when returning to the app. 
N/A
- on android device launch the sample app
- enable logger on the chat client
- go from background to foreground immediately (within a couple of seconds), then you should see `client:openConnection() - open connection called twice...`
- wait for around 20-30 seconds, then …

feat: always open connection when app goes to foreground

---

package/native-package/src/handlers/triggerHaptic.ts

For haptic feedback, we weren't using the default export, resulting in the function not being available. This PR sorts that out by explicitly using the default export.
This fixes #1753 
see above
n/a
Run an app without haptic feedback, then long press a message. Overlay should be visible, no error should be thrown.
Then install react-native-haptic-feedback and do the same.

fix: use the default export of haptic feedback

---

package/src/contexts/messageInputContext/MessageInputContext.tsx

Fixes #1498 
The `image` parameter type is changed from `Asset` to `Partial<Asset>`.
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>

fix: type of image parameter in MessageInputContext's uploadNewImage prop to Partial<Asset>

---

.github/workflows/check-pr.yml
examples/ExpoMessaging/yarn.lock
examples/SampleApp/yarn.lock
examples/TypeScriptMessaging/yarn.lock
package/expo-package/yarn.lock
package/native-package/yarn.lock
package/package.json
package/yarn.lock
yarn.lock

The following weird error happens in GH actions that doesn't happen locally. This PR aims to fix it
```
sampleapp: error An unexpected error occurred: "ENOENT: no such file or directory, lstat '/home/runner/work/stream-chat-react-native/stream-chat-react-native/package/native-package/node_modules'".
```

fix: check-pr and next-release GH actions are broken after bottomsheet upgrade

---

docusaurus/docs/reactnative/guides/push_notifications_v1.mdx
docusaurus/docs/reactnative/guides/push_notifications_v2.mdx
docusaurus/reactnative_versioned_docs/version-4.x.x/guides/push_notifications_v1.mdx
docusaurus/reactnative_versioned_docs/version-4.x.x/guides/push_notifications_v2.mdx

The docs of unsubscribe of push token was not called properly. Causing support questions related to this. However sample app doesn't have this problem as it is using useRef so never faced this there. This part of the docs was ported from v2 so another reason that it was never checked.
NA
NA
NA

docs(push): unsubscribe of push token was not called properly

---

package/package.json
package/yarn.lock

Fixes https://github.com/GetStream/stream-chat-react-native/issues/1765
`react-art` is a deprecated dependency and is part of react now.

fix: drop unnecessary react-art dependency

---

package/src/components/MessageList/utils/getReadStates.ts

Fixes https://github.com/GetStream/stream-chat-react-native/issues/1778
Internal discussion thread - https://getstream.slack.com/archives/CE5N802GP/p1668528970036629
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>

fix: read receipts should not be removed due to message update

---

package/src/components/ChannelList/ChannelList.tsx
package/src/components/ChannelList/hooks/listeners/__tests__/useChannelUpdated.test.tsx
package/src/components/ChannelList/hooks/listeners/useAddedToChannelNotification.ts
package/src/components/ChannelList/hooks/listeners/useChannelDeleted.ts
package/src/components/ChannelList/hooks/listeners/useChannelHidden.ts
package/src/components/ChannelList/hooks/listeners/useChannelTruncated.ts
package/src/components/ChannelList/hooks/listeners/useChannelUpdated.ts
package/src/components/ChannelList/hooks/listeners/useChannelVisible.ts
package/src/components/ChannelList/hooks/listeners/useNewMessage.ts
package/src/components/ChannelList/hooks/listeners/useNewMessageNotification.ts
package/src/components/ChannelList/hooks/listeners/useRemovedFromChannelNotification.ts
package/src/components/ChannelList/hooks/listeners/useUserPresence.ts
package/src/components/ChannelList/hooks/usePaginatedChannels.ts
package/src/components/Chat/hooks/useConnectionRecovered.ts

fixes: https://github.com/GetStream/stream-chat-react-native/issues/1811
Handled the case of `null` channels within event handlers.
- Go to `useChatClient` hook within SampleApp
- Go to line 92 and add following after `await promise`
```tsx
await client.queryUsers(
{
id: 'tommaso',
},
{},
{
presence: true,
},
);
```
- Within `usePaginatedChannels` hook, add some delay before calling `queryChannels` api call.
- Open the app on your device (testflight) and sign in as Tommaso
- Now open the app in your Simulator and sign in as Vishal. And while channel list is being loaded, sign out from Tommaso's account from your app on device (testflight).
- You should see the error.
P.S. Nothing to do with testflight or simulator. Just needs 2 devices for testing.

fix: event handlers when channels is null on channel list component

---

package/native-package/src/handlers/Sound.tsx
package/native-package/src/handlers/Video.tsx

Currently, if you try to play a video from chat or upload a mp3 file the sdk errors up saying React is not present inside the relevant files.
Adding React import to Sound.tsx and Video.tsx
None
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
Upload a Sound file to GetStream chat or a video file
- [] Documentation is updated
- [] New code is tested in main example apps, including all possible scenarios
- [] SampleApp iOS and Android
- [] Expo iOS and Android

fix: import React Dependency into Video / Sound files

---

package/src/components/Chat/hooks/useAppSettings.ts
package/tsconfig.json

We found remapping of `stream-chat-react-native` in tsconfig to be ugly. This PR removes it.
NA
NA
`yarn` build must complete successfully.

fix: remove the unnecessary remapping of chat-core import

---

package/src/components/ImageGallery/components/ImageGridHandle.tsx

The top border radius for the image gallery grid handle creates an unpleasant-looking small gap when displayed in dark mode.
This PR removes the gap by reducing the top border radius from `16` to `12`.
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>

fix: unmatched border radius for image gallery grid handle

---

package/native-package/src/handlers/pickDocument.ts
package/src/components/Channel/Channel.tsx
package/src/contexts/messageInputContext/MessageInputContext.tsx
package/src/native.ts

Make the DocumentPicker dependency optional
This hides the document picker icon by default if the DocumentPicker isn't available
None
Set up an app without the document picker - you should not be able to access the document picker in the attachment picker.
If you then install the document picker, it should reappear, and work as expected.
- [-] Expo iOS and Android

feat: Make the DocumentPicker dependency optional

---

package/src/components/Message/Message.tsx
package/src/contexts/themeContext/utils/theme.ts

Currently you can only theme the background color for targeted messages. This aims to make it possible to add viewstyles to the container for pinned messages
This fixes #1865 
Kept naming similar to existing targeted message theming
None
Add styles to `theme.messageSimple.targetedMessageContainer`, pin a message, and see that your changes are reflected in the app

feat: allow theming the container for pinned messages

---

examples/SampleApp/src/screens/ChannelScreen.tsx

Details: https://github.com/GetStream/stream-chat-react-native/issues/1853#issuecomment-1354260277

fix: always watch channel before passing to channel component

---

examples/SampleApp/App.tsx

This allows for easily resetting the database through the dev menu in the SampleApp
n/a
Selecting the button in the dev menu should clear out your local database for the offline support

feat(SampleApp): Add dev menu item to clear the local DB

---

package/src/components/Message/MessageSimple/utils/renderText.tsx

Fixes #1883 
Disables the markdown parser for images. This is in alignment with iOS SDK and react SDK.
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
Put this message `![Some GIF](https://media.giphy.com/media/dkGhBWE3SyzXW/giphy.gif)`. You should see only one gif.

fix: do not render images twice on markdown

---

package/expo-package/package.json
package/native-package/package.json
package/package.json

- having an old netinfo peer dependency forces users to use `npm i --force` while the latest is compatible as well
- SVG peer dependency needs updating - fixes #1898
- camera roll dependency is unnecessarily fixated to v5, while v6 may come out
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>

fix: do not fixate on peer dependency versions unnecessarily

---

docusaurus/docs/reactnative/basics/getting_started.mdx

Newer expo-cli (46 and above) recommend to use `npx expo` during installation.
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>

fix(docs): use npx as adviced by expo-cli

---

examples/SampleApp/App.tsx
examples/SampleApp/src/context/AppOverlayProvider.tsx
examples/SampleApp/src/context/UserSearchContext.tsx

Fixed some minor typing issues on the sample app

fix: typing issues in sample app

---

examples/ExpoMessaging/yarn.lock
examples/SampleApp/yarn.lock
examples/TypeScriptMessaging/yarn.lock
package/native-package/package.json
package/native-package/yarn.lock

fixes #1932 
N/A
1. Run TSM app both on Android and iOS
2. Go to a random channel and long press on a text message
3. The option "copy text" should not be listed
4. Install the clipboard dependency in TSM app - `yarn add  @react-native-clipboard/clipboard`
5. Repeat step 2, the option "copy text" should be visible.
6. Click on "copy text" and the text should be available to paste somewhere

fix: fixes clipboard detection on android when not installed

---

package/src/components/MessageList/MessageList.tsx
package/src/components/Thread/__tests__/__snapshots__/Thread.test.js.snap

fixes #1810 
ref: https://github.com/Expensify/App/pull/12820
Open message list in Android 33 OS, it should behave as normal without any freeze.

fix: apply workaround for android anr

---

package/src/components/MessageList/MessageList.tsx

Fixes #1968 
Set a EmptyStateComponent for message list and pass an empty array as data, it should not be inverted

fix: empty state component was falsely inverted

---

package/src/components/Chat/Chat.tsx
package/src/components/Chat/hooks/useAppSettings.ts

#2001 caused a bug that a blank screen would appear if user id is not set on offline support. This PR fixes it.

fix: blank screen on offline support if user id is lazily set

---

package/src/components/MessageList/MessageList.tsx

fixes #1989 
Uses countUnread method of chat-sdk if lastRead is unknown 
* Send more than 10 messages to a channel (make sure they are unread for the user who is seeing it)
* Open channel
* Should scroll to the first unread message

fix: scrollToFirstUnreadMessage not working

---

package/src/components/Message/MessageSimple/utils/renderText.tsx

Style was never added to `Bullet` so was always using the default `defaultMarkdownStyles`. This closes #2007 
- Pass the correct markdown style to the `Bullet` component
- Updated `Bullet` and `ListRow` to use the main style object as that already has all the `defaultMarkdownStyles` and then allows for full customisation. 
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
- Open the Sample App, send a message that contains an ordered or unordered list
- See you have all the default markdown styles
- …

fix: Add style prop to Bullet component

---

package/src/components/MessageList/MessageList.tsx
package/src/components/Thread/__tests__/__snapshots__/Thread.test.js.snap

fixes #2012 
Add the following prop
```
<MessageList
additionalFlatListProps={{
style: { backgroundColor: '#ffffff' },
}}
/>
```
the list should behave normally

fix: android list is inverted when custom flatlist style is used

---

package/src/components/Channel/Channel.tsx
package/src/components/Channel/hooks/useTargetedMessage.ts
package/src/components/ChannelPreview/ChannelPreview.tsx
package/src/components/MessageList/MessageList.tsx
package/src/components/MessageList/utils/getReadStates.ts

While @khushal87 investigated #2004, he found that when there were large number of unread messages, the scroll to first unread was broken
The main fix is f35b4486ad098ed1f0e5b7fd1fd4918e80d11252. This fixed a lot of issues
https://user-images.githubusercontent.com/3846977/226427987-1af0b8e5-d0fc-4389-aec4-5a1f42967ec4.mp4
- Open sample app
- Login as "vir"
- Load 7 unread messages - `for i in {1..7}; do stream-cli chat send-message --user "25100e34-4450-3dcb-82eb-fbc34d2b421b" --channel-id "c1ece5ff-a5b1-4e4c-305c-4313fbc2e876" --channel-type "messaging"  --text `date +"%T"`; done`
- open the channel, should highlight the unread message, but should NOT show the unread banner on top of the message
- after 1 or 2 seconds the channel's unread count must become 0
- Go to homepage
-  Load 80 …

fix: initial scroll to first unread message was broken when there more than 55 unread messages

---

examples/ExpoMessaging/yarn.lock
examples/SampleApp/yarn.lock
examples/TypeScriptMessaging/yarn.lock
package/expo-package/yarn.lock
package/native-package/yarn.lock
package/src/components/Message/hooks/useMessageActionHandlers.ts

Fixing the following bug reported by teamworks
```
when toggling a reaction off, we get breaking behavior if there are more than 10 messages AND my reaction wasn't in the last 10 reactions
so if my reaction isn't in the last 10 reactions, it should remove, but instead it adds, which causes silly behavior
```

fix: removing a reaction outside of the latest reactions causes to add it

---

package/src/i18n/en.json

Changing "Cannot Flag Message": "Cannot Flat Message" to "Cannot Flag Message": "Cannot Flag Message"
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>

fix: typo in i18n string about cannot flag message

---

package/expo-package/package.json
package/expo-package/src/handlers/takePhoto.ts
package/expo-package/yarn.lock

The `takePhotos` API was not working with the latest versions of the expo CLI. Therefore, to make this compatible this change was added.
The `ImagePickerResult` is dealt with appropriately.
NA
- Try to upload a photo using the third tab on the attachment picker.

fix: make takePhoto native handler compatible with latest expo versions

---

.github/workflows/docusaurus.yml

Stream chat docusaurus doesn't work with v18 so we have to pin to 16

chore: pin v16 node for docusaurus

---

examples/ExpoMessaging/yarn.lock
examples/SampleApp/ios/Podfile.lock
examples/SampleApp/yarn.lock
examples/TypeScriptMessaging/yarn.lock
package/expo-package/yarn.lock
package/native-package/yarn.lock
package/src/components/Chat/Chat.tsx
package/src/contexts/overlayContext/OverlayProvider.tsx
package/src/hooks/useStreami18n.ts
package/src/utils/Streami18n.ts

In order to use a different i18n library, the translator function needs to be overridden. Currently, the only way to do that is the children inside a translationProvider. But this doesn't override the tFunction for every components. Especially the Image Gallery.
In this PR, we add the ability to override the t function. 
This is the way to use it
```
streami18n.overrideTFunction((key, options) => {
// the custom implementation
});
``` 
NOTE: If `setLanguage` is called, then override must be called after language is set using
`await streami18n.setLanguage("nl")` for example

feat: allow to use different i18n library

---

package/src/components/ChannelList/hooks/usePaginatedChannels.ts
package/src/utils/DBSyncManager.ts

When passing a different filter channel list as header the channel state gets into non initialised state randomly. This PR aims to fix it
Not skipping initialisation when querying channels at all times 
None

fix: do not skip initialisation when querying channels

---

docusaurus/docs/reactnative/guides/performance_guide.mdx

Improve performance guide with channel context usage warning when used within message level customized components.
Describing the needed information with regards to the usage of the channel context
N/A
N/A

docs: Improve performance guide with channel context usage warning

---

examples/SampleApp/fastlane/Fastfile

<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>

fix: pinning xcode version to 14

---

docusaurus/docs/reactnative/basics/offline_support.mdx
docusaurus/docs/reactnative/customization/global_config.mdx

- We support all `react-native-quick-sqlite` version so there is no need to install a spec. one.
- Spelling mistake removed
Remove pin point when installing
N/A
Read to see if you comprehend steps

docs: dont install a sepc. react-native-quick-sqlite version

---

package/expo-package/src/optionalDependencies/pickDocument.ts

The goal is to fix the file picker. It stopped working when I upgraded to version 11.2.2 of expo-document-picker. The require('expo-documentpicker').default would simply return undefined. It seems the default export is removed from the package, hence the require has to be done without the .default. Then it would work again for me.
I have removed the .default from  require('expo-documentpicker').default. It would simply return undefined.
There are none.
I haven't done any other testing besides running the app and using the file picker with this change included.

fix: require of expo-document-picker version v11

---

examples/TypeScriptMessaging/ios/Podfile.lock
package/src/store/apis/index.ts
package/src/store/apis/upsertUserSyncStatus.ts
package/src/utils/DBSyncManager.ts

We discovered that we receive api calls with status 400 when hitting the sync endpoint when the user does not have channels. 
There is no need in making a sync call when there aren't any channels.
This PR aims to aliminate those above mentioned unneded calls.
Early exit before syncing
N/A
We should inspect that there's no regression.
- User 1: Go offline and send, react delete messages.
- User 2: Send messages to user 1.
- User 1: Return online.
- Check whether all messages are updated by both users.
-

fix: reduce-unneeded-syncing

---

package/expo-package/src/handlers/getPhotos.ts
package/native-package/src/handlers/getPhotos.ts
package/src/components/AttachmentPicker/components/AttachmentPickerItem.tsx
package/src/types/types.ts

<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>

fix: incorrect typing of getPhotos between expo and native

---

package/src/utils/DBSyncManager.ts

backend does not accept too old sync dates and sends us a 400 error back.  - `Sync failed with error: \"Too old last_sync_at time, please have last_sync_at argument no later than 30 days ago`
This PR aligns the behavior with other SDKs where we don't execute sync if its too old and also clear out the DB
Used the solution as per [this discussion on Slack](https://getstream.slack.com/archives/CE5N802GP/p1664455487856019)
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>

fix: do not sync if last sync is too old

---

package/src/components/ChannelPreview/ChannelPreviewMessenger.tsx

During hot module reload the app throws the following error 
```
ERROR  Error: You can't use a channel after client.disconnect() was called
This error is located at:
in ChannelPreviewMessengerWithContext (created by ChannelPreviewMessenger{channelPreview})
in ChannelPreviewMessenger{channelPreview} (created by ChannelPreviewWithContext)
in ChannelPreviewWithContext (created by ChannelPreview)
```
the HMR error was because the channel preview component rerendered during HMR of a global variable. This doesn't happen in our sample apps, but our awesome customer had made a repro at https://github.com/farmstrong8/stream-chat-rn-render
My theory is that due to some specific usage of react navigation the component rerenders. 
But anyway we should break HMRs. 
After this fix, if the customer …

fix: hmr issue due to disconnect

---

package/src/components/MessageList/MessageList.tsx

A quick dirty fix for HMR issue with react navigation on cleanup as described in #2169. This should be looked at later to turn the last read state to be more reactive
NA
NA
NA

fix: do not render message list items when channel is disconnected

---

package/src/components/ChannelPreview/ChannelPreviewUnreadCount.tsx

<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>

fix: ui issue when customizing unread count when there is no count

---

package/src/components/MessageList/utils/getDateSeparators.ts

If previous message was sent on Friday of last week and the new message is also Friday but of current week. We don't render a date separator. This PR aims to fix it.
NA

fix: date separators were not visible if prev msg was same day of the week

---

docusaurus/docs/reactnative/core-components/overlay_provider.mdx
package/src/components/ImageGallery/ImageGallery.tsx
package/src/contexts/overlayContext/OverlayContext.tsx
package/src/contexts/overlayContext/OverlayProvider.tsx

Add the ability to autoplay videos in the gallery. Fixes #2186 
Adds a new prop to the `OverlayProvider` called `autoPlayVideo` - the default is false to match current behaviour. This prop is used to define whether the video should start paused or not. 
<details>
https://github.com/GetStream/stream-chat-react-native/assets/45667737/c4f1d56d-96f7-4d70-8758-05caee02e404
</details>
<details>
https://github.com/GetStream/stream-chat-react-native/assets/45667737/51a4a839-ffb8-405d-8a6d-d6ed98ef56fa
</details>
- Open the Sample App on iOS or Android
- Go to a Channel with a video and photos being shared
- Tap on a video and see it maintains the current behaviour of not autoplaying
- Update the App.tsx in Sample App with the prop `autoPlayVideo` …

feat: add ability to autoplay videos in gallery

---

package/src/components/AttachmentPicker/components/AttachmentPickerItem.tsx

<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>

fix: video upload issue through image picker

---

package/src/components/AttachmentPicker/AttachmentPicker.tsx

Fixes #2129 
- Fix loop on Android
- Avoid having the FlatList call `onEndReached` on error states, since that would either show the prompt again or enter a loop until the user gives permission.
N/A
Call `toggleAttachmentPicker` from `useMessageInputContext` on an Android and either deny permission or click outside the Modal.

fix: android picker loop on refuse permission

---

.github/workflows/check-pr.yml
.github/workflows/next-release.yml
README.md

<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>

chore: remove SonarCloud checks from CI

---

package/src/components/Attachment/Gallery.tsx
package/src/contexts/themeContext/utils/theme.ts

Add the ability to add a theme to the gallery image thumbnail.
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>

feat: introduce ability to add theme for the gallery image thumbnail

---

.github/workflows/changelog-preview.yml
.github/workflows/check-pr.yml
.github/workflows/next-release.yml
README.md
examples/ExpoMessaging/yarn.lock
examples/SampleApp/yarn.lock
examples/TypeScriptMessaging/yarn.lock
package/expo-package/yarn.lock
package/native-package/yarn.lock
package/src/components/Attachment/Gallery.tsx
package/src/components/Channel/Channel.tsx
package/src/contexts/themeContext/utils/theme.ts

<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>

Next Release

---

package/src/components/Attachment/Gallery.tsx

<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>

fix: order of application of theme for gallery images

---

examples/TypeScriptMessaging/App.tsx
package/src/components/AttachmentPicker/AttachmentPicker.tsx
package/src/components/AttachmentPicker/components/AttachmentPickerItem.tsx
package/src/components/Channel/Channel.tsx
package/src/contexts/messageInputContext/MessageInputContext.tsx

This PR focuses on fixing the images/video upload through expo apps and native CLI. This also streamlines the usage of `getLocalAssetUri` by optimizing its usage where we select an attachment rather than using it before actually uploading an attachment.
Moreover, the expo media library sends the `id` for every photo/video while the camera roll mostly deals with the `URI` of the attachment. Hence, the check should happen in the same way.
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>

fix: image/video picker upload issue from expo apps and getLocalAssetURI improvements

---

package/src/components/MessageList/MessageList.tsx
package/src/components/Thread/__tests__/__snapshots__/Thread.test.js.snap
package/src/contexts/themeContext/utils/theme.ts

Fixes #2158 by allowing a user to customize the horizontal padding for `MessageList`.
- Remove the default styling in `MessageList` to use the default in `theme.ts`. This means the reactions alignment is always in sync rather than having to update both `screenPadding` and the `MessageList`.
- Added a new theme property called `messageContainer` so we can apply further custom styling beyond just the padding
<details>
Proof of working with an extreme 32 horizontal padding -
</details>
<details>
Proof of working with an extreme 32 horizontal padding -
</details>

feat: customize message padding

---

package/src/components/Message/MessageSimple/ReactionList.tsx

Currently `ReactionList` has several Views that are take up basically the full screen width. These views have a height that is based on the reactionSize. Using the default reactionSize, these take up roughly half the size of the `MessageContent` size if the message is a single line of text. 
This absolute overlay then blocks the `MessageContent` components `TouchableOpacity`. Thus, the goal is to fix #2021 by making `ReactionList` not block the `TouchableOpacity` in `MessageContent`. FYI I couldn't repo the hit box moving when adding a reaction, only the blocking of long press on both iOS and Android. 
Update the `View` and `Svg` to have `pointerEvents` that don't block the underlying `TouchableOpacity` from `MessageContnet` while maintaining the `TouchOpacity` of the `ReactionList` …

fix: add pointerEvents to ReactionList

---

package/src/components/Message/MessageSimple/MessageReplies.tsx
package/src/components/Message/MessageSimple/MessageRepliesAvatars.tsx
package/src/components/Message/MessageSimple/__tests__/__snapshots__/MessageReplies.test.js.snap

Fix #1982 and the curve wasn't showing on Android at all (hard to tell due to `MessageRepliesAvatars` sitting over it)
- Added `flexDirection: row` to the message-replies container
- Update the padding and margins to be nicely padded for both right and left alignment
- Remove the transparent border colour as that meant it never showed on Android
- Removed the Android specific code as that fixed the need to have a transparent colour.
<details>
Before - 
After - 
</details>
<details>
Before - 
After - 
</details>

fix: fix reply border style

---

examples/TypeScriptMessaging/ios/TypeScriptMessaging.xcodeproj/project.pbxproj
package/src/components/MessageOverlay/OverlayReactions.tsx

on Ipad landscape mode, the reaction list was cut off as below..
additionally, I have enabled iPad support in TS messaging app 
this PR aims to fix this
We set the max height based on the item height. The item height is now computed.
Use iPad landscape mode and open the list

fix: iPad landscape mode broke the height reactions list

---

.github/ISSUE_TEMPLATE/bug_report.md

Those lines can create messy markdown when not spaced out properly. E.g., following screenshot:

chore: updated issue template

---

package/src/components/Message/MessageSimple/ReactionList.tsx

Adding:
```tsx
ReactionList={({ messageContentWidth }) => {
return <ReactionList messageContentWidth={messageContentWidth} fill='green' />;
}}
```
to `Channel` doesn't add the fill color to ReactionList.
The PR tends to fix the issue.

fix: unable to apply reaction list fill color

---

package/src/components/Message/MessageSimple/utils/renderText.tsx
package/src/components/MessageOverlay/MessageOverlay.tsx
package/src/components/MessageOverlay/OverlayReactionList.tsx

This PR fixes two UX issues:
- https://github.com/GetStream/stream-chat-react-native/issues/1734
- https://github.com/GetStream/stream-chat-react-native/issues/2188
There are two types of message overlay. One where we show message actions and another one where we show reactions from all the users. The overflowing content can only be resolved by adding ScrollView on message overlay. At some point we [decided to remove](https://github.com/GetStream/stream-chat-react-native/pull/953/files#diff-5ddd01157638d81c5bd88ac5488fe90520647956e3a861da3e6ce07c95fe47d0) `ScrollView` because we already have a `FlatList` in OverlayReactions component (as shown in 2nd screenshot below). FlatList inside ScrollView results into red warning from RN
- Add the ScrollView on the message overlay, but only when we …

fix: long message content overflowing issue in overlay

---

package/package.json
package/yarn.lock

Upgrade the `stream-chat` dependency to get the fix with url param serialization on iOS 17 - https://github.com/GetStream/stream-chat-js/pull/1180
**Fixes**: https://github.com/GetStream/stream-chat-react-native/issues/2235

fix: url param serialisation issue on iOS 17

---

package/package.json
package/yarn.lock

This upgrade ensures feasible upgrade to reanimated v3. The issues with reanimated v3 were fixed between 4.4.6 and 4.4.8.
https://getstream.slack.com/archives/C0404PASF45/p1689082793392139

feat: upgrade bottom-sheet to 4.4.8

---

package/src/components/ChannelPreview/hooks/useLatestMessagePreview.ts
package/src/components/Message/MessageSimple/utils/renderText.tsx

Fixes: https://github.com/GetStream/stream-chat-react-native/issues/2253
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>

fix: issue with String.replaceAll being undefined function

---

package/src/components/MessageInput/SendButton.tsx
package/src/contexts/themeContext/utils/theme.ts

Closes #2153
Added theme variables for the icons.
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>

feat: apply theme to SendButton internal icons

---

package/src/components/Attachment/Gallery.tsx

Fix the application crash that happens when opening a video attachment before the upload is finished.
Fixes #2133 
Avoids sending a null/undefined URL to the native video loader, which would cause a crash.
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
N/A
</td>
<td>
N/A
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
N/A
</td>
<td>
N/A
</td>
</tr>
</tbody>
</table>
</details>
1- Open a chat
2- Open the attachment picker and select a video
3- Send the video
4- Immediately click on the new video thumbnail in the chat before the upload finishes (it'll be black)
Should not crash with this fix.

fix: crash when opening null url

---

examples/ExpoMessaging/yarn.lock
examples/SampleApp/yarn.lock
examples/TypeScriptMessaging/yarn.lock
package/expo-package/yarn.lock
package/native-package/yarn.lock
package/src/components/Message/MessageSimple/utils/renderText.tsx

Fixes #2283 
The PR also updates the dependencies of Axios in packages and sample apps after #2281 
The regex is used in individual usernames rather than the accumulator of the reduce method.
Before:
After:
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>

fix: multiple mentions render in message text

---

examples/TypeScriptMessaging/ios/Podfile.lock
package/src/components/Reply/Reply.tsx
package/src/utils/utils.ts

Most of our deleted message checks depend on `message.type === "deleted"` but the Reply.tsx component doesn't have the same logic and depends on `message.deleted_at` to be defined. We tend to solve it in this PR.
The `message.deleted_at` is changed to `message.type === "deleted"`.
None
None

refactor: quoted message deleted logic in Reply component

---

package/src/components/Message/MessageSimple/utils/generateMarkdownText.ts
package/src/components/Message/MessageSimple/utils/parseLinks.ts
package/src/components/Message/MessageSimple/utils/renderText.tsx

Fixes #2285 
The code structure is also improved with this PR.
The regex is changed so that email type user names are removed when parsing links and then modifying the text accordingly.
Before:
After:

fix: resolve mentioned user as user rather than link

---

package/src/components/ImageGallery/ImageGallery.tsx
package/src/components/ImageGallery/components/ImageGalleryFooter.tsx
package/src/components/ImageGallery/components/ImageGalleryVideoControl.tsx

Fixes: #1949 
For the expo video player, we need to use the `setPositionAsync` API to reset the position to 0. This is not the case for native CLI.
iOS:
https://github.com/GetStream/stream-chat-react-native/assets/39884168/d9670ddb-faa9-4664-9421-a5abb4a27027
Android:
https://github.com/GetStream/stream-chat-react-native/assets/39884168/a7059ffb-f1f8-4c4b-af62-7752b8fbf829

fix: auto restart video in gallery when end reached on Expo

---

package/src/components/Message/MessageSimple/ReactionList.tsx
package/src/contexts/themeContext/utils/theme.ts

Fixes #1863 
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>

feat: add theme to override the reaction list icon color

---

package/expo-package/src/handlers/takePhoto.ts
package/native-package/src/handlers/takePhoto.ts

fix: if camera permission cannot be requested go to settings

---

package/src/components/Message/MessageSimple/utils/renderText.tsx

Fixes #2317 
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>

fix: inability to handle long URLs with params properly when clicked on message

---

package/expo-package/src/handlers/getPhotos.ts
package/native-package/src/handlers/getPhotos.ts
package/src/components/AttachmentPicker/components/AttachmentPickerItem.tsx
package/src/components/MessageInput/MessageInput.tsx
package/src/components/MessageInput/__tests__/MessageInput.test.js
package/src/contexts/messageInputContext/MessageInputContext.tsx
package/src/types/types.ts

Currently, the key for file name and size are `filename` and `fileSize`. We change it to `name` and `size` so that it stays in line with the `Asset` type.
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>

refactor: change filename and fileSize to name and size respectively for Asset type

---

package/src/components/AttachmentPicker/components/AttachmentPickerItem.tsx
package/src/components/MessageInput/FileUploadPreview.tsx
package/src/types/types.ts

The `File` type has the type of `duration` as `string | null`. It should rather be `number` as it makes more sense and also creates a parity with the `Asset` type.
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>

refactor: change duration type to number for both Asset and File type

---

package/src/components/Channel/Channel.tsx
package/src/contexts/messageInputContext/MessageInputContext.tsx
package/src/contexts/messageInputContext/__tests__/__snapshots__/sendMessage.test.tsx.snap
package/src/types/types.ts
package/src/utils/compressImage.ts

Fixes #2327 
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>

fix: image compress logic when uploading image while offline support is enabled

---

package/src/components/Message/MessageSimple/utils/generateMarkdownText.test.ts
package/src/components/Message/MessageSimple/utils/generateMarkdownText.ts
package/src/components/Message/MessageSimple/utils/renderText.tsx

Fixes https://github.com/GetStream/stream-chat-react-native/issues/2297#issuecomment-1813788524
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>

fix: app crash when the message links have special characters in it

---

package/src/components/Attachment/AudioAttachment.tsx
package/src/components/Channel/Channel.tsx
package/src/components/Channel/hooks/useCreateChannelContext.ts
package/src/components/MessageInput/FileUploadPreview.tsx
package/src/components/MessageInput/ImageUploadPreview.tsx
package/src/components/MessageInput/__tests__/AudioAttachmentUploadPreviewExpo.test.tsx
package/src/components/MessageInput/__tests__/AudioAttachmentUploadPreviewNative.test.tsx
package/src/contexts/channelContext/ChannelContext.tsx
package/src/contexts/messageInputContext/MessageInputContext.tsx
package/src/contexts/messageInputContext/__tests__/__snapshots__/sendMessage.test.tsx.snap
package/src/contexts/messageInputContext/hooks/useMessageDetailsForState.ts
package/src/types/types.ts
package/src/utils/compressImage.ts

<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>

fix: do not send two upload requests when offline support is enabled

---

package/src/components/Channel/Channel.tsx
package/src/components/Channel/hooks/useCreateInputMessageInputContext.ts
package/src/contexts/messageInputContext/hooks/useCreateMessageInputContext.ts
package/src/contexts/messagesContext/MessagesContext.tsx

- Start editing a message, and without sending the message - try editing some other message. In that case you will see previous message not getting cleared from input box
- Same thing with combination of quoted reply and editing state as well.

fix: update editing and quoted state within context correctly

---

package/src/components/Channel/Channel.tsx
package/src/components/Channel/hooks/useCreatePaginatedMessageListContext.ts
package/src/components/MessageList/MessageList.tsx

When we would load the channel around a message ID the state was broken. This was mainly due to memoization misses. This PR also adds scroll drag event listening. This is particularly seen if the channel is loaded around a message.

fix: incorrect message list state when non recent messages are loaded

---

package/src/native.ts

<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>

fix: make iOS14RefreshGallerySelection optional

---

examples/SampleApp/ios/Podfile.lock
examples/SampleApp/package.json
examples/SampleApp/yarn.lock
package/src/components/Channel/Channel.tsx
package/src/components/MessageList/MessageList.tsx

When large lists were presented (>200) and a message was targeted, the targeted message could never be shown.. because we would clear out the scrollToFailure methods very early before it gets executed..
this pre clearance is now fixed.
Extra: update rn video component

fix: do not clear the scroll failure timeouts before the failure scroll completes execution

---

package/src/components/ImageGallery/ImageGallery.tsx

We saw the following crash
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>

fix: null check attachment duration

---

package/native-package/src/handlers/compressImage.ts

At least based on the latest documentation, the width should come before height: https://github.com/bamlab/react-native-image-resizer?tab=readme-ov-file#usage-example
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>

refactor: width and height passed to ImageResizer were reversed

---

docusaurus/docs/reactnative/common-content/core-components/channel/props/my_message_theme.mdx
package/src/components/Channel/hooks/useCreateMessagesContext.ts
package/src/components/MessageList/MessageList.tsx
package/src/components/MessageOverlay/MessageOverlay.tsx

myMessageTheme prop was not used in memoisation and so changing it did not cause a rerender

fix: myMessageTheme prop change did not cause a rerender

---

package/src/components/Message/MessageSimple/utils/parseLinks.test.ts
package/src/components/Message/MessageSimple/utils/parseLinks.ts

Previously, special characters inside [] where not taken into account while parsing links from message text. This PR tends to fix the issue by changing the regex.
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>

fix: parsing links from message text having links in markdown format

---

package/src/components/AttachmentPicker/AttachmentPicker.tsx

Fixes #2024 
Before:
https://github.com/GetStream/stream-chat-react-native/assets/39884168/4215f48d-126c-4a60-ae06-533a64cbbc78
After:
https://github.com/GetStream/stream-chat-react-native/assets/39884168/bb7540a8-a854-4e9e-9d70-c6ed877395cc
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>

fix: keyboard transition issue when switching from attachment picker to keyboard

---

package/src/components/Message/Message.tsx
package/src/components/Message/MessageSimple/MessageStatus.tsx
package/src/store/apis/getChannelMessages.ts
package/src/utils/utils.ts

The Goal of the PR is to show blocked messages in the MessageList UI. This is a feature part of moderation.
The blocked messages are represented by message type as error and the message text having `Message was blocked by moderation policies`.
https://github.com/GetStream/stream-chat-react-native/assets/39884168/a18d2aa2-9a97-4a05-a1d2-5ba1e9be78aa

feat: Moderation: show Blocked messages in SDK

---

package/src/contexts/messageInputContext/MessageInputContext.tsx
package/src/utils/utils.ts

<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>

refactor: remove URL regex usage to check if message text contains URL

---

package/src/components/ChannelList/hooks/usePaginatedChannels.ts
package/src/components/ChannelPreview/ChannelPreview.tsx

fixes #2377 #1996
Fixes a race condition between unread count update and channel query update while being on offline support
the issue is that channel preview does not update after query channels on offline support.. and this force update causes it to
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>

fix: outdated unread count on offline support

---

package/src/components/MessageInput/SendButton.tsx
package/src/contexts/messageInputContext/MessageInputContext.tsx

fixes #2316 
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>

feat: add a way to  insert a custom field into a message through message input context

---

package/src/components/ImageGallery/ImageGallery.tsx
package/src/components/ImageGallery/components/ImageGrid.tsx

The goal of the PR is to fix the undefined thumb_url when image grid is opened in image gallery.
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>

fix: undefined thumb_url when image grid opens in image gallery

---

package/src/components/ChannelPreview/ChannelPreviewMessenger.tsx
package/src/components/ChannelPreview/ChannelPreviewTitle.tsx
package/src/components/ChannelPreview/ChannelPreviewUnreadCount.tsx
package/src/contexts/channelsContext/ChannelsContext.tsx

<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>

refactor: add back channel prop to ChannelPreviewTitle and ChannelPreviewUnreadCount

---

docusaurus/docs/reactnative/ui-components/channel-preview-status.mdx
docusaurus/docs/reactnative/ui-components/channel-preview-title.mdx
docusaurus/docs/reactnative/ui-components/channel-preview-unread-count.mdx
package/src/components/ChannelPreview/ChannelPreviewMessenger.tsx
package/src/components/ChannelPreview/ChannelPreviewStatus.tsx

<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>

fix: add channel prop to ChannelPreviewStatus and fix docs props information

---

docusaurus/docs/reactnative/contexts/chat-context.mdx
docusaurus/docs/reactnative/core-components/chat.mdx
docusaurus/docs/reactnative/customization/global_config.mdx
package/src/components/Chat/Chat.tsx
package/src/components/Chat/hooks/useCreateChatContext.ts
package/src/contexts/chatContext/ChatContext.tsx
package/src/utils/StreamChatRN.ts

The goal of the PR is to deprecate the global config `StreamChatRN` and in turn introduce the prop inside `Chat` component.
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>

fix: deprecate global config from usage and add resizableCDNHosts to resizableCDNHosts

---

docusaurus/docs/reactnative/common-content/ui-components/overlay-provider/props/attachment_picker_bottom_sheet_handle.mdx
docusaurus/docs/reactnative/common-content/ui-components/overlay-provider/props/attachment_picker_bottom_sheet_handle_height.mdx
docusaurus/docs/reactnative/common-content/ui-components/overlay-provider/props/attachment_picker_error.mdx
docusaurus/docs/reactnative/common-content/ui-components/overlay-provider/props/attachment_picker_error_button_text.mdx
docusaurus/docs/reactnative/common-content/ui-components/overlay-provider/props/attachment_picker_error_image.mdx
docusaurus/docs/reactnative/common-content/ui-components/overlay-provider/props/attachment_picker_error_text.mdx
docusaurus/docs/reactnative/core-components/overlay-provider.mdx
package/src/components/AttachmentPicker/AttachmentPicker.tsx
package/src/components/AttachmentPicker/components/AttachmentPickerIOSSelectMorePhotos.tsx
package/src/contexts/overlayContext/OverlayProvider.tsx
package/src/index.ts

The goal of the PR is to add the ability to customize the attachment picker to select more photo components for iOS.
Note: This PR also removed unused docs files around the attachment picker.
The component can be customized using the `AttachmentPickerIOSSelectMorePhotos` prop in the `OverlayProvider` component:
Eg:
```
AttachmentPickerIOSSelectMorePhotos={() => {
return (
<>
<Text>You are given selected access to the image gallery.</Text>
<Button onPress={iOS14RefreshGallerySelection} title='Manage' />
</>
);
}}
```
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead> …

feat: add customizability for attachment picker ios select more photos component

---

examples/SampleApp/src/hooks/usePaginatedAttachments.ts
examples/SampleApp/src/hooks/usePaginatedPinnedMessages.ts

The goal of this change is to fix a bug in the usePaginatedAttachments and usePaginatedPinnedMessages hooks. This bug caused the loading state to not be reset to false for empty lists. As a result, the empty list indicator could not be displayed.
The change consists of adding the following code to both hooks:
`setLoading(false)`
1. Create a new chat without any messages.
2. Open the screen with attachments or pinned messages.
3. Notice that the empty state is not visible. This is because the loading state is still true even though there are no results and the data has finished loading from the API.

fix(sample-app): for the loading status which did not return to false when the list of attachments or pinned messages was empty

---

examples/SampleApp/App.tsx
package/src/components/MessageInput/SendButton.tsx
package/src/contexts/messageInputContext/MessageInputContext.tsx

due to #2422 we supported adding any custom fields to the message
but if an integrator adds `<TouchableOpacity onPress={sendMessage}>` it will unintentionally add any touchable event params to the signature. And this creates a bug with offline support as it has cyclic structure.
This was pointed out [here](https://github.com/GetStream/stream-chat-react-native/pull/2453#issuecomment-2015865576)
In this PR we change the signature of the method so that this cannot happen anymore

fix: offline support saving cyclic structure

---

examples/ExpoMessaging/useStreamChatTheme.ts
examples/TypeScriptMessaging/App.tsx
examples/TypeScriptMessaging/useStreamChatTheme.ts
package/src/components/Indicators/LoadingIndicator.tsx
package/src/components/MessageInput/SendMessageDisallowedIndicator.tsx
package/src/components/MessageList/MessageList.tsx

This PR fixes the theme for the `MessageList` and the `SendMessageDisallowedIndicator` components. The background colour is especially fixed, which was white for most cases if no external colour is applied.
The empty state spinner was also not rendering. That is also fixed in the PR.
Before:
https://github.com/GetStream/stream-chat-react-native/assets/39884168/354b86c4-8158-4c01-86b6-74bab4fbe895
After:
https://github.com/GetStream/stream-chat-react-native/assets/39884168/bbbf4011-6d32-42d0-9d4a-28b6893a4084

fix: theme for MessageList and SendMessageDisallowedIndicator

---

examples/SampleApp/src/hooks/usePaginatedSearchedMessages.ts
package/src/components/MessageList/MessageList.tsx

The goal of the PR is to solve the scroll-to-bottom visible issue when the message list is empty and also not to show the scroll-to-bottom button after the offset is reached.
PFA the video attached that shows the previous and new behaviour(as per the PR):
Previous:
https://github.com/GetStream/stream-chat-react-native/assets/39884168/69e5c23c-0aab-4dc5-bb3f-0b0e820d3b66
New:
https://github.com/GetStream/stream-chat-react-native/assets/39884168/b062ebce-5533-45ee-bb3c-f816da5b86c7
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr> …

fix: scroll to bottom issue when the message list is empty

---

package/src/components/AttachmentPicker/AttachmentPicker.tsx
package/src/components/ImageGallery/ImageGallery.tsx

Normalise the snap points to never have negative value as it causes crashes in the apps of integrators

fix: crashes due to negative bottom sheet snap points

---

package/src/components/Channel/Channel.tsx
package/src/components/MessageList/MessageList.tsx

This PR fixes the bug where we did not watch on connection recovery. Since we directly call the `resyncChannel` function on `connection.changed` event that has this early exit(`if (!channel.initialized) return;`), which will never allow the channel to be watched.
https://github.com/GetStream/stream-chat-react-native/blob/develop/package/src/components/Channel/Channel.tsx#L1206 
Moreover, there is no real need to reload the entire channel when sending a message. When the connection is recovered, the messages sent by other users are already fetched without any issues.
1. Calling the reload channel for offline case is vague, and the messages, even if sent, will fail, and you cannot really fetch new messages while offline thereby reloadChannel will obviously fail. This is also fixed in the …

fix: messages not received when connection recovered and do not reload channel when sending message

---

package/src/components/Message/MessageSimple/MessageContent.tsx
package/src/contexts/themeContext/utils/theme.ts

Fixes #2461 
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>

feat: add sender and receiver message theme background color

---

package/src/components/Message/MessageSimple/utils/renderText.tsx

Fixes #2505
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>

fix: incorrect mentioned users regex users with same prefix

---

package/src/components/MessageInput/hooks/useAudioController.tsx

Fix issue when upload audio in android.
IOS ??
Replace : and . in sample name audio record
Create a new React Native project
Follow steps in getStream page for RN
Add .aac and mime audio/aac en Overview Panel
Enable audioRecording in the chat
Try to send audio
Audio upload file
See logs in GetStream Board: http: no such file. status 400

fix: Stream chat fix http no such file

---

package/src/components/ChannelPreview/hooks/useLatestMessagePreview.ts

Preventing deleting last_read of current user.
In current implementation, `getLatestMessageReadStatus` function manipulates `channel.state.read` directly and deletes read state of current user.
```
const readList = channel.state.read;
if (currentUserId) {
delete readList[currentUserId];
}
```
This causes problems in case of using `channel.lastRead()` function after posting new message. Because `this.state.read[userID]` is set undefined after calling `getLatestMessageReadStatus`.
https://github.com/GetStream/stream-chat-js/blob/master/src/channel.ts#L901
To prevent this, how about copying object to avoid manipulating state directly?
Nothing changed.
- `channel.lastRead()` does not return null after posting new message.

Fix: channel.lastRead() returns null after posting a message

---

package/src/components/Message/MessageSimple/MessageFooter.tsx
package/src/components/Message/MessageSimple/MessageTimestamp.tsx
package/src/utils/getDateString.ts

We mistakenly removed the `formattedDate` prop from the `MessageFooter` component and introduced a `date` prop in #2514. In this PR, we add back the prop and allow both modes of data passing in the component.
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>

fix: add back formattedDate prop to MessageFooter

---

docusaurus/docs/reactnative/common-content/contexts/message-input-context/editing.mdx
docusaurus/docs/reactnative/common-content/contexts/message-input-context/quoted_message.mdx
package/src/components/Channel/Channel.tsx
package/src/components/Channel/hooks/useCreateInputMessageInputContext.ts
package/src/components/Message/MessageSimple/MessageAvatar.tsx
package/src/components/Reply/Reply.tsx
package/src/contexts/messageInputContext/MessageInputContext.tsx
package/src/contexts/messageInputContext/hooks/useCreateMessageInputContext.ts
package/src/contexts/messagesContext/MessagesContext.tsx

Change quoted message state from `boolean | message type` to `message type | undefined` to improve code.
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>

fix: change quotedMessage type to MessageType or undefined

---

package/src/components/Thread/__tests__/__snapshots__/Thread.test.js.snap
package/src/mock-builders/generator/message.js
package/src/store/QuickSqliteClient.ts
package/src/store/mappers/mapMessageToStorable.ts
package/src/store/mappers/mapStorableToMessage.ts
package/src/store/schema.ts
package/src/utils/removeReservedFields.ts

<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>

fix: store message_text_updated_at field in the offline DB

---

package/src/components/Message/Message.tsx
package/src/components/Message/MessageSimple/MessageContent.tsx
package/src/components/Message/MessageSimple/MessageSimple.tsx
package/src/components/Message/MessageSimple/MessageTextContainer.tsx

<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>

fix: i18n in message rerender issue for MessageText component

---

package/src/components/MessageList/MessageList.tsx

Fixes #2569
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>

fix: show parent thread message on navigation through message action if its empty

---

package/src/components/Attachment/Gallery.tsx
package/src/contexts/themeContext/utils/theme.ts

<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>

fix: add borderRadius theme property for Gallery image

---

docusaurus/docs/reactnative/common-content/contexts/thread-context/parent_message_prevent_press.mdx
docusaurus/docs/reactnative/contexts/thread-context.mdx
docusaurus/docs/reactnative/ui-components/thread.mdx
package/src/components/Channel/hooks/useCreateThreadContext.ts
package/src/components/Thread/Thread.tsx
package/src/components/Thread/components/ThreadFooterComponent.tsx
package/src/contexts/threadContext/ThreadContext.tsx

Fixes #2565
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>

fix: thread reaction list rerender and add prop to enable/disable press on parent message

---

package/src/components/ChannelPreview/ChannelPreview.tsx
package/src/components/ChannelPreview/hooks/useLatestMessagePreview.ts
package/src/utils/utils.ts

Fixes #2583 
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>

fix: channel preview update on new message when coming from BG to FG

---

package/src/components/Message/MessageSimple/MessageSimple.tsx

<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>

fix: do not show reactions bubble on deleted message

---

examples/SampleApp/src/components/NewDirectMessagingSendButton.tsx
package/src/components/MessageList/utils/getReadStates.ts

The goal of the PR is to have parity between React and React Native SDK around message read status.
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>

fix: message read state according to actual read count

---

package/src/components/Chat/hooks/useCreateChatContext.ts

The goal of the PR is to have the appSettings available when the chat client is connected in the Chat Context. Initially, it was null when offline support was disabled in some cases. This has been fixed in the PR.
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>

fix: appSettings rerender issue in the ChatContext

---

package/src/components/ImageGallery/ImageGallery.tsx
package/src/components/ImageGallery/hooks/useImageGalleryGestures.tsx
package/src/components/ProgressControl/ProgressControl.tsx

<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>

fix: animations and gesture handler(GestureDetector) usage in ImageGallery

---

package/src/components/MessageList/MessageList.tsx
package/src/components/MessageList/__tests__/MessageList.test.js

This PR fixes [this Github issue opened towards our SDK](https://github.com/GetStream/stream-chat-react-native/issues/2629).
The issue happened whenever one tried to target a message in a larger channel, that would be outside of the processing window of our underlying `FlatList` in `MessageList`. Whenever this is the case and we cannot find the message, we should try to load it in order to load to the correct message set as well as everything around the message.
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table> …

fix: targeting message outside bounds

---

package/src/components/MessageInput/FileUploadPreview.tsx

The PR fixes [this JIRA issue](https://stream-io.atlassian.net/browse/PBE-5600).
The cancel button set as a child of `UploadProgressIndicator`, making it unclickable whenever `enableOfflineSupport` is set to `false`. Moving it out fixes the issue.
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>

fix: inability to cancel file uploads

---

examples/ExpoMessaging/package.json
examples/ExpoMessaging/yarn.lock
package/src/components/AttachmentPicker/components/AttachmentPickerBottomSheetHandle.tsx
package/src/components/ImageGallery/ImageGallery.tsx
package/src/components/ImageGallery/components/AnimatedGalleryImage.tsx
package/src/components/ImageGallery/components/AnimatedGalleryVideo.tsx
package/src/components/ImageGallery/components/ImageGalleryFooter.tsx
package/src/components/ImageGallery/components/ImageGalleryHeader.tsx
package/src/components/ImageGallery/components/ImageGalleryOverlay.tsx
package/src/components/ImageGallery/components/__tests__/ImageGalleryHeader.test.tsx
package/src/components/ImageGallery/hooks/useImageGalleryGestures.tsx
package/src/components/MessageOverlay/MessageActionList.tsx
package/src/components/MessageOverlay/MessageOverlay.tsx
package/src/components/MessageOverlay/OverlayReactionList.tsx
package/src/components/MessageOverlay/OverlayReactions.tsx
package/src/contexts/themeContext/utils/theme.ts

Usage of `createAnimatedComponent` is removed to solve the laziness in the component while rendering it in new architecture.
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>

fix: animations laginess on the ImageGallery and MessageOverlay on new architecture

---

package/src/components/Chat/Chat.tsx
package/src/components/Chat/__tests__/Chat.test.js
package/src/mock-builders/mock.js
package/src/utils/DBSyncManager.ts

This PR fixes a niche' usecase in our SDK as explained in [this Slack thread](https://getstream.slack.com/archives/C04GGF7CD9P/p1724688121503949). The tl;dr version of the issue is the following:
- If the `Chat` component gets unmounted and then remounted (i.e if the chat is perhaps used in a modal, overlay or anything of the sort that would destroy the entire context tree from the virtual DOM whenever closed), we will initialize the `DBSyncManager` multiple times
- This causes the listener towards the `connection.changed` event to be subscribed more than once (since the `DBSyncManager` lives within the JS runtime, rather than the components' lifecycle) amongst other things
- We can also never have the reference towards the old listener back so it's impossible to clean it up, and if done …

fix: memory leak during remount or user change

---

examples/SampleApp/package.json
examples/SampleApp/yarn.lock

Since some versions ago, the `SampleApp` for our RN SDK crashes on start. This only happened on `release` builds and not on debug ones, which makes it annoying to debug.
The culprit was the `moment-timezone` library, which is added as a dev dependency. I haven't figured out why this one doesn't work whereas whenever we used `moment` instead of it it defaulted to `daysjs` (which is a non-dev dependency), but for now I want to fix the `SampleApp` first and then have a look at that right after.
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td> …

fix: add moment-timezone as a dependency to the app

---

.github/workflows/sample-distribution.yml

Pushing directly (and only) to the `SampleApp` path [like so](https://github.com/GetStream/stream-chat-react-native/commit/54fe1b7fb5eb4a8cc5ebddc8fdfa9aa211624050) did not trigger a release, since the path was wrong (likely old structure).
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>

fix: wrong path in gh workflow for SampleApp

---

package/src/components/ChannelList/ChannelListMessenger.tsx

The goal of the PR is to fix the unnecessary render of the skeleton in the Channel List messenger component, especially when it is already handled within the `ListEmptyComponent` of `FlatList`. 
Remove the extra condition for the same.
Before:
After:

fix: loading skeleton in the Channel List unnecessary display

---

package/expo-package/src/optionalDependencies/takePhoto.ts
package/native-package/src/optionalDependencies/pickImage.ts
package/native-package/src/optionalDependencies/takePhoto.ts
package/src/components/AttachmentPicker/components/AttachmentPickerItem.tsx
package/src/components/MessageInput/FileUploadPreview.tsx
package/src/components/MessageInput/MessageInput.tsx
package/src/contexts/messageInputContext/MessageInputContext.tsx
package/src/contexts/messageInputContext/__tests__/sendMessage.test.tsx
package/src/contexts/messageInputContext/__tests__/updateMessage.test.tsx
package/src/contexts/messageInputContext/hooks/useMessageDetailsForState.ts

The goal of the PR is to primarily solve the multiple image upload issue on the new architecture but this also applies to the current v5 branch as the improvements here make sense and are not architectural dependant.
There are a few improvements in the `useEffect` of the `MessageInput` as well that is supposed to target only the media library(attachment picker) but don't make sense for the native image pickers, so proper checks are added around the same and improves the upload process for normal use-cases.
The PR also solves the issue of clicked images not respecting the file size config check.

fix: multiple image upload issue using native image picker and generic improvements for upload

---

package/expo-package/src/handlers/Audio.ts
package/expo-package/src/optionalDependencies/Video.ts
package/jest-setup.js
package/native-package/src/optionalDependencies/Audio.ts
package/src/components/MessageInput/MessageInput.tsx
package/src/components/MessageInput/__tests__/MessageInput.test.js
package/src/components/MessageInput/components/AudioRecorder/AudioRecorder.tsx
package/src/components/MessageInput/hooks/useAudioController.tsx
package/src/native.ts

This PR addresses the issues mentioned in [this Github issue](https://github.com/GetStream/stream-chat-react-native/issues/2636). In addition to this, it also takes care of a variety of additional bugs and odd behaviours I found with async audio recording in particular.
Provided below is a list of the things it fixes.
General (all platforms):
- When letting go of the recording button while below both the threshold for locking and canceling, the recording is sent to the chat as an available attachment
-  I wasn't too sure if this is the behaviour we want, but it seems a lot more intuitive than having the recording stuck in a weird state so it made sense
- The difference between locking and doing it like this is that this is the "quick way" to send an audio recording whereas the lock is …

fix: audio recording variety bugs

---

package/src/components/Chat/hooks/__tests__/useAppSettings.test.tsx
package/src/components/Chat/hooks/useAppSettings.ts

The goal of the PR is to allow to fetch app settings for the api key even when the connect user is not done. Ideally the app settings has nothing to do with userId so this should not be checked when fetching the app settings. This has been fixed in the PR.
Note: This PR handles the case for non-offline cases and could be a temporary fix. For offline cases, we will have a look into it later.
cc: @isekovanic 
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>

fix: issue with loading app settings when the connectUser is not called on app

---

package/src/components/Message/MessageSimple/utils/generateMarkdownText.ts
package/src/components/Message/MessageSimple/utils/renderText.tsx
package/src/contexts/messageInputContext/MessageInputContext.tsx
package/src/utils/utils.ts

The goal of the PR is to allow uploading images/files that have special characters in their file names. This PR tends to fix the issue by escaping the character by replacing those characters with `_`.

fix: unable to upload file due to special characters in the file name

---

package/src/components/Message/MessageSimple/utils/parseLinks.test.ts
package/src/components/Message/MessageSimple/utils/parseLinks.ts
package/src/components/Message/MessageSimple/utils/renderText.tsx

This PR fixes [this issue](https://getstream.slack.com/archives/C07ASFG19SL/p1725646018734349) posted in a client channel.
Essentially, we modify the regex so that we respect the [built-in url schemes](https://reactnative.dev/docs/0.73/linking?syntax=ios#built-in-url-schemes) the OS provides.
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>

fix: avoid prepending http before native supported url schemes

---

package/src/hooks/useScreenDimensions.ts
package/src/hooks/useViewport.ts

The memoisation was very wrong in these two hooks. This PR fixes them.

fix: bad memoisation in window, screen dimension listener hooks

---

examples/SampleApp/Gemfile.lock
examples/SampleApp/fastlane/Pluginfile

Relates to https://github.com/GetStream/fastlane-plugin-stream_actions/pull/9

fix: bump fastlane plugin version

---

examples/SampleApp/Gemfile.lock
examples/SampleApp/fastlane/Pluginfile

Default:
```ruby
max_tolerance = 5000 Bytes
fine_tolerance = 2500 Bytes
```
These values can be adjusted, eg:
```ruby
show_sdk_size(max_tolerance: 10000, fine_tolerance: 5000)
```

fix: bump max tolerance for sdk size analysis

---

package/expo-package/src/optionalDependencies/pickImage.ts

The `pickImage` utility for Expo previously requested permissions for both Android and iOS, which should not be the case for the native image picker. HingeHealth reported this, and this has been fixed as part of it.
The permission is now requested only for iOS.
Ref: https://getstream.slack.com/archives/C05BNFLTZ33/p1726660030605229?thread_ts=1714148969.598989&cid=C05BNFLTZ33
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>

fix: request image access permissions for iOS only for native image picking

---

package/src/components/Channel/Channel.tsx
package/src/components/Channel/hooks/useCreateInputMessageInputContext.ts

We have an issue with memoization where if you do the following:
- Override `doSendMessageRequest` on the `Channel` level
- Make `doSendMessageRequest` depend on some local state that gets updated later
only the initial value of that state would be memoized.
Zendesk ticket: https://getstream.zendesk.com/agent/tickets/55303
The reason why we wrap `sendMessage` in a `ref` is due to the fact that simply adding it to the dependency array will likely cause a ton of rerenders of components everywhere. I realise it's a hacky way to solve this, but more conventional methods such as wrapping it inside a `useCallback` are a bit difficult since we would need to wrap all of its other dependencies in callbacks as well, causing a cascading effect. Ideally, this should be solved by getting rid of the …

fix: properly resolve sendMessage during memoization

---

docusaurus/docs/reactnative/guides/custom-message-actions.mdx
package/src/components/Message/Message.tsx
package/src/components/Message/MessageSimple/ReactionList.tsx
package/src/components/Message/utils/messageActions.ts
package/src/contexts/messageContext/MessageContext.tsx
package/src/contexts/overlayContext/OverlayContext.tsx

The goal of the PR is to deprecate the `messageReactions` prop from `Overlayprovider` since it doesn't work and seems useless. Also, the `messageReactions` prop of default message actions function is deprecated as a part of it and instead the `isMessageActionsVisible` is used for better clarity according to the behaviour.
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>

fix: deprecate messageReactions prop and use isMessageActionsVisible instead for messageActions

---

package/src/components/Message/hooks/useMessageActions.tsx
package/src/components/Message/utils/messageActions.ts

The goal of the PR is to make the type of the `copyMessage` to be always defined. The check for the `setClipboardString` function can be checked at the `messageActions.ts` itself, and the TS does not have to be handled explicitly.
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>

fix: copy message action type for message actions

---

package/src/components/MessageList/MessageList.tsx
package/src/components/Thread/__tests__/__snapshots__/Thread.test.js.snap

Fixes [this Zendesk issue](https://getstream.zendesk.com/agent/tickets/55535).
While inverting manually, we were inverting the entire `CellRenderer` component. Debugging how the `FlatList` rendering mechanism works, we can see that each `Cell` within it comprises of 2 parts: the `ListItem` component (which `renderItem` spits out) and the `ItemSeparatorComponent` just below it. By inverting the `Cell` we would invert the entire composition, while we should be really inverting them separately.
Also fixes an issue where the `ItemSeparatorComponent` was not being inverted properly (noticeable if you would add text to it for example, since we'd never invert this).
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td> …

fix: properly invert list manually android

---

package/src/components/AttachmentPicker/AttachmentPicker.tsx

Solves [this GH issue](https://github.com/GetStream/stream-chat-react-native/issues/2663#issuecomment-2360252605). Details of the reproduction steps can be found in the issue itself.
Here is a brief summary of why this issue is happening:
- Looking at the [`containerHeight` property](https://gorhom.dev/react-native-bottom-sheet/props#containerheight) in the library as well as looking at the implementation for a bit, we can clearly see that:
- This value is not meant to be used as a dynamic one
- It completely prevents recalculation from the library itself and relies on this value solely
- Typically, whenever we change landscape the value for the top area insets changes (as well as the screen height) and this is passed as a dynamic value to the `containerHeight`; the `BottomSheet` is …

fix: changing orientation attachment picker issues

---

package/src/components/MessageList/MessageList.tsx

Fixes [this issue](https://getstream.zendesk.com/agent/tickets/56162).
The Android inversion workaround swaps around the leading components in another axis entirely. This makes sure that the message is considered as a whole and the inversion happens on the entire group, putting the date separator in the correct position.
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>

fix: own message custom theme bug

---

package/src/components/AttachmentPicker/components/AttachmentPickerItem.tsx
package/src/contexts/messageInputContext/MessageInputContext.tsx
package/src/i18n/en.json
package/src/i18n/es.json
package/src/i18n/fr.json
package/src/i18n/he.json
package/src/i18n/hi.json
package/src/i18n/it.json
package/src/i18n/ja.json
package/src/i18n/ko.json
package/src/i18n/nl.json
package/src/i18n/pt-br.json
package/src/i18n/ru.json
package/src/i18n/tr.json

Fixes an issue where the `maxNumberOfFiles` property was not respected by the native file picker for images. It should now properly stop the user if they're trying to upload too many images.
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>

fix: native picker max images

---

package/src/components/Channel/Channel.tsx

The goal of the PR is to load the channel at the very end when the messageId is undefined, making sure the messages in the state doesn't match the latest message.
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>

fix: load channel at the very end when messageId is undefined

---

package/src/components/ChannelPreview/ChannelPreviewMessenger.tsx
package/src/components/ChannelPreview/hooks/useChannelPreviewDisplayPresence.ts

Fixes an issue of an app crash when `ChannelAvatar` is used outside of `ChannelList`. 
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>

fix: ChannelAvatar crash when used outside of ChannelList

---

package/src/components/MessageList/MessageList.tsx
package/src/components/MessageList/__tests__/MessageList.test.js

Fixes an issue where the `MessageList` would be loaded twice whenever we target a message specifically through `messageId` on the `Channel`. The `targetedMessage` prop still works as intended.
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>

fix: double loading when targetting a message

---

package/src/components/MessageList/utils/getDateSeparators.ts
package/src/components/MessageList/utils/getGroupStyles.ts

Fixes #2714 
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>

fix: inline date separator not being rendered for deleted message appropriately

---

docusaurus/docs/reactnative/guides/custom-message-actions.mdx
package/src/components/Message/MessageSimple/ReactionList/ReactionListBottom.tsx
package/src/contexts/themeContext/utils/theme.ts

The design of the ReactionList was broken when more reactions existed in the list, so this has been improved in the PR.
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>

fix: design issues with ReactionList bottom UI

---

package.json
package/src/components/Message/Message.tsx
release/next.js
release/release.config.js
yarn.lock

BREAKING CHANGE: Update the Message.tsx conditional in the component to use ternary

feat: improve Message.tsx render conditional

---

package/package.json
package/src/components/ImageGallery/ImageGallery.tsx
package/src/components/ImageGallery/components/AnimatedGalleryImage.tsx
package/src/components/ImageGallery/components/AnimatedGalleryVideo.tsx
package/src/components/ImageGallery/hooks/useAnimatedGalleryStyle.tsx
package/src/components/ImageGallery/hooks/useImageGalleryGestures.tsx
package/yarn.lock

The warning on RN 0.74 with the React native reanimated throws:
```
WARN  [Reanimated] Reading from `value` during component render. Please ensure that you do not access the `value` property or use the `get` method of a shared value while React is rendering a component.
If you don't want to see this message, you can disable the `strict` mode. Refer to:
https://docs.swmansion.com/react-native-reanimated/docs/debugging/logger-configuration for more details.
```
This has been fixed in multiple places, including the ImageGallery, AnimatedImageGallery and AnimatedGalleryVideo components.
For the `useImageGalleryGestures`, the `index` is not at all an animated value but can be managed using a local state, so that is what I have done in the PR, and the change is for the better.
There was a bug …

fix: way of reading the value from animated shared values in the components

---

package/src/contexts/messageInputContext/MessageInputContext.tsx
package/src/contexts/messageInputContext/__tests__/pickFile.test.tsx
package/src/contexts/messageInputContext/hooks/useCreateMessageInputContext.ts

Solves the `typing` errors mentioned in [this GH issue](https://github.com/GetStream/stream-chat-react-native/issues/2737).
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>

fix: disable typing events when offline

---

package/src/components/MessageInput/MessageInput.tsx

Fixes this [GH issue](https://github.com/GetStream/stream-chat-react-native/issues/2747).
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>

fix: message disallowed indicator display

---

package/src/components/Message/MessageSimple/MessageContent.tsx
package/src/components/Message/MessageSimple/MessageReplies.tsx
package/src/components/MessageOverlay/MessageOverlay.tsx
package/src/components/Thread/__tests__/__snapshots__/Thread.test.js.snap
package/src/contexts/themeContext/utils/theme.ts

The goal of the PR is to fix the theme around the sender and receiver colour of the message bubble.
| Previous | Now |
| - | - |
| ![simulator_screenshot_52CF461B-D545-4E3A-B9AA-7E1A6214BC4E](https://github.com/user-attachments/assets/348b4362-c01b-487e-8349-de948028d666) | ![simulator_screenshot_FBB1051C-AA4C-422F-8A9E-349121F1BF3C](https://github.com/user-attachments/assets/43608b67-7713-41c5-ab29-af24f731d2d5) |
| Previous | Now |
| - | - |
| ![simulator_screenshot_008D4EC3-2EC4-423F-BF84-608106F9127D](https://github.com/user-attachments/assets/e604d47f-308d-444a-b22c-489edf8e974a) | ![simulator_screenshot_41613DB6-87A2-4DD7-9579-39C3B883515C](https://github.com/user-attachments/assets/d5a88ab0-4215-443d-b639-a1533f54e6ef) |

fix: theme for the message bubble and replies

---

package/src/components/Channel/Channel.tsx
package/src/components/ChannelPreview/hooks/useLatestMessagePreview.ts
package/src/components/Chat/hooks/handleEventToSyncDB.ts
package/src/components/Poll/CreatePollContent.tsx
package/src/components/Reply/Reply.tsx
package/src/store/QuickSqliteClient.ts
package/src/store/apis/getChannelMessages.ts
package/src/store/apis/updateMessage.ts
package/src/store/apis/updatePollMessage.ts
package/src/store/apis/upsertMessages.ts
package/src/store/mappers/mapMessageToStorable.ts
package/src/store/mappers/mapPollToStorable.ts
package/src/store/mappers/mapStorableToMessage.ts
package/src/store/mappers/mapStorableToPoll.ts
package/src/store/schema.ts

This PR addresses a couple of issues related to polls that I've found:
- The offline storage was kind of wonky, so I opted into moving polls to a separate table in the DB; this should both improve performance and data persistence
- A bug where leaving the max votes switch toggled but the upstream one not would cause the lower switch to be preferred
- Issues when thread replying to a poll (the message disappearing as well as replies not working)
- Latest messages in `ChannelList` fixes too
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td> …

fix: poll edge cases

---

package/src/components/Channel/Channel.tsx
package/src/components/MessageList/MessageList.tsx

This PR should resolve: 
- This [GH issue](https://github.com/GetStream/stream-chat-react-native/issues/2591) (and all related to it)
- This [Zendesk ticket](https://getstream.zendesk.com/agent/tickets/57269)
- Possibly any other issues related to scrolling to bottom after loading the first unread message
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>

fix: scroll to recent issues

---

package/src/components/ChannelList/hooks/usePaginatedChannels.ts

Brief rundown:
- Marking channels as `read` was not working properly
- Scrolling to first unread message was not working at all
- There was a race condition where `reloadChannel` could be invoked before the offline channels were fetched (in offline mode) thus putting the entire app in a broken state that was unresolvable on its own (and probably corrupting the DB as well)
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>

fix: critical v6 bugs

---

package/src/components/MessageInput/MessageInput.tsx

It appears that on version `0.76.0` of React Native and onwards Android modals are known to bug out if it is not immediately clear what the size of their parent is, even if it's enclosed and completely predictable. It's not entirely clear to me (yet) if this is a new architecture thing or something else. The change makes sure that the `Modal`'s immediate parent is correct and signals the Android internals to properly calculate the size of the modal. 
Special styling overrides to the modal are not given because:
- This is something that is meant to be used internally (and I want it to stay that way), since integrators can always override the behaviour of the poll creation button and spin up their own modal if they need something specific
- We anyway want to enforce the proper use of …

fix: android poll creation modal size

---

package/src/components/ChannelPreview/hooks/__tests__/useChannelPreviewMuted.test.tsx
package/src/components/ChannelPreview/hooks/useChannelPreviewData.ts
package/src/components/ChannelPreview/hooks/useIsChannelMuted.ts

This addresses 2 issues:
- Makes sure `muteStatus().muted` is used to determine whether the channel is muted (and not just the object returned)
- Makes sure `channel.muteStatus()` is not invoked before the channel is initialized
The latter should almost never happen as we have control over this, however there was an instance of this happening when going from background -> foreground with the app.
Note: Will also be backported to V5.
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>

fix: is muted hook crash

---

examples/SampleApp/src/hooks/useChatClient.ts
package/src/store/SqliteClient.ts

As @khushal87 found out, we occasionally had some race conditions when opening and closing the DB, specifically during resetting it. These changes should help with that and make sure this doesn't happen.
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>

fix: db open close issues

---

package/src/components/MessageInput/MessageInput.tsx

This is a backport of [this PR](https://github.com/GetStream/stream-chat-react-native/pull/2783), currently available only on V6.
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>

fix: android modal size

---

package/src/components/MessageList/hooks/useMessageList.ts
package/src/components/MessageList/utils/getReadStates.ts
package/src/contexts/channelsStateContext/ChannelsStateContext.tsx
package/src/contexts/channelsStateContext/useChannelState.ts

The goal of the PR is to remove the subscriber count increase/decrease logic, which is redundant, and improve types to use the client directly rather than rely on ChannelContext.

refactor: remove stale subscriber count logic and types refactor

---

package/src/components/Channel/Channel.tsx
package/src/components/Message/MessageSimple/utils/generateMarkdownText.ts
package/src/components/Thread/__tests__/__snapshots__/Thread.test.js.snap

Fixes the occasional `regex maximum depth reached` error. 
Not going to go into the specifics on why this happens as they're complicated, but I will add a few bullet points:
- Tried porting the latest version of `simple-markdown` available [here](https://github.com/Khan/perseus/tree/main/packages/simple-markdown), but nothing changed with that and the issue is still noticeable
- The issue typically happens whenever we have one (or more) `\n` characters, followed by many white spaces; the regex state machine runs something similar to `/\s+/g` at one point, which considers both. However, despite treating them both as the same character under `\s`, it actually does a ridiculous amount of backtracking and combinations while all that's going on, even due to a single `\n` character as it tries …

fix: regex max stack depth crash

---

package/src/components/ChannelPreview/ChannelPreview.tsx
package/src/components/ChannelPreview/__tests__/ChannelPreview.test.tsx
package/src/components/ChannelPreview/hooks/useChannelPreviewData.ts

This PR addresses a couple of regressions that we've introduced with some of the `ChannelList` cleanup. Most notably:
- The latest message not being updated within `ChannelPreview` in certain scenarios
- Unread count being volatile and not always updating as expected
- `ChannelPreview` not rerendering when it should (despite the state updating)
- The read state not updating in real time whenever another user reads a message in a 1on1 `Channel`
As a bonus, the `useChannelPreviewData` hook has been stabilized, in the sense that it no longer requires `forceUpdate` to be passed in order for it to function properly (meaning integrators can now use it once we add it to the docs).
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr> …

fix: channel hook extraction regressions

---

package/expo-package/src/optionalDependencies/pickImage.ts
package/native-package/src/optionalDependencies/pickImage.ts

Fixes this [Zendesk ticket](https://getstream.zendesk.com/agent/tickets/58471).
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>

fix: expo media library permissions race conditions

---

package/src/components/ChannelPreview/hooks/useChannelPreviewData.ts

Reverts back to the changes discussed in [this Slack thread](https://getstream.slack.com/archives/C06CF5TKRGA/p1732023470613829) (thanks @myandrienko ).
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>

fix: listen to correct channel read events

---

package/expo-package/src/optionalDependencies/pickImage.ts
package/native-package/src/optionalDependencies/pickImage.ts
package/src/components/ChannelPreview/ChannelPreview.tsx
package/src/components/ChannelPreview/__tests__/ChannelPreview.test.tsx
package/src/components/ChannelPreview/hooks/useChannelPreviewData.ts

Backporting the following v6 PRs:
- https://github.com/GetStream/stream-chat-react-native/pull/2792
- https://github.com/GetStream/stream-chat-react-native/pull/2793
- https://github.com/GetStream/stream-chat-react-native/pull/2795
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>

fix: backporting variety fixes

---

package/expo-package/src/index.js

Fixes a critical issue on expo where the `MessageList` component was not rendering anything due to a missing native dependency being exported from the upstream package. 
We need to do this now since we handle defaults directly in the variants themselves.
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>

fix: add FlatList default for Expo

---

examples/ExpoMessaging/yarn.lock
examples/SampleApp/yarn.lock
examples/TypeScriptMessaging/yarn.lock
package/package.json
package/src/utils/utils.ts
package/yarn.lock

This PR:
- Enables the Moderation V2 flow on our SDK
- It also fixes the V1 flow which was broken
- It keeps backwards compatibility to the V1 flow as well
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>

feat: enable moderation v2 on the sdk and sample apps

---

package/src/components/Chat/hooks/useIsOnline.ts

Fixes a very old and prominent issue we've had in the SDK where sometimes upon a very specific queue of actions messages would stop updating in real time. 
The issue is well documented in the following issues:
- This [GH issue](https://github.com/GetStream/stream-chat-react-native/issues/2305)
- This [Zendesk ticket](https://getstream.zendesk.com/agent/tickets/57225)
- Many other scattered comments across other issues that I'm unable to find right now
Despite the oneliner fix, this issue was incredibly difficult to reproduce consistently - especially because typically it would manifest differently across different integrations.
The TL;DR version of it is:
- Whenever we put the app using the SDK in background (either through going to background, locking the phone or whatever) we close the …

fix: channel.state break on going to background

---

package/src/components/MessageOverlay/MessageOverlay.tsx
package/src/components/MessageOverlay/OverlayReactions.tsx
package/src/components/MessageOverlay/hooks/useFetchReactions.ts

The goal of the PR is to show the reactions in the Thread messages, which were buggy previously and were not displayed.

fix: show user reactions in threads

---

package/src/components/Chat/hooks/__tests__/useAppSettings.test.tsx
package/src/components/Chat/hooks/useAppSettings.ts

<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>

fix: add safeguard for querying app settings

---

package/src/components/Attachment/AudioAttachment.tsx
package/src/utils/getTrimmedAttachmentTitle.ts

fix: audio attachment title overflow issue

---

package/src/components/Attachment/Gallery.tsx
package/src/components/ImageGallery/hooks/useAnimatedGalleryStyle.tsx

This PR fixes 2 issues on V6 and new architecture:
- The closing animations of our image gallery being completely broken (with ghost animations happening after the fact)
- An issue of having an infinite loading spinner of images within image thumbnail components for `Gallery` attachment messages
More details on the actual changes.
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>

fix: image gallery issues

---

package/src/components/MessageInput/MessageInput.tsx

Fixes [this Zendesk issue](https://getstream.zendesk.com/agent/tickets/59176).
This technically gets rid of the behaviour that we can override how the UI behaves regardless of capabilities. The reason why we need to do it is because of the fact that:
- The `disableIfFrozenChannel` override can override how the UI behaves but it will still never allow you to actually send messages (if no permissions/capabilities are present you will always have the message bounced back by our backend)
- Due to its default being `true`, it would also mean that having frozen channels that can receive messages from certain roles (that have the correct permissions) would not be possible unless specifically set to `false`, which is not the default behaviour we preach and want to have
Instead, we should have:
- …

fix: only disable message input ui when capabilities change

---

package/src/components/MessageInput/__tests__/MessageInput.test.js

This is a followup to [this PR](https://github.com/GetStream/stream-chat-react-native/pull/2836), as we were trying to get it out as soon as possible in order to fix an incident. Tests were lacking in this department, causing the regression.
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>

chore: write tests for disallowed sending messages

---

package/src/components/Channel/Channel.tsx
package/src/components/MessageInput/MessageInput.tsx
package/src/components/MessageInput/__tests__/MessageInput.test.js

A forward port of [this change](https://github.com/GetStream/stream-chat-react-native/pull/2836) to V6.
As agreed, we remove the `disableIfFrozenChannel` prop as it causes a bad state between the BE and our SDK.
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>

chore: remove disable if frozen channel

---

.github/workflows/check-pr.yml
.github/workflows/docusaurus.yml
.github/workflows/next-release.yml
.github/workflows/sample-distribution.yml
.github/workflows/sdk-size-metrics.yml
release/next.js

<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>

chore: v6 preparation ceremonies

---

package/src/components/MessageMenu/MessageReactionPicker.tsx
package/src/components/MessageMenu/MessageUserReactions.tsx
package/src/components/index.ts

The goal of the PR is to export useFetchReaction hook from the SDK and unify a couple of TS types.

fix: export useFetchReaction hook from SDK and TS improvements

---

examples/SampleApp/App.tsx
package/src/components/ImageGallery/components/ImageGalleryFooter.tsx
package/src/components/ImageGallery/components/ImageGalleryHeader.tsx
package/src/contexts/themeContext/utils/theme.ts

<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>

fix: image gallery safe area

---

package/src/components/Channel/Channel.tsx
package/src/components/MessageInput/MessageInput.tsx
package/src/components/MessageInput/components/AudioRecorder/AudioRecordingButton.tsx
package/src/components/Thread/__tests__/__snapshots__/Thread.test.js.snap

There was a bug, lets say you have the `expo-av` package but disabled the async audio feature using the prop on Channel component but it would still show the recording button. This is fixed in the PR.

fix: change default value of audioRecordingEnabled and not rely on package availability for default value

---

package/src/components/Message/MessageSimple/MessageStatus.tsx
package/src/components/MessageList/hooks/useLastReadData.ts
package/src/components/MessageList/hooks/useMessageList.ts
package/src/components/MessageList/utils/getReadStates.ts

The PR fixed the issue where the `readBy` status was updated only for the last message of the message list and not for others. Technically it should be updated for all the messages no matter you show it or not.

fix: incorrect read state for messages

---

package/src/components/AITypingIndicatorView/hooks/useAIState.ts
package/src/components/Channel/Channel.tsx

This PR fixes the problems mentioned in [this GH issue](https://github.com/GetStream/stream-chat-react-native/issues/2894).
- The reconnect issue is a regression that happened in V6 of our SDK, where no actual HTTP calls were being done when trying to reconcile the state when recovering connection
- The other one is an improper use of a hook within the SDK, causing the property to be ignored altogether (as the second time it is being invoked is deeper within the DOM tree)
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr> …

fix: message list connection reconciliation

---

package/src/components/Attachment/Gallery.tsx
package/src/components/Message/Message.tsx

Resolves [this Zendesk issue](https://getstream.zendesk.com/agent/tickets/60784).
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>

fix: add thumbnail info on gallery press handlers

---

package/src/components/Attachment/Gallery.tsx
package/src/components/Message/Message.tsx

A backport of [this PR](https://github.com/GetStream/stream-chat-react-native/pull/2911) to V5.
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>

fix: backport attachment thumbnail fix

---

package/expo-package/src/optionalDependencies/getPhotos.ts
package/native-package/src/optionalDependencies/getPhotos.ts

<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>

fix: warn users about new google policy and to replace cameraroll with image-picker

---

examples/ExpoMessaging/yarn.lock
examples/SampleApp/ios/Podfile.lock
examples/SampleApp/yarn.lock
examples/TypeScriptMessaging/ios/Podfile.lock
examples/TypeScriptMessaging/yarn.lock
package/expo-package/yarn.lock
package/native-package/yarn.lock
package/package.json
package/yarn.lock

The issue is explained in [this PR](https://github.com/GetStream/stream-chat-js/pull/1456).
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>

fix: bump stream-chat-js version for poll state invalidation bug

---

package/src/components/Message/MessageSimple/utils/generateMarkdownText.test.ts
package/src/components/Message/MessageSimple/utils/generateMarkdownText.ts
package/src/components/Message/MessageSimple/utils/renderText.tsx

The PR is responsible for the preview of the blockquote in the message text.

feat: add blockquote support for preview in message

---

package/src/__tests__/offline-support/offline-feature.js
package/src/components/ChannelList/ChannelList.tsx
package/src/components/ChannelList/hooks/listeners/useChannelVisible.ts
package/src/components/ChannelList/hooks/listeners/useNewMessageNotification.ts

This PR fixes an issue with channel pinning where pinned channels aren't respected if a channel goes from hidden to visible.
Steps to reproduce:
- Pin 1 or more channels within `ChannelList`
- Take another `channel` (not a pinned one) and `channel.hide()` it
- After that, run `channel.show()` without reloading the app (so that no HTTP requests are done in the meantime)
- The recently shown `channel` will not respect pinned ones
~~Also, pretty sure that `notification.message_new` handler is also incorrect since it doesn't take archiving into account, but will look into that on Monday.~~
Update: This was indeed an issue with `notification.message_new` as well and is fixed in this PR.
This is already fixed in the [recent reactive channel list state PR in the …

fix: channel.visible not taking sort and pinned channels into account

---

package/src/components/Message/MessageSimple/MessageSimple.tsx

Should fix [this Github issue](https://github.com/GetStream/stream-chat-react-native/issues/2940).
The TL;DR is that the gesture was getting rid of its own activation criteria and relying on manual activation. In these cases, if the gesture is indeed recognized (for example from a long press) but the state is **not** managed manually it will not know how to recover properly (for example `state.fail()` if it's not the correct gesture). 
As there isn't enough time for the gesture to actually fail before the bottom sheet pops up, the entire handling was caught in a weird state.
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table> …

fix: animation start event breaking ui responsiveness

---

examples/SampleApp/src/components/MenuDrawer.tsx
examples/SampleApp/src/components/SecretMenu.tsx
examples/SampleApp/src/hooks/useChatClient.ts

This PR creates a way for us to switch push providers on the fly. It's meant to be used for testing purposes while the BE team works on the new PN infrastructure.
How-to:
- In the user menu (top left corner), you can press on the currently logged in user's name/image 7 times and another menu will appear
- In this menu you can:
- Choose between preset push providers (currently only `Firebase` and `APNs`)
- Remove all devices for the given user
Whenever switching between push providers please make sure to also close and reopen the app.
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td> …

chore: secret menu for dev config

---

examples/SampleApp/src/components/SecretMenu.tsx
examples/SampleApp/src/hooks/useChatClient.ts

I missed resolving this issue in the [previous PR](https://github.com/GetStream/stream-chat-react-native/commit/7ea43d4c389aa81213e419c03c6460dbf0b40abc).
We essentially need to ask for permissions manually as of the newer Android versions.
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>

fix: android push notification permission issues

---

package/src/components/Attachment/Gallery.tsx
package/src/contexts/themeContext/utils/theme.ts

It appears that in some integrations our `Gallery` component within `MessageList` was behaving weirdly.
Although this was not reproducible (for me at least) on our:
- `Expo` sample app
- A brand new `Expo` application
it is explained in detail in [this Github issue](https://github.com/GetStream/stream-chat-react-native/issues/2939).
Regardless, exposing `imageContainerStyle` within our `theme` system should allow these properties to be overridden and unset from the styles if needed.
Many thanks to @PRASSamin for [this PR](https://github.com/GetStream/stream-chat-react-native/pull/2946) and for tracking down the origin of the issue.
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table> …

chore: make imageContainerStyle theme compliant

---

package/src/components/MessageMenu/MessageActionList.tsx
package/src/components/MessageMenu/MessageUserReactions.tsx
package/src/components/UIComponents/BottomSheetModal.tsx
package/src/contexts/themeContext/utils/theme.ts

The goal of the PR is to make the FlatList/ScrollView responsive inside the BottomSheetModal. We were using the one from React native, which was not working with the gesture handler, so we migrated it to the one from `react-native-gesture-handler`.
As a part of the PR, the bottom sheet is also improved, and the pan gesture reacts to the gesture we put in the UI.
https://github.com/user-attachments/assets/e1ab6ae2-faf3-41ad-b4ee-2262f8ca14e6

fix: change flatlist inside the bottom sheet modal and fix gesture in bottom sheet

---

package/src/components/Channel/Channel.tsx

Since the `channel` class instance is not reactive, we've traditionally relied on copying over the `ChannelState` from the LLC every time a relevant WS event arrives. 
We do not need this for polls, as they themselves are reactive and don't rely on this behaviour.
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>

perf: do not rerender Channel on poll events

---

package/src/components/Channel/Channel.tsx
package/src/components/MessageList/MessageList.tsx
package/src/components/MessageList/hooks/useShouldScrollToRecentOnNewOwnMessage.ts

This PR addresses [this GH issue](https://github.com/GetStream/stream-chat-react-native/issues/2954).
Essentially, we were wrapping the copying of the `channel` state from our LLC in a `ref` which was never updated, thus resulting in an issue whenever we don't explicitly unmount and then remount the `Channel` component.
Although it is not very common behaviour to have this working like explained on mobile devices, it is very common on tablets for example where we're aiming for more of a web-like behaviour. 
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr> …

fix: state break on channel prop update

---

package/src/components/Channel/Channel.tsx

<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>

fix: use channel.cid instead of id

---

examples/SampleApp/src/components/SecretMenu.tsx
examples/SampleApp/src/hooks/useChatClient.ts
examples/SampleApp/src/screens/AdvancedUserSelectorScreen.tsx

A new entry is added to the secret menu, which allows the provider name to be overridden of the currently selected provider. The name persists through reloads and such. Needed for debugging the new PN architecture.
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>

feat: add the ability to override pn provider names

---

package/src/components/MessageList/MessageList.tsx

It appears that for some RN versions we still have the issue of `onViewableItemsChanged` throwing an invariant violation whenever it changes dynamically, causing a regression here. We can keep this workaround for now and get rid of it on the next major release.
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>

fix: onViewableItemsChanged invariant violation

---

package/src/store/apis/queries/selectMessagesForChannels.ts

This PR fixes a regression that we introduced about a month ago which causes a specific chain of events to break pagination in the `MessageList` whenever offline support is enabled. 
Steps to reproduce:
- Open a freshly installed app
- Load the `ChannelList` component
- Close the app or log out (this is important, so that we don't receive any WS events)
- Receive some messages in a channel (anything >= 1 message)
- Open the app again
- Open the channel which received messages
- You are now unable to paginate to previous messages
With a recent bugfix to pagination, we pessimistically set the pagination cursors to `false` as an initial value. The bugfix relies on the fact that whenever we query for new messages, we should heuristically be able to figure out whether we have earlier (or …

fix: return properly sorted messages from offline DB

---

package/native-package/package.json
package/native-package/src/optionalDependencies/pickDocument.ts

Since we had to keep support for both `react-native-document-picker` and `@react-native-documents/picker` in V6, in V7 we remove support for the stale `react-native-document-picker`. 
This change is done as part of this Linear ticket: https://linear.app/stream/issue/RN-148/v7-of-the-stream-chat-react-native-sdk
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>

chore: remove support for react-native-document-picker

---

package/src/components/ChannelList/hooks/usePaginatedChannels.ts

This PR fixes an unintended regression that happened with the new reactive channel list change.
It should fix [this GH issue](https://github.com/GetStream/stream-chat-react-native/issues/3003). It has no performance implications thanks to batched state updates.
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>

fix: properly resolve activeQueryType state

---

package/src/components/ChannelPreview/hooks/useChannelPreviewDisplayAvatar.ts
package/src/components/ChannelPreview/hooks/useChannelPreviewDisplayName.ts
package/src/components/ChannelPreview/hooks/useChannelPreviewDisplayPresence.ts
package/src/components/ChannelPreview/hooks/useIsChannelMuted.ts
package/src/components/ChannelPreview/hooks/useLatestMessagePreview.ts

The goal of the PR is to improve the channel preview display hooks to use `useMemo` instead of a combination of `useState` and `useEffect` for the calculation that would take an additional render.
Also, the title logic for the channel preview is improved for channels that have long names. This was a UI issue that was easily noticeable and looked bad.
I am open to discussion if anything doesn't seem correct here. 
Linear - https://linear.app/stream/issue/RN-151/improve-channel-preview-hooks-performance-and-seek-for-improvements

fix: improve channel preview display hooks and long title issue

---

package/src/components/ChannelPreview/hooks/useLatestMessagePreview.ts
package/src/hooks/useTranslatedMessage.ts

Linear issue - https://linear.app/stream/issue/RN-154/optimize-read-events-calculation-on-the-uselatestmessagepreview-hook

fix: memoize the read_events calculation to make it save a rerender

---

package/src/components/ChannelList/ChannelList.tsx
package/src/components/ChannelList/__tests__/ChannelList.test.js
package/src/components/ChannelList/hooks/listeners/useUserPresence.ts
package/src/components/ChannelList/hooks/useChannelMembershipState.ts
package/src/components/ChannelPreview/hooks/__tests__/useChannelPreviewDisplayPresence.test.tsx
package/src/components/ChannelPreview/hooks/useChannelPreviewDisplayPresence.ts
package/src/hooks/useSelectedChannelState.ts
package/src/hooks/useSyncClientEvents.ts

When the user presence changed previously, the entire Flatlist/ChannelList re-rendered due to the fact that the `setForceUpdate` was explicitly triggered, which is a bad practice. This has been improved by moving the display presence logic to the Channel Preview using the `useSyncExternalStore` to optimize the re-renders and the performance of the ChannelList.
Previous:
https://github.com/user-attachments/assets/62d70310-8f97-45d4-ba0b-7ae248d099c5
Now:
https://github.com/user-attachments/assets/aa036a51-11db-4f18-b0e7-7e8361b3f662

fix: improve the entire channel list re-render for useUserPresence hook

---

package/native-package/src/optionalDependencies/pickImage.ts

Fixes [this issue](https://linear.app/stream/issue/RN-159/users-having-issues-with-video-uploads-[-high-priority]) and [this Zendesk ticket](https://getstream.zendesk.com/agent/tickets/62568).
Due to how `assetRepresentationMode: auto` works sometimes, files and videos in general increase in size (and if they were just below the threshold of 100MB it is very possible that this tips them over). To make things worse, if the OS does decide that it can provide a better resolution/quality of the video we need to wait for the conversion too (even before being able to figure the size out).
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details> …

fix: native-image-picker pickImage issue

---

.github/workflows/sample-distribution.yml
package/src/components/Channel/Channel.tsx

This PR fixes a bug in V5 where scrolling to the first unread message was behaving in a weird way. It either sometimes would not happen or when it did it would not respect message sets properly. 
This PR should fix these issues.
Closes [this Zendesk ticket](https://getstream.zendesk.com/agent/tickets/62480) and [this Linear issue](https://linear.app/stream/issue/RN-157/issue-with-initialscrolltofirstunreadmessage-functionality-in-channel).
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>

fix: initial scroll to first unread v5

---

package/src/components/Message/MessageSimple/MessageStatus.tsx
package/src/components/Message/MessageSimple/__tests__/MessageStatus.test.js
package/src/components/Message/MessageSimple/__tests__/__snapshots__/MessageStatus.test.js.snap

The PR's goal is to show the correct read status(readBy number) on the message status component.
For 1:1 channels/group channels with only two users:
- We will no longer show the read count as it doesn't make sense since the only user who can read the message is the other user. 
- We only update the check mark to double if the other user has read the message in the channel. This was buggy before. ⚠️ 
For channels with more group members:
- We will show a single check mark until no one has read the message in the channel. We do not show any read count until then.
- Update it to double as soon as someone reads the message and then show the count of how many **other** users have read the message. Previously, it included my read count as well, which was buggy. ⚠️ 
This is inline with the iOS …

fix: show correct read status on the message status component for a message

---

package/src/components/Channel/Channel.tsx
package/src/components/MessageList/MessageList.tsx

The PR is responsible for fixing the current unread indicator pill visibility on the Message List. 
- When you send a lot of messages post the viewable area, the indicator appeared which was buggy. This is now fixed.
- When you send a single long message in the message list that is more than the visible area the indicator appeared. It is fixed as well.
- When you are somewhere above in the message list, when you scroll to bottom, you would expect to see the unread messages label in the message list on top of the first unread received message. This is fixed as well. 
Linear issue - https://linear.app/stream/issue/RN-158/investigate-faulty-appearance-of-unread-indicator-label-in-message

fix: unread indicator label presence in message list

---

package/src/components/Attachment/AudioAttachment.tsx
package/src/hooks/useAudioPlayer.ts

Fixes [this Github issue](https://github.com/GetStream/stream-chat-react-native/issues/3036).
Tons of credit to @thib92 for the [initial fix](https://github.com/GetStream/stream-chat-react-native/pull/3037) !
Linear issue: https://linear.app/stream/issue/RN-173/[]-voice-message-playback-runs-an-infinite-useeffect-loop-in-v6
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>

fix: audio component recursive loading for expo

---

package/expo-package/yarn.lock
package/native-package/yarn.lock
package/src/components/UIComponents/BottomSheetModal.tsx

This PR fixes a nasty bug where if the reaction list is open, receiving new reactions would trigger a run of an effect that handles the animation. 
Linear ticket: https://linear.app/stream/issue/RN-185/receiving-new-reaction-while-reaction-list-is-open-causes-unwanted
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>

fix: bottom sheet animations on new reactions

---

package/src/components/Attachment/AudioAttachment.tsx
package/src/hooks/useAudioPlayer.ts
package/src/native.ts

fix: audio distortion on audio rate change

---

package/src/types/types.ts

The `RNFile` was changed to `FileReference` lately on the LLC message composer branch so, that has been take care of here.

fix: change RNFile to FileReference as per latest client changes

---

package/src/contexts/channelsStateContext/useChannelState.ts

This is an interesting bug that we caught within smoke testing of V7.
Essentially, this has been a dormant issue in the SDK for ages; pretty much relying on the fact that our `MessageList` would rerender literally every time one of its parents rerendered (and completely rereference its `data` in the process). In that regard, this would work because of cascading state updates that happened on the `Channel` HoC level.
Since this was fixed in one of the recent performance improvement PRs, the faulty behaviour was no longer in place and the dormant bug came to the horizon.
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead> …

fix: thread messages setting broken

---

package/src/components/KeyboardCompatibleView/KeyboardCompatibleView.tsx

The fix is as per the patch provided here - https://github.com/facebook/react-native/issues/29974#issuecomment-700804626

fix: keybaord taking full screen issue when the prefer cross-fade transition setting is enabled on iOS

---

package/src/hooks/useStateStore.ts

The goal of the PR is inspired by https://github.com/GetStream/stream-chat-react/pull/2573. I was trying to reply to a message where I noticed that when replying to a poll message, and then if you reply to some other message, the poll message doesn't go away from the UI, and that is because of https://github.com/GetStream/stream-chat-react-native/blob/develop/package/src/components/Reply/Reply.tsx#L180 not resetting as it should. React added this change in the past to the `useStateStore` hook they have, which we never added to fix a similar bug. This is a possible fix to the issue, as previously changing the store in the hook would keep the previously calculated state and return it. 
**Prev**
https://github.com/user-attachments/assets/050b5709-21f9-4950-9bf5-14e550494278
**Now** …

fix: use useSyncExternalStore in the useStateStore hook

---

package/src/components/ChannelList/hooks/usePaginatedChannels.ts

Fixes [this Zendesk ticket](https://getstream.zendesk.com/agent/tickets/64773).
In the event of an error occurring while the `ChannelList` is loading, the `error` state is not preferred over the loading one and in due to how offline support works on the current version, we need to have an extra check for loading because of it which was causing as stuck loading state. 
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>

fix: prefer error screen over loading screen

---

package/src/components/Attachment/FileAttachmentGroup.tsx
package/src/components/Message/MessageSimple/MessageSimple.tsx

This PR fixes an issue of file attachment components would remount with an empty state, causing weird layout switches sometimes. It also fixes a race condition with how animations are calculated if multiple are triggered at the same time.
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>
<details>
<table>
<thead>
<tr>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
</details>

fix: remounting specific attachments and jittery fast anims

---

package/src/components/Message/MessageSimple/ReactionList/ReactionListBottom.tsx
package/src/components/MessageMenu/MessageUserReactionsItem.tsx
package/src/contexts/themeContext/utils/theme.ts

Ref - https://getstream.slack.com/archives/C05BVRH1FDZ/p1747761373882249

fix: add filled and unfilled bg color theme properties for ReactionListBottom

---

package/src/components/Channel/Channel.tsx
package/src/components/MessageList/MessageList.tsx

This PR should fix 2 things:
- Unreliable visibility of the unread message notification (especially when sending longer messages that would take the last read message out of the viewport)
- Display of the unread message overlay when message sending is delayed (for example, if we send 5-6 consecutive videos which would take time to upload in the offline case)
The general idea is that if the length of the message list changes after the initial time the notification was rendered, we can safely assume that we're present in the channel and do not need to see the notification. Marking a message as unread should still work as intended.
Should also fix [this Zendesk ticket](https://getstream.zendesk.com/agent/tickets/65229).
<details>
<table>
<thead>
<tr> …

fix: visibility of unread notification and underlay in certain scenarios

---

examples/ExpoMessaging/README.md

The readme was a bit confusing - it should mention that expo-package is under the package directory.  I looked for it at the root and didn't see it.
Make readme clear
Update readme
Not applicable

docs: update README.md to make expo-package path clear

---

examples/ExpoMessaging/app.json
examples/ExpoMessaging/plugins/keyboardInsetMainActivityListener.js
examples/SampleApp/android/app/src/main/java/com/sampleapp/MainActivity.kt
examples/SampleApp/ios/Podfile.lock
examples/SampleApp/src/screens/ThreadScreen.tsx
examples/SampleApp/yarn.lock
examples/TypeScriptMessaging/android/app/src/main/java/com/typescriptmessaging/MainActivity.kt
package/src/components/KeyboardCompatibleView/KeyboardCompatibleView.tsx

This PR fixes an issue with our `KeyboardCompatibleView` within the SDK that surfaced on `Android 15` in the RN upstream. 
The actual open issue can be seen [here](https://github.com/facebook/react-native/issues/49759), while the Android changes that triggered this can be found [here](https://developer.android.com/about/versions/15/behavior-changes-15#ux).
This fix should:
-  Fix some `KeyboardCompatibleView` edge cases and introduce slight performance improvements with skipping unnecessary state updates when they aren't needed
- Do the RN CLI adjustments in the sample apps required for this to work (until it's fixed upstream)
- Showcases a custom `Expo` plugin that does the same for the `Expo` sample app
Should also close [this Zendesk …

fix: android 35 keyboard issues

---

package/src/components/MessageList/MessageList.tsx

This PR addresses an issue where the `MessageList`'s underlying `FlatList` would get caught in a weird infinite scrolling (into nothing) state whenever we removed the last `item` inside of it. 
This was particularly obvious on `threads`, with the following reproduction steps:
- Set `deletedMessagesVisibilityType={'never'}` on the `Channel` component encapsulating a `Thread`
- Create a `thread` from a message
- Write a single `message` into the `thread`
- Delete the message (no `Deleted Message` default as we set the visibility to `never`)
- The `FlatList` would now spin endlessly
The actual issue is that the `FlatList` completely bugs out whenever we pass it an `index` it can clearly not find (since the message got deleted, the index no longer exists. Instead, we keep the …

fix: properly set minIndexForVisible

---

package/src/components/MessageList/MessageList.tsx
package/src/components/Thread/__tests__/__snapshots__/Thread.test.js.snap

Due to a bug in earlier RN versions, we needed to implement a workaround for Android regarding inversions of the FlatList.
It boils down to [this value here](https://github.com/GetStream/stream-chat-react-native/blob/857d2203559bf093be61c45a019d7e96ff9fd10b/package/src/components/MessageList/MessageList.tsx#L738).
Since starting with V8 we are supporting only version 0.73.0 of React Native and onwards, we are finally safe to remove this. 
It should prove to be a minor performance boost on Android.

fix: remove inverted list android workaround

---

package/src/components/Channel/Channel.tsx

Even when the `expo-media-library` was not installed the attachment picker would render in the UI which shouldn't be done. This is fixed in the PR.

fix: optionally render attachment picker as per media library availability

---

package/src/components/MessageList/utils/getGroupStyles.ts

Update condition to check for date separators in group styles.

fix: group styles condition for date separators

---

package/src/components/MessageMenu/MessageUserReactions.tsx
package/src/components/MessageMenu/hooks/useFetchReactions.ts

The goal of the PR is to fix the message user reactions UI refreshing multiple times due to the reactions data changing very often inside the `useFetchReaction` hook. This has been optimized. Also the bug where the next data was loading infinitely inside the hook on end reached has been fixed effectively in the PR.

perf: re-render issue in the useFetchReactions hook

---

package/src/contexts/messageInputContext/hooks/useCreateMessageComposer.ts

Fixes a similar issue as https://github.com/GetStream/stream-chat-react/issues/2845 in RN SDK

fix: keep editing message composer with up-to-date edited message reference

---

package/src/components/ImageGallery/ImageGallery.tsx
package/src/components/ImageGallery/components/ImageGalleryFooter.tsx
package/src/components/ImageGallery/hooks/useImageGalleryGestures.tsx

The PR fixes the following issues:
- Improper indexing of the attachment items in the image gallery on the footer.
- Reversed/incorrect scrolling even though you open the first item of the gallery in the image gallery overlay. Please refer to the video to see.
- Reduced motion setting disabled for couple of `withTiming` functions that will help in consistent pan down gesture even when the setting is enabled/disabled. This is the most sensible solution I could found that also avoid hacks of adding any inconsistent values.
- Slight optimization by using the precomputed `photoSelectedIndex` in the useEffect rather than recalculating it. 
New
https://github.com/user-attachments/assets/e64b6b88-4d7f-411b-9c19-744ad0e864b5
Prev
https://github.com/user-attachments/assets/57a51341-4c17-4981-8090-6 …

fix: image gallery animation and wrong indexing
